### ISSUE TITLE
Issue while uploading files with formats like ppsx

### ISSUE THREAD

**Issue by mukulgupta2507** [cloudinary/cloudinary_npm#102]
Hi,

Cloudinary works great if you are uploading images but when it comes to upload files with other formats, I face a lot of issues:
1. Cloudinary makes the file as zip, so after uploading when you try to use the file again. You get a zipped folder rather than the original file. For example, uploading a ppt file resulted in zipped folder:

Following response for the api call:

> "public_id":"b16df33a051eb478042900ee1edacdf6_jxutaz","version":1464595390,"signature":"9fed4d3bd191537688e41bf500dc36f327542d25","resource_type":"raw","created_at":"2016-05-30T08:03:10Z","tags":[],"bytes":705578,"type":"upload","etag":"24849bdf12b8b53c51a6c893df850064","url":"http://res.cloudinary.com/dltxrejm4/raw/upload/v1464595390/b16df33a051eb478042900ee1edacdf6_jxutaz","secure_url":"https://res.cloudinary.com/dltxrejm4/raw/upload/v1464595390/b16df33a051eb478042900ee1edacdf6_jxutaz","original_filename":"b16df33a051eb478042900ee1edacdf6"}

Code for uploading the file to cloudinary

```
function uploadFileInCloudinary(fileObj, callback) {
    console.log(fileObj);
    if(fileObj && (fileObj != undefined)) {
        console.log(fileObj['path']);
        cloudinary.uploader.upload(fileObj['path'], {resource_type:"auto", use_filename: true}, function(err, result) {
            if(err) {
                console.log(err);
                return callback(err);
            }
            console.log("cloudinary result");
            console.log(JSON.stringify(result));
            return callback(null, result);
        });
    } else {
        return callback("error");
    }
}
```
1. If I try to get the uploaded file back for rendering to my user using node request module, I'm not able to get proper file:

```
exports.fetchFile = function(req, res, next){
    var fileUrl = "/" + req.params.fileUrl;
    console.log(fileUrl);

    async.auto({
        'A': function(callback) {
            var queryObj = { 'myUrl' : fileUrl};
            UserFileCtrl.fetchUserFile(queryObj, callback);
        }
    }, function(err, results){
        if(err) {
            return res.send(500, "error");
        }

        var secureUrl = results['A']['secureUrl'];
        var fileType = results['A']['fileType'];
        res.setHeader('Content-Type', fileType);
        request(secureUrl).pipe(res);
    }); 
}
```

Here in case of pdf, I get an blank pdf.

Everything work good for images but not for other files. Can anyone please tell me what's the issue over here ?

**Comment by MaorGar** [comment]
Hi,
Thanks for reaching out. 

Cloudinary saves all your files just as you uploaded them. In this case, the file was uploaded with no extension (as you can see from the extension-less public_id), therefore, the returned file is both extension-less and doesn't have an appropriate `content-type`.
Note that if you download the file and try to append it with .pptx extension, it will work.

For future cases, we recommend making sure the uploaded file contains an extension so that the returned file will have the corresponding extension and content-type.

Hope this helps, please let me know if you have any other questions.

Thanks,
Maor

**Comment by mukulgupta2507** [comment]
@MaorGar 
The file was uploaded with an extension, .pps and as far as public id is concerned, in my case i get a public id without any extension for every file, even for images. May be because I'm using "resource_type:"auto" in my upload request. Is it something like, we have to explicitly tell cloudinary about the type of file ? Also, when we use "auto", don't we assume that cloudinary will be able to determine the type of uploaded file on its own ? If this isn't the case, then can you please list valid file types which cloudinary can understand ?

Thanks

**Comment by mukulgupta2507** [comment]
I tried again and this time using "resource_type" as "raw" but it also resulted in same thing. In fact this time, images are also not working. Can you please tell me some way to preserve actual file extensions ?

> {"public_id":"8e80a25bd014380f41e17e073c0cc0a6_asfrmn","version":1464607959,"signature":"a5e6aac0e703c75c5f0233bdf64635edc6c7598e","resource_type":"raw","created_at":"2016-05-30T11:32:39Z","tags":[],"bytes":140288,"type":"upload","etag":"ba050816e3075b4ee8c27b6ec1f99987","url":"http://res.cloudinary.com/dltxrejm4/raw/upload/v1464607959/8e80a25bd014380f41e17e073c0cc0a6_asfrmn","secure_url":"https://res.cloudinary.com/dltxrejm4/raw/upload/v1464607959/8e80a25bd014380f41e17e073c0cc0a6_asfrmn","original_filename":"8e80a25bd014380f41e17e073c0cc0a6"}

**Comment by MaorGar** [comment]
Hi,

In the case of images and videos, that's correct. The public_id for images and videos indeed excludes an extension to allow easy on-the-fly transformation without appending multiple extensions in the URL. 
However, in all other cases (raw files), the extension is included in the public_id (as raw files cannot be transformed). 

When setting `resource_type` as `auto`, Cloudinary takes a look at the file, if it's identified as either an image or a video file, it'll be be categorized as the corresponding resource type (*note, PDFs are also handled as images). All other types are categorized as `raw`. 

We checked the logs of your uploads and noticed that at the case of the two mentioned files, the original uploaded files indeed excluded an extension. Also, the logs showed that some other files were uploaded with extensions and work as expected. I can share some examples, however if privacy is an issue, please feel free to open a support ticket (at support@cloudinary.com) and I'll be happy to continue this with you.
If the problem persists and you're comfortable with it, you can attach the original file you were trying to upload and we can examine it even further.

Best regards,
Maor

**Comment by MaorGariv** [comment]
Hi,

Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
