### ISSUE TITLE
cloudinary.url appends options.format to returned url

### ISSUE THREAD

**Issue by danielmahon** [cloudinary/cloudinary_npm#103]
`cloudinary.url(image.public_id + '.' + image.format, {format: 'jpg'})` returns a url with the `options.format` extension appended to the default extension. Isn't this incorrect? Shouldn't the format option override? Since you always have to provide an extension if you dont provide the format option.

**Example:** `cloudinary.url('/root/folder/myfile.pdf', {format: 'jpg'})`
**Expected:** `http://.../root/folder/myfile.jpg` (good url)
**Actual:** `http://.../root/folder/myfile.pdf.jpg` (bad url)

I understand that you can just send `cloudinary.url('/root/folder/myfile.jpg')`. But then what's the point of format? This seems broken to me, and makes it difficult to program.

**Comment by danielmahon** [comment]
@JedWatson didn't want to pollute keystone's repo but this directly affects it. For example:
`{{ image.fill(125, 125, { format: 'jpg' }) }}` returns a URL with 2 extensions `.jpg.jpg`, which is a bad URL. I have a solution for keystone but I thought it looked like more of a cloudinary issue.

We could change something like this
```
return cloudinary.url(item.get(paths.public_id) + '.' + item.get(paths.format), options);
```
to this
````
options.format = options.format || item.get(paths.format);
return cloudinary.url(item.get(paths.public_id), options);
````

**Comment by taragano** [comment]
Note that the public_id of the image actually excludes the extension part. The extension part tells Cloudinary in which format the image should be delivered in. So either use (if the format you need for the end result is JPG) : 

    cloudinary.url(image.public_id + '.jpg')
or:

    cloudinary.url(image.public_id, {format: 'jpg'})
Using them both will indeed generate a "double-extension" which will cause an error.

**Comment by danielmahon** [comment]
Would it be better to let the format option override the public_id extension that way the error wouldn't exist? Or at least have an error returned instead of a malformed url?

**Comment by taragano** [comment]
Can you please share why it is a requirement for you to use both?

Note that the public ID is passed as is to the URL. The `format` adds an additional extension to what's passed in the `public_id`.
Note that we'll need to keep supporting the current state as some public IDs include dots.

**Comment by danielmahon** [comment]
@taragano You're right, i didnt think of public_id's with periods AND without an extension. I was thinking you would just pop off the extension and replace it with the format option. This would work if the public_id had periods AND the final one designated the extension but would be much harder to determine if the final segment was indeed an extension. This should be a NO FIX. Thanks for responding!

**Comment by taragano** [comment]
I'm glad I could be of assistance. Please feel free to contact us always :)
