### ISSUE TITLE
Cloudinary throws an error when passing width in as a number

### ISSUE THREAD

**Issue by tikotzky** [cloudinary/cloudinary_npm#105]
Seems to be caused by a recent commit.

see: https://github.com/cloudinary/cloudinary_npm/commit/1ea487af9540c8ea0e88cbe79037ac50548878f5#commitcomment-17975693

**Comment by tikotzky** [comment]
I'm getting an error on both `cloudinary.image` and `cloudinary.url` when passing width as a number.

**Comment by tikotzky** [comment]
just cloned the repo to see if I can add a failing test, and I see there is already is a failing test...
see: https://github.com/cloudinary/cloudinary_npm/blob/df7517040ed367ad58870b0965b5f786972c1d84/test/image_spec.coffee#L16

```
  2) image helper should accept scale crop and pass width/height to image tag :
     TypeError: width.startsWith is not a function
    at Object.exports.generate_transformation_string (lib/utils.js:341:25)
    at Object.exports.url (lib/utils.js:525:28)
    at Object.exports.image (cloudinary.js:16:29)
    at Context.<anonymous> (test/image_spec.coffee:17:23)
```

**Comment by TalLevAmi** [comment]
We are working on a fix. Will be released shortly. Sorry about that.

**Comment by tikotzky** [comment]
Thanks!

**Comment by TalLevAmi** [comment]
Version 1.4.1 was pushed to npm that solves the issue.
