### ISSUE TITLE
Version 1.4 breaks uploads with transformations

### ISSUE THREAD

**Issue by Airswoop1** [cloudinary/cloudinary_npm#106]
In the latest version of the repository 1.4, lib/utils.js line 341, there is a check for width.startsWith("auto"). In prior versions <=1.3, the check is width == "auto". The modification to use startsWith expects that the parameter being passed in is a string. If it is a number, (as it was for me), the function throws an unhandled exception.

**Comment by Airswoop1** [comment]
@tocker this should probably hotfixed immediately given the severity of the issue

**Comment by tikotzky** [comment]
its breaking all calls to `cloudinary.image` and `cloudinary.url` as well...
see: https://github.com/cloudinary/cloudinary_npm/issues/105

**Comment by TalLevAmi** [comment]
We are working on a fix. Will be released shortly. Sorry about that.

**Comment by TalLevAmi** [comment]
Version 1.4.1 was pushed to npm that solves this issue.
