### ISSUE TITLE
react native fetch when using FormData whose name of params can not be Chinese 中文键报错！

### ISSUE THREAD

**Issue by r4ggj** [cloudinary/cloudinary_npm#107]
![image](https://cloud.githubusercontent.com/assets/19884878/17918843/ffc57a28-69fa-11e6-858a-6985a1f21f3b.png)

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. We’ll consider implementing it in the future React-Native SDK. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
