### ISSUE TITLE
Optimize lodash size

### ISSUE THREAD

**Issue by moimael** [cloudinary/cloudinary_npm#109]
HI,

Right now cloudinary is the second biggest dependency in our project, just behind react. And it is because of lodash, who takes > 400k. 
In our project we use the babel lodash plugin to only retrieve lodash modules we use.

Have you considered updating to lodash 4 and only requiring lodash modules you need ?

Thanks !

![screenshot from 2016-09-08 10-23-40](https://cloud.githubusercontent.com/assets/1479859/18342409/03a63c8a-75af-11e6-9fb0-2a971cc982f6.png)
![screenshot from 2016-09-08 10-24-16](https://cloud.githubusercontent.com/assets/1479859/18342411/058135b4-75af-11e6-8290-260771182e1a.png)

**Comment by eitanp461** [comment]
@moimael can you add more details regarding your use case?

This module is meant for server-side Cloudinary integration.
Since you are using Webpack it seems that you are targeting client code, for which there are different modules, such as [https://github.com/cloudinary/cloudinary_js/](https://github.com/cloudinary/cloudinary_js/)

**Comment by moimael** [comment]
Thanks, I didn't knew about the core version of it. At first we didn't want to use the JQuery version with React. I made the switch and it works great. Still it could make sense to trim down the server version too, considering it shouldn't be a huge amount of work.

**Comment by MaorGariv** [comment]
Thanks for the feedback @moimael.

We've passed your suggestion to our SDK team for further review and discussion:)

**Comment by apalumbo** [comment]
Hi, any news on that? We are using it server side but we need to cut dependency sizes as we are running on lambda. I have seen that now you are using lodash 4 but still importing the full library.

**Comment by strausr** [comment]
@apalumbo though this is still being evaluated there is still no ETA

**Comment by apalumbo** [comment]
@tocker Great job! Thank you, will it be in version 1.13.3 ?

**Comment by tocker** [comment]
Actually since 1.11.0 ... :-)

**Comment by apalumbo** [comment]
@tocker Are we talking about cloudinary_npm? It seems to me that in the package.json the full version of lodash is used in dependencies
