### ISSUE TITLE
upload with err, callback

### ISSUE THREAD

**Issue by ralphtheninja** [cloudinary/cloudinary_npm#11]
It would be nice if cloudinary.uploader.upload() returned an error in the callback, e.g.

```
var upload = require('cloudinary').uploader.upload
upload('http://bit.ly/15RFz9B', function (err, result) {
  console.log(err, result)
})
```

**Comment by rshov** [comment]
Is there documentation for the v2 uploader? I don't see it mentioned anywhere, and the documentation still lists the callback as function(result) { }

**Comment by riston** [comment]
No documentation about the error handling, add this into doc or use conventional callback with error and result object.
