### ISSUE TITLE
Status Pending ,While calling async resource() function

### ISSUE THREAD

**Issue by regmish** [cloudinary/cloudinary_npm#110]
I want to get all resources that are uploaded before 45 days.

When I call the `api.resources()` method, I get `{status:pending}` and nothing at all

This is my method 

```
var d = new Date();
    var timesstam = d.getTime();
    var fourtyFiveDaysBefore = new Date(timesstam - (1 * 24 * 60 * 60 * 1000));
    var reourceUploadeBefore45Days = cloudinary.api.resource(function (result) {
      while(result.hasOwnProperty('next_cursor')){
        cloudinary.api.resource(function (res) {
          reourceUploadeBefore45Days  = _.merge(reourceUploadeBefore45Days, res)
        })
      }
    },{start_at:fourtyFiveDaysBefore,direction:"desc"})
   // code to delete reourceUploadeBefore45Days
```

Please correct me , If I have done something wrong

**Comment by shankarregmi** [comment]
+1

**Comment by taragano** [comment]
Sorry for our delay.

Please try to use something like the following example, here's a function that would iterate paged API (with next_cursor):

```
function allCursors(pagedApi) {
  var all = function (options, callback) {
    if (options && !callback) {
      callback = options;
      options = undefined;
    }
    if (options && options.hasOwnProperty("next_cursor") && options.next_cursor === undefined) {
      return callback([]);
    }
    pagedApi(options, function (error, result) {
      if (error) {
        console.error(error);
        callback([]);
      } else {
        all(Object.assign({max_results: 500}, options, {next_cursor: result.next_cursor}), function (resources) {
          callback(result.resources.concat(resources));
        });
      }
    })
  };
  return all;
};


var cloudinary = require('../cloudinary').v2;

var r;
var listAllResources = allCursors(cloudinary.api.resources);
listAllResources(function (resources) {
  console.log("got " + resources.length + " resources");
  r = resources;
});

```

`allCursors` is a function that takes an API function and generates a new function that iterates all records.

If you run the code above you'll get all resources eventually in the `r` variable.

Note that `allCursors` is not perfect(!), a smarter implementation would be to pass arbitrary parameters to the generated function using `apply()` (as long as the last two args are options and callback).
Also if you're coding it, put a stop condition that would allow you to break an endless recursion. For example at the top of `all()` put `if(global.stop) {return [];}`, and stop the recursion outside with `global.stop = true;`

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
