### ISSUE TITLE
Cloudinary ,express and passport

### ISSUE THREAD

**Issue by sudharsantk** [cloudinary/cloudinary_npm#115]
Dear team,
 I was able to upload images succsfully using  cloudinary direct upload (javascript) until recently I started using passport for authentication purpose.
  After that it started failing , any idea?

**Comment by taragano** [comment]
Can you please share some more information about this issue?
Can you share some code snippets? What kind of error responses are you getting?
Do you have a URL to a live webpage demonstrating the issue?

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
