### ISSUE TITLE
Support tint effects

### ISSUE THREAD

**Issue by rowanmanning** [cloudinary/cloudinary_npm#116]
Hi, I've looked around the source and tried a few things, but it seems that [tint effects](http://cloudinary.com/documentation/image_transformations#tint_effects) aren't supported by this library yet. Is there a plan to add it in, or am I missing something?

**Comment by TalLevAmi** [comment]
```
var cloudinary = require('./cloudinary');
cloudinary.url("sample.jpg", {cloud_name: "demo", effect: "tint:100"})
```
Result is: 'http://res.cloudinary.com/demo/image/upload/e_tint:100/sample.jpg'

**Comment by rowanmanning** [comment]
Thanks @TalLevAmi, this works :)
