### ISSUE TITLE
No transformations when using utils.download_archive_url

### ISSUE THREAD

**Issue by kswedberg** [cloudinary/cloudinary_npm#119]
When I attempt to generate a download url, the transformations array doesn't end up becoming part of that url. For example, if I do this:

```js
cloudinary.utils.download_archive_url({
  target_format: 'zip',
  target_public_id: 'hmc_1478615185359',
  tags: 'sometag',
  transformations: ['w960-transparent']
});
```

… and then I log the `cloudinary_params` string from https://github.com/cloudinary/cloudinary_npm/blob/master/lib/utils.js#L966 , I get the following object *without `transformations`*:

```js
{
  timestamp: 1478615185,
  mode: 'download',
  target_format: 'zip',
  target_public_id: 'hmc_1478615185359',
  tags: [ 'sometag' ],
  signature: '…',
  api_key: '…'
}
```

Am I missing something?

**Comment by kswedberg** [comment]
Hmmm. After digging around some more in the utils.js file, it looks like I can get this to work if I make the value of the `transformations` property something like this: `{transformation: ['w960_transparent']`. Not clear at all from the documentation.

And speaking of the documentation, this node.js example for `download_archive_url` is misleading: `cloudinary.utils.download_archive_url(options, callback);`. That callback parameter doesn't exist in the code.

**Comment by taragano** [comment]
Hi @kswedberg,

Named transformations should indeed use the `transformation` parameter, as mentioned in our [documentation](http://cloudinary.com/documentation/node_image_manipulation#named_transformations).
Regarding the callback, you're right, sorry for that. Our team will fix this issue as soon as possible.

**Comment by kswedberg** [comment]
@taragano , thanks for the reply and for fixing the `callback` param issue.

You're right that the documentation for `cloudinary.image` refers to `transformation`. But the documentation for the ["Generate Archive" methods](http://cloudinary.com/documentation/image_upload_api_reference#generate_archive) refers to `transformations` with an "s." And it doesn't explain why the options for `cloudinary.download_zip_url`, for example, would have to look like this (with `transformation` as a sub-property of `transformations`):

```js
{
  transformations: {
    transformation: []
  }
}
```

The description of the `transformations` option wrongly states that it takes an array, rather than an object: 

> This parameter is given as an array (using the SDKs) or comma-separated list (for direct API calls) of transformations, and separated with a slash for chained transformations.

And the following sentence is ambiguous at best:

> Note that when using the SDK for a dynamically-typed language, the transformation parameters can be specified directly without using the transformation parameter. 

Thanks again for your help.

**Comment by taragano** [comment]
@kswedberg, that's correct, the generate archive supports generating a ZIP file that includes multiple `transformations` (that's why the "s" is there), and it gets an array of hashes, where each hash includes the parameters of the transformations. 
Here's one other example, the following will generate 2 different transformed images for each included original image:

```
{
  transformations: [
    {
      width: 200,
      crop: "scale"
    },
    {
      width: 400,
      crop: "scale"
    }
  ]
}
```

To differentiate named transformations with dynamic ones, the `transformation` parameter is used, which tells Cloudinary that the value is a named transformation.
So it should actually look like:

```
{
  transformations: [
    {
      transformation: "my_named_transformation"
    }
  ]
}
```
Your version is just a "shortcut" of this one :)
I hope this helps.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
