### ISSUE TITLE
With Upload Mapping in place, api calls trigger an unhandled rejection if file is missing.

### ISSUE THREAD

**Issue by TheFarmer1** [cloudinary/cloudinary_npm#132]
I have an Auto Upload Mapping in place to automatically pull images from S3. 

When I call Cloudinary.api.resource with a file name that does not exist at S3, it correctly returns a 404 but also triggers an unhandledRejection event.  The rejected error looks like: {error: {http_code:404, message:"Resource not found - <file name>}}

Same thing occurs for Cloudinary.uploader.upload but again the upload does work and the call does return without error.

**Comment by roeeba** [comment]
Hi @TheFarmer1 , can you please share the code you're using, which triggers the `unhandledRejection` event, so we can better understand the issue here? thanks

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
