### ISSUE TITLE
Special characters are not useable in the public_id

### ISSUE THREAD

**Issue by dominik1996** [cloudinary/cloudinary_npm#133]
I am trying to upload an image with a readable public_id which contains the character 'ä'.
Cloudinary is returning an error, stating that an invalid signature was submitted.

Heres the code:

```
var cloudinary = require('cloudinary');

// Edit config for testing
cloudinary.config({
	cloud_name: 'sample',
	api_key: '12345',
	api_secret: 'ABCDE'
});

var options = {

	// Readable public_id with special characters ('ä')
	public_id: 'Allgäu'
};

cloudinary.uploader.upload('http://www.campetent.com/images/coleman-sundome-3-tent-1200x1200.jpg', (result) => {
	console.log(result);

	// Signature may vary
	// Logs:
	// { error:
	// { message: 'Invalid Signature 63315870d558f6de555ed924a8f737dd4180ca65. String to sign - \'public_id=Allgäu&timestamp=1485259422\'.',
	//   http_code: 401 } }
}, options);
```

I attached a sample project to this issue.
You just have to install the dependencies and change the keys and cloudname.

[TestProject.zip](https://github.com/cloudinary/cloudinary_npm/files/726608/TestProject.zip)

Cheers.

**Comment by roeeba** [comment]
Hey @dominik1996 Can you please make sure you are using the latest library version? 
If you are using the most recent one, would be great if you could share your cloud_name, so I can check our logs for your requests. If you rather not share it here, please feel free to [open a support ticket](https://support.cloudinary.com/hc/en-us/requests/new).

**Comment by dominik1996** [comment]
Thanks for the quick answer @roeeba.

Updating to latest library version did the trick.

Thanks a bunch.
