### ISSUE TITLE
samples out of date ?

### ISSUE THREAD

**Issue by leviwheatcroft** [cloudinary/cloudinary_npm#135]
This [sample](https://github.com/cloudinary/cloudinary_npm/blob/c290aa1ba4b4c56b8c16094356c9630a4ea273d2/samples/basic/basic.js#L32) uses the pattern `upload_stream(params, callback)` but in your readme it's `upload_stream(callback, params)`.

In addition, the callback does not appear to be passed an error param.

**Comment by roeeba** [comment]
Hi @leviwheatcroft thank you for this feedback. We apologise, but it looks like the README file is outdated. 
There are currently two versions running in the package, the first one (callback first) is meant mainly for backwards compatibility (to support developers which used our first versions). The 'correct' version is in the v2 namespace (require('cloudinary').v2), as can be seen in the example here:
https://github.com/cloudinary/cloudinary_npm/blob/master/samples/basic/basic.js

I've forwarded this input to our dev team to review and fix. Thanks again. 

In regards to the callback's error param - we're aware of this issue and we plan to resolve it as soon as we can. Please see - #131

**Comment by leviwheatcroft** [comment]
Fair enough.. you should definitely add a notice about this in the readme, even if you can't update all the examples in the readme in the short term. I've been playing around with this api a lot in the last few days and I had no idea about the v2 stuff. I just didn't notice the `v2` in the samples require statement.

**Comment by roeeba** [comment]
@leviwheatcroft, I fully agree with you. We'll do our best to make it as clear as possible. Thank you for your inputs.
