### ISSUE TITLE
api_call should reject promise on request error

### ISSUE THREAD

**Issue by leviwheatcroft** [cloudinary/cloudinary_npm#136]
api_call does include sophisticated error handling for res error emitter, but errors emitted by request are just passed to the callback without rejecting the deferred promise. See the request [error handler](https://github.com/cloudinary/cloudinary_npm/blob/master/src/api.coffee#L69).

A few lines up you can see the response error handler correctly rejecting the deferred promise before callback.

**Comment by roeeba** [comment]
Hi @leviwheatcroft, thank you for reporting this issue. I've forwarded this to our dev team to review and fix. We will update here once this is resolved.
