### ISSUE TITLE
Wrong negative angle in url

### ISSUE THREAD

**Issue by haraldini** [cloudinary/cloudinary_npm#137]
(using node 7.7)

This call
`cloudinary.image("sample.jpg", { angle: -20, overlay: "text:DarkText:encodedCopy" })`

should return a correct url like this
`.../image/upload/a_-20,l_text:DarkText:helloworld/v1489489711/sample.jpg`
notice: **a_-20**

however, it returns a malformed url
`/image/upload/a_min20,l_text:DarkText:helloworld/sample.jpg`
notice: **a_min20**

the minus in the rotation has be encoded incorrectly and the API call fails

**Comment by MaorGariv** [comment]
Hi @haraldini, thanks for letting us know.
We're checking the issue and will post here once we have updates to share.

**Comment by MaorGariv** [comment]
This issue was identified and fixed. The fix will be added on our next release..

Thanks again for pointing it out:)

**Comment by tocker** [comment]
Fixed in 4e939f74dc96ae52b83c7c69a1a51375c93f4396 (version 1.9.0)
