### ISSUE TITLE
callback error

### ISSUE THREAD

**Issue by shuigesuntao** [cloudinary/cloudinary_npm#139]
### return new Promise((resolve,reject) => {
        cloudinary.uploader.upload(url,{
            resource_type: 'video',
            folder: 'video'
        },function(result) {
            if(result && result.public_id){
                resolve(result)
            }else{
                reject(new Error(result))
            }
        })
    })
};

**Comment by tocker** [comment]
@shuigesuntao you probably mean to call `cloudinary.v2.uploader.upload`. Before `v2` the last argument was the options rather than the callback argument.
Also please note the `upload` returns a promise, so you don't need to create a new promise. If you intend to use the returned promise the callback argument is not required.

```
exports.uploadToCloudinary = (url) => {

return new Promise((resolve,reject) => {

    cloudinary.uploader.upload(url,{
        resource_type: 'video',
        folder: 'video'
    },function(result) {
        if(result && result.public_id){
            resolve(result)
        }else{
            reject(new Error(result))
        }
    })
})
};

**Comment by tocker** [comment]
Or even...

```
exports.uploadToCloudinary = (url) => 
    cloudinary.v2.uploader.upload(url,{resource_type: 'video',folder: 'video' });
```

Usage:

```
uploadToCloudinary('http://res.cloudinary.com/demo/video/upload/dog.mp4').then(
    (res)=> console.log("Success!", res),
    (error)=> console.log("Error...", error)
).finally(()=>console.log("Done!!!"));
```

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
