### ISSUE TITLE
Poor documentation on generating upload signature for client upload

### ISSUE THREAD

**Issue by 0xc00010ff** [cloudinary/cloudinary_npm#145]
I spent quite a while looking for conventions on how to implement signature generation for direct client signed-uploads in Node (Express), and there was only links to the raw library code and a support request that didn't offer any help... 😖  Since this is a very common operation, I thought it might be worth including in the docs, whether on the site or in the README. 

In case you find it useful... the Express code

```Javascript
/**
* Returns a calculated signature for uploading to Cloudinary via the client SDKs
*/
function signFileUploadRequest(request, response) {
  // get the api_secret (and keep it secret)
  var apiSecret = process.env.CLOUDINARY_SECRET;
  // grab a current UNIX timestamp
  var millisecondsToSeconds = 1000;
  var timestamp = Math.round(Date.now() / millisecondsToSeconds);
  // generate the signature using the current timestmap and any other desired Cloudinary params
  var signature = Cloudinary.utils.api_sign_request({ timestamp: timestamp }, apiSecret);
  // craft a signature payload to send to the client (timestamp and signature required, api_key either sent here or stored on client)
  var payload = {
    signature: signature,
    timestamp: timestamp
  };
  // send it back to the client
  response.json(payload);
}
```

or just plain node if that fits the README better..

```Javascript
var apiSecret = 'your-api-secret';
// grab a current UNIX timestamp
var millisecondsToSeconds = 1000;
var timestamp = Math.round(Date.now() / millisecondsToSeconds);
// generate the signature using the current timestmap and any other desired Cloudinary params
var signature = Cloudinary.utils.api_sign_request({ timestamp: timestamp }, apiSecret);
// craft a signature payload to send to the client (timestamp and signature required, api_key either sent here or stored on client)
var payload = {
  signature: signature,
  timestamp: timestamp
};
// return payload to client
```

**Comment by roeeba** [comment]
Hi @0xc00010ff, thank you again for sharing this (as well as in the forum). I've forwarded your code snippet to our SDK team to review. Your feedback is much appreciated!

**Comment by vishchiv** [comment]
@0xc00010ff so basically before uploading an image you call endpoint to get a signature and then you upload actual image but now with a signature, right?

**Comment by 0xc00010ff** [comment]
@vishchiv This is true for a good number of cases but in some scenarios, you don't always have the luxury of high memory or disk-space servers so it becomes necessary.

Like in a photo/video sharing app, where a lot of requests are uploads- you'd be spending a lot of resources just proxying binary files to Cloudinary. At high load, this could bog down other requests too. 

I agree that it breaks the mold of clean architecture (making the client apps know a little too much about the backend details)- I too prefer just passing the data through my servers when I can. It just happens that in my particular use case this time, I can't let the app servers get slowed down by big uploads.

**Comment by vishchiv** [comment]
@0xc00010ff  thank you for reply. I got your point.

**Comment by Taylorsuk** [comment]
Still in 2018 I've been scouring the internet in order to find this exact code example! 

Thank you!

**Comment by yakirp** [comment]
Hi @Taylorsuk , 

Please check this code:

```
var express    = require('express');
var bodyParser = require('body-parser');
var cloudinary = require('cloudinary');
var app = express();

app.use(bodyParser.urlencoded());
app.use(bodyParser.json())      ; 

var api_secret = "***";
var api_key = "***";
var cloud_name = "***";

cloudinary.config({ 
    cloud_name: cloud_name,
    api_key: api_key,
    api_secret: api_secret
  });

app.post('/', function (req, res) {
  var data = req.body;
  console.log(data);
  
  if (data.resource_type)
  delete data.resource_type;

  if (!data.timestamp)
  data.timestamp = Math.floor(new Date() / 1000);

  var signature = cloudinary.utils.api_sign_request(data, api_secret);
  res.json({ signature: signature, api_key: api_key, timestamp: data.timestamp});
});
```

Please let me know if it works for you?

--Yakir

**Comment by Taylorsuk** [comment]
@yakirp - Yeah pretty much exactly what I ended up with. 

```
      try {
        const apiSecret = process.env.CLOUDINARY_API_SECRET;
        const millisecondsToSeconds = 1000;
        const timestamp = Math.round(Date.now() / millisecondsToSeconds);
        const signature = cloudinary.utils.api_sign_request({ timestamp: timestamp, upload_preset: upload_preset }, apiSecret);
        const payload = {
          signature: signature,
          timestamp: timestamp
        };
        res.success(payload)
      } catch (error) {
        res.error({ error: error })
      }
```

**Comment by yakirp** [comment]
@Taylorsuk this is great!

Just note that my example is more general and you can use it to sign any upload request with us.

Cheers,
--Yakir

**Comment by Bengejd** [comment]
A year later, and the docs are still terrible about clearly stating how this is possible. I couldn't even find documentation on what methods are available via the server SKD's when I was trying to find out how to do this on my own...plus I'm pretty sure the manually generated key example that is listed on the docs, is incorrect. Because I used their own string example, and just encoded it using crypto on Node, and it gave me a similar, but different string than the one they said we should be expecting. 

Please fix the docs. This seems like a great service, but not if it's going to be this complicated to utilize on a technical level, because you simply can't find any of the answers that you're looking for...

**Comment by cloudinaraz** [comment]
Hi @Bengejd, thank you for your feedback. The signature generation section of our documentation went through some modifications during the last year. Have you seen the [Signature quick reference](https://cloudinary.com/documentation/signatures) page, which provides a quick check-list style summary of the various ways that signatures can be used in Cloudinary? It also has links to designated sections describing each of usages more in-depth.

Please find the updated [Generating authentication signatures](https://cloudinary.com/documentation/upload_images#generating_authentication_signatures) help topic, which includes the syntax of the **api_sign_request()** method for all server-side frameworks SDK's. You can also use this [link](https://cloudinary.com/documentation/upload_images#using_cloudinary_server_side_sdks_to_generate_authentication_signatures) to jump directly to the method's syntax section.

Thanks for bringing the sha-1 example issue to our attention. This is now fixed.
We appreciate any specific feedback on these topics, so please let us know if you think there's anything that is missing or unclear.

**Comment by austinthetaco** [comment]
I'd like to add that I also spent far too long trying to figure out how to accomplish this. The example found here for [api_sign_request](https://cloudinary.com/documentation/upload_images#verifying_signatures_in_the_json_response) has incorrect syntax for Node, as the params should be wrapped as an object. Below the code example it also concatenates the version number with the secret, yet elsewhere in the docs it says to concatenate the timestamp with the secret. 

There is little-to-no documentation on how to do signed uploads from the client-side while using Node/etc to generate the signature. The only signed direct-upload documentation that I found gave details using the Cloudinary-core and that isn't really compatible with a lot of React projects. 

It would be great to get some very clear examples of what is minimally required to do a signed upload from the frontend and the structure of the parameters for the `api_sign_request` method (as well as documentation for the other methods).

**Comment by cloudinaraz** [comment]
@austinthetaco it seems like you are looking for instructions on how to generate the signature for signed upload. However, the link that you've shared includes information about verifying a signature returned in the response for some of Cloudinary's API methods. 
Please see the following [section](https://cloudinary.com/documentation/upload_images#generating_authentication_signatures), which is more relevant to your use case.
The `params_to_sign` passed to the `api_sign_request` should indeed be wrapped as an object and must consist of `timestamp` + all the parameters in your request, except for the ones mentioned in the above link. 
You shouldn't be worried about sorting your parameters object in the correct order as the `api_sign_request` function will already take care of it.
Have you seen the example code shared in this thread by @yakirp?

**Comment by n19htz** [comment]
So I get payload with signature and timestamp on the nodejs backend, then I send response to the front with that payload. But what should I do with it on frontside? How do I use that payload for uploading an image? Could somebody give me an example?

**Comment by GaddMaster** [comment]
Does anyone know how to generate a signature for the client widget? Struggling for any help anywhere what so ever. ?

Thanks

**Comment by shirlymanor** [comment]
@GaddMaster You can follow the instructions here: https://cloudinary.com/documentation/upload_widget#signed_uploads

**Comment by GaddMaster** [comment]
@shirlymanor I have read this link 10 times and all the rest, they don't help me. they don't explain fully... There are no examples...

**Comment by aleksandar-cloudinary** [comment]
Hi @GaddMaster . I've provided a more detailed reply on the Support Forum where you had submitted a post, but let us know which specific step of the setup process is not working for you and you'd like an example for as well as your existing code. There's an example of the server-side code in NodeJS which receives the parameters and sings them if this is the part you're looking for.

**Comment by GaddMaster** [comment]
OK Great. That would be useful. I'll go check that out and once I get help figure this out. I'll share my code somewhere useful for others. I'll be back Mr Thread

**Comment by GaddMaster** [comment]
OK. So I am back after receiving help from the staff. I wanted to share my mistake with everyone in case anyone ever makes the same one as me. Which is silly I do accept. 

The upload signature (uploadSignature, upload_signature) has to be the actual function itself and not the results from you calling the function prior and getting the signature. I was retrieving the signature from my server and inserting that result as the upload signature. 

My Bad. Rock On.

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by Motoxpro** [comment]
Here is how I did it witha  Firebase Cloud Function

```
import * as functions from 'firebase-functions';
import cloudinary from 'cloudinary';
const CLOUDINARY_SECRET_KEY = functions.config().cloudinary.key;
const cloudinaryV2 = cloudinary.v2;
module.exports.main = functions.https.onCall(async (data, context: CallableContext) => {
  // Checking that the user is authenticated.
  if (!context.auth) {
    // Throwing an HttpsError so that the client gets the error details.
    throw new functions.https.HttpsError(
      'failed-precondition',
      'The function must be called while authenticated.',
    );
  }
  try {
    return cloudinaryV2.utils.api_sign_request(data.params_to_sign, CLOUDINARY_SECRET_KEY);
  } catch (error) {
    throw new functions.https.HttpsError('failed-precondition', error.message);
  }
});


// CLIENT
const uploadWidget = () => {
  const generateSignature = async (callback: Function, params_to_sign: object): Promise<void> => {
    try {
      const signature = await generateImageUploadSignatureCF({ params_to_sign });
      callback(signature.data);
    } catch (err) {
      console.log(err);
    }
  };

  cloudinary.openUploadWidget(
    {
      cloudName: 'xxxxxx',
      uploadSignature: generateSignature,
      apiKey: ENV.CLOUDINARY_PUBLIC_KEY,
    },
    function(error, result) {
      console.log(error);
    },
  );
};
```

**Comment by trevthewebdev** [comment]
It's 2020 and the documentation is still lacking. I've spent 3 days (at least 6 hours a day) on this now and FINALLY got it working thanks to @Motoxpro. I was plagued by the dreaded `invalid signature` error. The following is the bare minimum to get this thing to authenticate.

client-side (I happen to be using react)
```
// in an useEffect or componentDidMount lifecycle method
// where getSignature is a get / post request that sends some params to the server (my widgetOptions is just an empty object for now so please disregard)
getSignature({ ...widgetOptions })
      .then(({ data }) => {
        const { apiKey, signature, timestamp } = data;

        window.cloudinary.openUploadWidget({
          cloudName: 'your-cloud-name-here',
          apiKey,
          uploadSignature: signature,
          uploadSignatureTimestamp: timestamp,
        });
      })
```

server-side (nodejs)
```
// in a controller somewhere
getSignature() {
    const timestamp = Math.floor(Date.now() / 1000);
    const signature = cloudinary.v2.utils.api_sign_request(
      { source: 'uw', timestamp },
      env.MEDIA_CDN_API_SECRET,
    );

  // for me this is the response
  return {
    data: { apiKey: CDN_PUBLIC_KEY, signature, timestamp },
  };
}
```

Again... this is the bare minimum to get this stuff working and not rejecting you like that love interest you asked out but said they valued your friendship.

**Comment by eyalktCloudinary** [comment]
Hi @trevthewebdev, 
Thanks for the feedback regarding our documentation. I'm glad to hear it is now working for you! 
We continuously strive to improve our documentation, and clients' feedbacks, like yours, are very helpful.
I hope you'll never encounter the dreaded `invalid signature` error again :) If you do see this error, or have any other question/issue, be sure to let us know! either here, in GH, or through support@cloudinary.com

**Comment by austinthetaco** [comment]
@eyalktCloudinary instead of a friendly reply hoping it doesn't happen anymore: why not just fix the documentation?

**Comment by limaho** [comment]
Trying to implement using direct Rest Api without lucky. Anyone has a good example? I try with the code from @trevthewebdev and @Motoxpro. I am getting the signature, but once I sent the post with axios response with 401 error

**Comment by igy** [comment]
Hi Lima,
Can you let me know which API calls you're trying to make, how you're generating the signature, and where it's failing? If you're using our Node SDK, the signature will be added automatically when using our SDK to make the call, or you can [use the `api_sign_request ` function to generate a signature if the call will be made from client-side code or another system](https://cloudinary.com/documentation/upload_images#using_cloudinary_server_side_sdks_to_generate_authentication_signatures). 
There's an example here for signed uploads from the upload widget: https://cloudinary.com/documentation/upload_widget#signed_uploads
If you need to provide anything that shouldn't be posted publicly, you can create a support request for us at support.cloudinary.com and we can help you to debug

Thanks,
Stephen

**Comment by NiccoloCase** [comment]
I am aware that it is a fairly old thread, but I really can't understand how to manage the entire image uploading flow and it doesn't seem to me that there are no examples in the documentation. I am developing my client application with react-native and I need to upload images directly from the client. I wonder if it is possible to use a server-generated signature to secure the whole process (as in s3). From the documentation it seems possible to me, however, I have not found any example that can clarify my ideas. Also, I don't understand if there is an SDK for react-native, for now, I am dealing with simple HTTP requests. As soon as I add to my HTTP request the signature I get an error regarding the absence of the API key. However, it seems obvious to me, even from what is written in the documentation, that the key should not be included in the application. I don't know if this reasoning is right, I hope in someone's support. Thank you.

**Comment by roeeba** [comment]
Hi @NiccoloCase, Please see my response to your [forum post](https://support.cloudinary.com/hc/en-us/community/posts/360009312339-Handle-signed-upload-from-react-native). 
Let me know if you have any questions?

**Comment by NiccoloCase** [comment]
@roeeba Thank you so much for the support. I really missed the difference between api key and api secret.

**Comment by roeeba** [comment]
Glad I could help, @NiccoloCase :)
