### ISSUE TITLE
[feature request] Set/Override filename for streams

### ISSUE THREAD

**Issue by marcohamersma** [cloudinary/cloudinary_npm#150]
Hey Hey,
I'm uploading to cloudinary using `cloudinary.uploader.upload_stream`, and right now when uploading with a stream, [the filename is automatically set to 'file'](https://github.com/cloudinary/cloudinary_npm/blob/c6aa42b11f2b0b97d904f93d2c5794da8c0cdb1b/src/uploader.coffee#L279). 

Since I do know what the filename should be, I was wondering if it would be possible to make an option for this. I tried setting the public id manually, but this obviously requires there to be no conflicting filenames and I can't guarantee this in my app. 

For now, I'd propose a `filename` option that can be passed, but maybe adding an additional parameter to `upload_stream` might also work. What would be the best implementation in your opinion?

**Comment by roeeba** [comment]
Hi @marcohamersma, we apologise for the late response. Thank you for your suggestion. I'm forwarding this to our dev team to review. We'll update here if and when this will be available.

**Comment by marcohamersma** [comment]
No worries, thanks for looking in to it :)

**Comment by roeeba** [comment]
We're always glad to help :)

**Comment by eddyw** [comment]
Any change? we're having the same issue.

**Comment by shirlymanor** [comment]
@eddyw we are working on a new update with a fix in our next release.

**Comment by eddyw** [comment]
@shirlymanor is there an estimated date for the next release? It's important for us to know. Thanks in advance :)

**Comment by shirlymanor** [comment]
@eddyw we can't really tell but hopefully in the next weeks.

**Comment by strausr** [comment]
Resolved on https://github.com/cloudinary/cloudinary_npm/pull/273
