### ISSUE TITLE
Streams throwing error

### ISSUE THREAD

**Issue by RWOverdijk** [cloudinary/cloudinary_npm#153]
I'm trying to upload using a read stream, but I'm geting an error:

```
if ((file != null) && file.match(/^ftp:|^https?:|^s3:|^data:[^;]*;base64,([a-zA-Z0-9\/+\n=]+)$/)) {
                                 ^

TypeError: file.match is not a function
```

Here's how I'm trying the upload:

```js
if (typeof url === 'string') {
  return (url.indexOf('https') === 0 ? https : http).get(url, fileStream => this.uploadToCloudinary(fileStream, req, res));
}

// In uploadToCDN
cloudinary.uploader.upload(file, result => { /* ... */ });
```

**Comment by taragano** [comment]
You should be able to use `upload_stream` (https://github.com/cloudinary/cloudinary_npm/blob/master/test/uploader_spec.coffee#L189-L200) and then write the buffer, i.e., in https://github.com/cloudinary/cloudinary_npm/blob/master/test/uploader_spec.coffee#L199

**Comment by RWOverdijk** [comment]
@taragano Thanks, I'll give it a go. I've currently worked around it by first downloading the file to my server, in a tmp dir, and uploading it to cloudinary. If this works I'll post a comment and the docs should probably be updated.

**Comment by taragano** [comment]
@RWOverdijk Great, thanks for the update.
Please let us know if there's anything else we can help you with.

**Comment by RWOverdijk** [comment]
I tried reading the code just now, but it's coffeescript and I gave up really quickly. Also opted to not use this library because of that same reason and just built my own.

Thanks though.

**Comment by RWOverdijk** [comment]
If anyone else finds this issue, by the way, cloudinary doesn't function with streams and upload_stream does the same check as it just calls upload_stream.

You're probably trying to upload an image from a remote source, in which case you can just call upload like normally, and pass it the url. That works. From the source code:

```js
      if ((file != null) && file.match(/^ftp:|^https?:|^s3:|^data:[^;]*;base64,([a-zA-Z0-9\/+\n=]+)$/)) {
        return [
          params, {
            file: file
          }
        ];
      }
```

Tested and confirmed. The reason upload_stream doesn't work, is because it 's about the way it processes the upload, not the source of the upload:

```js
  exports.upload_stream = function(callback, options) {
    if (options == null) {
      options = {};
    }
    return exports.upload(null, callback, _.extend({
      stream: true
    }, options));
  };
```

Same method, different path.

Still not using this lib though :p
