### ISSUE TITLE
Upload failed: Invalid Signature, String to sign

### ISSUE THREAD

**Issue by tureey** [cloudinary/cloudinary_npm#154]
**Hi everyone,**

**I am trying to implement the cloudinary widget in our platform but I am getting a strange error.**
```
kind:"fileuploadfail"
message:"Upload failed: Invalid Signature 4e12ef374b52dfdf1335b24d33413695e1fa13c2. String to sign - 'callback=http://widget.cloudinary.com/cloudinary_cors.html&custom_coordinates=35,39,612,706&folder=temp&timestamp=1501576422'."
widget_id:0
```

**I am still using the 'demo' cloud_name btw.. these are my functions:**

```
var generateSignature = function(callback, params_to_sign){
    var data = {
        image_uid: "hola" + Date.now(),
    };

    $.ajax({
        url     : urlCreateCloudBinaryWidgetSignature,
        type    : "POST",
        data    : data,
        complete: function() {console.log("complete")},
        success : function(response, textStatus, xhr) { callback(response.signature); },
        error   : function(xhr, status, error) { console.log(xhr, status, error); }
    });
}

$('.cloudBinaryWidget_init').cloudinary_upload_widget({
        cloud_name: 'demo',
        api_key: cloudinary_key,
        upload_signature: generateSignature,
        cropping: 'server',
        folder: 'temp',
        theme: 'white',
        inline_container: '#cloudBinaryWidget_container',
        button_class: 'cloudBinaryWidget_trigger',
        stylesheet : '#cloudinary-navbar{background:#f4f4f4;box-shadow:none!important}#cloudinary-navbar .source.active{border-bottom:6px solid #2dc8d2}.button.capture_camera,.button.select_file.select_single,.button.upload_url{background:linear-gradient(60deg,#2dc8d2 0,#22e5c9 100%)!important}#cloudinary-widget .button,#cloudinary-widget .button.small_button{background:linear-gradient(60deg,#2dc8d2 0,#22e5c9 100%)}'
    },
    function(error, result) {
        console.log(error, result)
    });
```

**Am I doing something wrong? and if some day I fix this error.. I tried to change the cloud_name, but I was getting an error doing a GET petiton to a name_of_cloud.json How could I solve this?**

_Thank you to everyone!
Have a nice day,
Victor_

**Comment by taragano** [comment]
There are some parameters that should be updated there:

1. The `data` should be { data: params_to_sign}. 
2. If you'd like to set a public_id for the uploaded image, you should include it at the upload parameters as the `public_id` parameter.
3. There should be a `dataType: "text"` added to the ajax call.
4. Please make sure you use your Cloudinary account's cloud_name and api_key, and also include your api_secret when generating the signature on the server.

Can you try the following and tell me if it works for you?

```
var generateSignature = function(callback, params_to_sign){
	    $.ajax({
	      url     : urlCreateCloudBinaryWidgetSignature,
	      type    : "POST",
	      dataType: "text",
	      data    : { data: params_to_sign },
	      complete: function() {console.log("complete")},
              success : function(response, textStatus, xhr) { callback(response.signature); },
              error   : function(xhr, status, error) { console.log(xhr, status, error); }
	    });
	  }

$('.cloudBinaryWidget_init').cloudinary_upload_widget({
        cloud_name: 'mycloudname',
        api_key: cloudinary_key,
        upload_signature: generateSignature,
        cropping: 'server',
        folder: 'temp',
        public_id: "hola" + Date.now(),
        theme: 'white',
        inline_container: '#cloudBinaryWidget_container',
        button_class: 'cloudBinaryWidget_trigger',
        stylesheet : '#cloudinary-navbar{background:#f4f4f4;box-shadow:none!important}#cloudinary-navbar .source.active{border-bottom:6px solid #2dc8d2}.button.capture_camera,.button.select_file.select_single,.button.upload_url{background:linear-gradient(60deg,#2dc8d2 0,#22e5c9 100%)!important}#cloudinary-widget .button,#cloudinary-widget .button.small_button{background:linear-gradient(60deg,#2dc8d2 0,#22e5c9 100%)}'
},
function(error, result) {
	console.log(error, result)
});
```

**Comment by tureey** [comment]
@taragano First of all thank you for this quick response!

I did some fixes so, right now it uploads photos perfectly but I still 2 problems:

- I created a upload_preset so I am using the code I got by then, but it doesn't crop the images... 
- Is there any way to set an click event listener for this button_class: 'cloudBinaryWidget_trigger' that is created? Be cause I attached a click event on this class into the document because it is created dynamicaly... but I can't still capture it... Btw, I tried to trigger it in the console... but no I got no reasults...

**Comment by taragano** [comment]
I'm sorry for my response delay @tureey.

- Regarding the cropping, it depends whether you want to crop the original or upload the original as is and crop on delivery. For more information:
https://support.cloudinary.com/hc/en-us/articles/203062071-How-to-crop-images-via-the-Upload-Widget-

- Regarding the click event, can you please share some more information about your use-case and specific requirements around the button click event?

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
