### ISSUE TITLE
Tests do not work.

### ISSUE THREAD

**Issue by Philin-Anton** [cloudinary/cloudinary_npm#156]
There is no possibility to create a pull requests

**Comment by taragano** [comment]
Hi @Philin-Anton,
I see that you managed to create on after all (https://github.com/cloudinary/cloudinary_npm/pull/155)?

Please let us know if you still need any further assistance.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
