### ISSUE TITLE
Failure when trying to delete resources

### ISSUE THREAD

**Issue by gvillenave** [cloudinary/cloudinary_npm#158]
I'm getting the following error when trying to delete resources:

```
/app/node_modules/cloudinary/lib/utils.js:1156
          return callback(void 0, result);
                 ^
TypeError: callback is not a function
    at /app/node_modules/cloudinary/lib/utils.js:1156:18
    at IncomingMessage.<anonymous> (/app/node_modules/cloudinary/lib/api.js:113:51)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

The call is the following: 
```
var countLeft = unusedResources.length;
async.doWhilst(
    function (callback) {
        var start = unusedResources.length - countLeft;
        var slice = unusedResources.slice(start, start + 100);
        countLeft = countLeft - 100;
        cloudinary.v2.api.delete_resources(
            slice,
            callback,
            {
                resource_type: type,
                type: 'upload',
                keep_original: false
            });
    },
    function (result) {
        return countLeft > 0;
    },
    next);
```

Lib version: 1.9.0

Thanks,
Gabriel

**Comment by roeeba** [comment]
Hi, @gvillenave. Placing the callback function before the options is an old approach. Note that it should only receive a single result argument (result). 
Alternatively, and more recommended, is using v2 (the newest version), where the callback is pushed to be the last argument and it now receives 2 arguments (error and result). 
Also note that `type: 'upload'` and `keep_original: false` are both default options so you can safely omit these. 

You can use something like this:

`cloudinary.v2.api.delete_resources('myImageId', { resource_type: type }, function(error, result){console.log(result);});`

**Comment by gvillenave** [comment]
Thanks @roeeba, this solves my problem! Could you consider updating the documentation to make this API use clearer?

**Comment by roeeba** [comment]
Sure! I've forwarded your feedback to our documentation team to review. We'll do our best to make it clearer.
