### ISSUE TITLE
Refusing to install cloudinary as a dependency of itself 

### ISSUE THREAD

**Issue by SasanksaiMekala** [cloudinary/cloudinary_npm#163]
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" 
"C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cloudinary"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install cloudinary as a dependency of itself

**Comment by strausr** [comment]
Can you please inspect your package.json file?

If the name of our project is cloudinary please rename it and try installing the dependencies again.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
