### ISSUE TITLE
When generating a secure url using secure: true in cloudinary.url, domain is never generated

### ISSUE THREAD

**Issue by JamesJansson** [cloudinary/cloudinary_npm#166]
I believe the following lines in utils.js are to blame 

`if ((secure_distribution == null) || secure_distribution === exports.OLD_AKAMAI_SHARED_CDN) {
        secure_distribution = private_cdn ? cloud_name + "-res.cloudinary.com" : exports.SHARED_CDN;
      }`

**Comment by shirlymanor** [comment]
Hi James,

Can you share more information about the following:

- how did you initialize Cloudinary (cloudinary.config({...})

- what's the cloudinary.url call you use.

- What's the result you got?

If security is an issue you're more than welcome to [open a ticket](https://support.cloudinary.com/hc/en-us/requests/new) and we'll be happy to assist you.

**Comment by calvinl** [comment]
@shirlymanor @JamesJansson I came across this issue too in `1.9.0`. I'm not sure how it got there, but I was able to resolve the issue by removing the trailing slash from my `CLOUDINARY_URL` env variable.

This:
```
CLOUDINARY_URL=cloudinary://{API_KEY}:{API_SECRET}@{cloudName}/
```

Became:
```
CLOUDINARY_URL=cloudinary://{API_KEY}:{API_SECRET}@{cloudName}
```
