### ISSUE TITLE
add support for quality_analysis

### ISSUE THREAD

**Issue by bobmoff** [cloudinary/cloudinary_npm#171]
wouldn't it be better just pass the options parameter on without modifying it?

then every new feature that is accessed using options would automatically be supported

**Comment by roeeba** [comment]
Hi @bobmoff. Not entirely sure what you're trying to achieve? Are you asking if the 'quality_analysis' feature can be set by default? if so, this is not supported at the moment.

**Comment by bobmoff** [comment]
I couldn't get the quality analysis to work at all and I check the code and it looks like it is never accepted as option when uploading. 

I switched to using a preset which has the quality analysis option added, and that way it worked.

Am i wrong? Is it supposed to work by just sending quality_analysis: true as an option ?

I am using the streaming upload.

**Comment by roeeba** [comment]
Hi @bobmoff. I apologize for the delayed reply. It seems that the `quality_analysis` feature wasn't added to the SDK yet. We will update as soon as it does.
