### ISSUE TITLE
Using preset in upload_stream

### ISSUE THREAD

**Issue by abachuk** [cloudinary/cloudinary_npm#174]
There is no documentation on how to use presets with upload_stream. I found this in the src 
https://github.com/cloudinary/cloudinary_npm/blob/master/src/uploader.coffee#L21-L22. 

Should the `upload_stream` be able to receive preset as part of the options? 
Should this feature be better documented?
For now, I `unsigned_upload_stream` got working.

**Comment by strausr** [comment]
@abachuk Thanks for the feedback. The upload preset should indeed be set as part of the options.
For example-

```

var fs = require('fs');
var stream = cloudinary.uploader.upload_stream(function(result, error) { console.log(result, error); }, { upload_preset: '<my_upload_preset>' } );
var file_reader = fs.createReadStream('<my_pic.jpg>').pipe(stream);
```

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
