### ISSUE TITLE
Adding typings

### ISSUE THREAD

**Issue by bentedder** [cloudinary/cloudinary_npm#175]
Any chance that adding typings is possible for this package? Using typescript w/node.js and this is one of the few packages left of mine that is typeless for my builds.

**Comment by strausr** [comment]
@bentedder While it is on our roadmap to add typings functionality to our cloudinary-core there is currently no ETA. That being said, I'd be happy to update you as soon as this is available.

**Comment by kikar** [comment]
Still no ETA @strausr ?
I saw the types have been added to the cloudinary_js for client.

**Comment by strausr** [comment]
@kikar This is currently not in our near-future plans. We’ll update here on any status update.

**Comment by ForsakenHarmony** [comment]
still nothing?

**Comment by strausr** [comment]
Hi @ForsakenHahrmony still no change in status. We'll update here if and when this changes.

**Comment by idrisadetunmbi** [comment]
this is almost November 2018, still no typings?

**Comment by roeeba** [comment]
Hey guys. Thank you all for your feedback, truly appreciated!

As Cloudinary fully contemplate the need for typings, implementation requires refactoring the entire JS SDK. This naturally requires thorough planning and time to consider all theoretical implications across the system. 

I have put a note to our Product team on your behalf expressing the community’s priority for such a feature and will make sure to update upon any new insights.

We truly appreciate the opportunity to improve.

**Comment by kikar** [comment]
Thank you for considering this.
Technically you don't need to refactor the whole project in Typescript.
All is needed is create a typings file and submit it as pull request to [this repo](https://github.com/DefinitelyTyped/DefinitelyTyped).

Do you think that could be considered with higher priority since is a much easier job?

**Comment by ForsakenHarmony** [comment]
you don't have to add it to definitelytyped,

you can just add the `typings` property pointing to it

and typescript definitions also work with javascript if the ide supports it

**Comment by adamduren** [comment]
For more information see [Including declarations in your npm package](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package).

**Comment by roeeba** [comment]
Thank you all for the feedback. We highly encourage community contributions to Cloudinary's client libraries and promote them, so please feel free submit a PR. Regardless, as mentioned, we've put a note to our product team to express the urgency you guys are expressing and hopefully we'll be able to share an update soon.

**Comment by gonpombo8** [comment]
We need typings 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏

**Comment by RWOverdijk** [comment]
Who in here can share their local typings? I'll complete them and make them available since nobody has done that yet.

**Comment by 2ajoyce** [comment]
@RWOverdijk Like this? https://pastebin.com/uM0RRJGb

**Comment by RWOverdijk** [comment]
@2ajoyce That's for react I'm afraid. I made a start here, feel free to comment additions and flaws on the gist and at some point it can be contributed to DT.

https://gist.github.com/RWOverdijk/7fa20a6de230c2fd76032179acdce6a3

**Comment by 2ajoyce** [comment]
@RWOverdijk Sorry, I was looking for typings and I ended up in the wrong repo. My bad!

**Comment by mcmar** [comment]
@roeeba Given how much money we pay you every month, I don't feel like you should be asking for community support building your product. Cloudinary is not FOSS, just the client is. I'd feel more inclined to donate my time if the Cloudinary backend was FOSS

**Comment by bd82** [comment]
I'ved started playing around with creating TypeScript signatures.
See WIP here: #268

**Comment by roeeba** [comment]
Hi @mcmar, thanks for the feedback! you're right, Cloudinary is a paid service and is solely responsible for improving its products. That said, we are working on our features according to priorities (which are constantly reevaluated). Some of our users rather not wait for a specific feature and decide to help speed things up by contributing to our library, and we appreciate that.
As for adding Typings, the team is currently discussing possible ways of action, including introducing it in the next major library version (2.0). We'll update as soon as we'll have more concrete updates. 
Thank you very much for your patience!

**Comment by yakirp** [comment]
Hi, 
Unfortunately, there isn't an ETA regarding JS/Node 2.0 at the moment, we will update here:
https://cloudinary.com/product_updates

Best
Yakir

**Comment by jhalborg** [comment]
Any hopes for @bd82 's great work to be finished and merged by the team before then? It seems he really has already done most of the work.

**Comment by roeeba** [comment]
Hi, @jhalborg. The official solution is currently in the works (final stages, see https://github.com/cloudinary/cloudinary_npm/tree/feature/add-ts-decleration-file). We will update as soon as it is published. Stay tuned :)

**Comment by roeeba** [comment]
Hey everyone, typings were just added!
https://github.com/cloudinary/cloudinary_npm/commit/83b3344deed172e517e7b24a4530dd0f779e5e62

Enjoy :)

**Comment by RWOverdijk** [comment]
New phone, who dis?
