### ISSUE TITLE
cannot be installed in Windows Subsystem For Linux because of a filename

### ISSUE THREAD

**Issue by tobiasmayr** [cloudinary/cloudinary_npm#179]
I'm using WSL for web development, but I cannot get the cloudinary package installed on my Windows partition, because of the file
`node_modules/cloudinary/doc/module-utils.html#.generate_auth_token#.module:auth_token`
This filename contains a colon, which is a reserved character in Windows file paths. I have to install the project on the Windows partition, because I want to access it through a Windows editor.

Would be cool if you could rename that file :-)

**Comment by roeeba** [comment]
Hi @tobiasmayr. Note that there is no such file in the cloudinary_npm package. Could you please let us know how did you install the package?

**Comment by tobiasmayr** [comment]
@roeeba I installed it through npm, I have
    "cloudinary": "^1.9.0"
in my package.json
But you are right, the doc folder is gone in 1.9.1 ;) so I'll just upgrade. Thanks!

**Comment by roeeba** [comment]
Glad we could help :) let us know if you need anything else.
