### ISSUE TITLE
Support node style callbacks

### ISSUE THREAD

**Issue by lo1tuma** [cloudinary/cloudinary_npm#18]
The cloudinary node client has a very uncommon callback style.
In node the callback should be called with the error object as its first argument.

This pattern allows you the use transformations like `promisify`.

**Comment by skotchio** [comment]
Thanks for fixing this issue but the error object must be inherited from Error class instead Object.

**Comment by isaachinman** [comment]
Sorry, should this issue actually be closed? Here's the function signature for deletion, for example:

    cloudinary.v2.uploader.destroy('zombie', function(error, result){console.log(result)});

**Comment by shirlymanor** [comment]
@isaachinman can you please provide more information regarding this issue?
Please note, if you want to force cache invalidation you can set the invalidate to `true`. For example:

```
cloudinary.v2.uploader.destroy('zombie', 
    {invalidate: true }, function(error, result) {console.log(result)});
```
