### ISSUE TITLE
Uploading with Buffer won't keep original name

### ISSUE THREAD

**Issue by engrpeters** [cloudinary/cloudinary_npm#181]
`cloudinary.uploader.upload_stream({
            resource_type: 'auto',
            use_filename:true
        }(result) => console.log(result)).end('somebufferihave')
`
Uploading the way seem not to keep the original name even after setting it true in the options

>   instead original_filename: 'file' 

 

NB:'it's an mp3 file'

**Comment by yakirp** [comment]
Hi @engrpeters ,

In order to understand this issue better, we need some more information.
Could you please reach us at support@cloudinary.com?

Thanks

**Comment by yakirp** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
