### ISSUE TITLE
Config path

### ISSUE THREAD

**Issue by YuriFontella** [cloudinary/cloudinary_npm#182]
In the has_attached_file function settings in rails, I could define a path:

: path => ": class /: attachment /: id_partition /: filename"

So my url of the image looked like this: images/images/110/144/988/filename

Where 110/144/988 is the id of my image in database "110144988".

Is there something native in the cloudinary.url function that brings me this path?

**Comment by d-mendoza** [comment]
Hi,

I apologize for the delay.
Which of the following URLs are you trying to get: 

- http://res.cloudinary.com/images/images/110/144/988/filename
OR
- images/images/110/144/988/filename

I am looking forward to your response.

**Comment by YuriFontella** [comment]
Hi, no problem.

I upload with the settings in rails, where I configure that path ... and it generates that url with the id_partition.

Now I need to retrieve this url with nodejs ... my question is if I get this natively with the cloudinary package, or am I going to have to do some magic in javascript?

![image](https://user-images.githubusercontent.com/4920619/36624444-177ed9c2-18ee-11e8-8a11-a45d2b283473.png)

**Comment by d-mendoza** [comment]
Hi,
In rails, using **cloudinary_url a.image_file_name** returns: "http://res.cloudinary.com/wiblisten/image/upload/603465_325114464245820_2129926860_n.jpg"

But what we should be using in rails is **a.image.url** which returns the full URL:
"http://res.cloudinary.com/wiblisten/image/upload/images/images/032/454/886/603465_325114464245820_2129926860_n.jpg"

**Comment by d-mendoza** [comment]
@YuriFontella Did the above suggestion resolve your issue?

**Comment by YuriFontella** [comment]
I had to give a check on this gem and see how it works.
The cloudinary package for nodejs, only returns me the default url ... being uploaded with a different path.

https://github.com/GoGoCarl/paperclip-cloudinary

**Comment by d-mendoza** [comment]
@YuriFontella 

To better understand your issue, can you provide some more insight into the following:

1. How is your ruby gem and NodeJS interacting? Can you provide us with a flow of what you are doing?
2. Can you show us what you have now, what you are trying to do, and what you expect the end result to be? Please be as descriptive as you can.

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
