### ISSUE TITLE
using CLOUDINARY_URL

### ISSUE THREAD

**Issue by johnantoni** [cloudinary/cloudinary_npm#185]
Hi, when first loading the cloudinary package in node if I want to use the CLOUDINARY_URL environment variable and it's set in my environment do i just:

```
const cloudinary = require('cloudinary');

cloudinary.config();

```
And it'll magically pick up the config_url and work?

**Comment by eexit** [comment]
@johnantoni You don't even need to call `cloudinary.config();`.

```bash
CLOUDINARY_URL=cloudinary://874837483274837:a676b67565c6767a6767d6767f676fe1@sample node foo.js
```

**Comment by shirlymanor** [comment]
@johnantoni 
@eexit, Yes, this is one option. 
Alternatively, you can use:
`var cloudinary = require('cloudinary').v2;

cloudinary.config({ 
	cloud_name: "my-cloud-name", 
	api_key: "my-api-key", 
	api_secret: "my-api-secret" 
}); `

**Comment by johnantoni** [comment]
thanks @eexit & @shirlymanor
