### ISSUE TITLE
api_call callback doesn't supply the result as second parameter

### ISSUE THREAD

**Issue by bernharduw** [cloudinary/cloudinary_npm#186]
When a call to the Admin API was successful, the callback function is not called in an error-first style as stated in the documentation, but is directly given the result as the first parameter (see [this line](https://github.com/cloudinary/cloudinary_npm/blob/439586eac73cee7f2803cf19f885e98f237183b3/src/api.coffee#L65)).

The promise variant of the API works correctly, but I missed it in the documentation (is it documented anywhere?), as all the examples use `function (err, result) {console.log(result}}` which doesn't work.

**Comment by strausr** [comment]
@bernharduw Can you please provide us with the method you called the API?

**Comment by bernharduw** [comment]
Sure, sorry:
```js
cloudinary.api.resources_by_ids(["user_photo_1", "user_photo_2"],
  function(error, result){console.log(result);});
```

**Comment by bernharduw** [comment]
The [line linked](https://github.com/cloudinary/cloudinary_npm/blob/439586eac73cee7f2803cf19f885e98f237183b3/src/api.coffee#L65) should actually be 
```js
callback?(undefined, result)
```
This is a breaking change IMO even if it conforms to the published documentation. It would break existing code that expected the result AND the error as the first parameter, so a major version increase would be necessary unfortunately.

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
