### ISSUE TITLE
file.match is not a function

### ISSUE THREAD

**Issue by rick-rheo** [cloudinary/cloudinary_npm#187]
Seeing this now in our error logs.  :(

`TypeERROR: file.match is not a function
    at /opt/ImageService+r_0.0.41/server/node_modules/cloudinary/lib/uploader.js:70:34
    at call_api (/opt/ImageService+r_0.0.41/server/node_modules/cloudinary/lib/uploader.js:456:22)
    at Object.exports.upload (/opt/ImageService+r_0.0.41/server/node_modules/cloudinary/lib/uploader.js:67:12)
`

**Comment by d-mendoza** [comment]
Hi @rick-rheo,
Can you send us the parameters that you are passing to the upload function?
I am looking forward to your response.

**Comment by rick-rheo** [comment]
Sorry, I realized that all of a sudden we stoped sending anything for the file parameter.  Still though, that shouldn't cause a crash.
