### ISSUE TITLE
format to set proxy

### ISSUE THREAD

**Issue by accio112** [cloudinary/cloudinary_npm#188]
i have to use cloudinary services behind a proxy.. what shall be the steps required?
` DEBUG app - uploadImageToCloud res { error:
   { Error: getaddrinfo ENOTFOUND api.cloudinary.com api.cloudinary.com:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'api.cloudinary.com',
     host: 'api.cloudinary.com',
     port: 443 } }`

**Comment by roeeba** [comment]
Hi @accio112. I apologize, but not sure I entirely understand what you're trying to achieve. Could you please elaborate? could you also share the code responsible for the error you've shared?

**Comment by accio112** [comment]
I am behind my college's proxy server and i want to use cloudinary services.. are there any changes or addition to be done in the below section of my config file.
"cloudinaryConfig": {
    "cloud_name": "****,
    "api_key": "****",
    "api_secret": "**********"

  }

**Comment by roeeba** [comment]
When working with Cloudinary's RESTful API (Upload-API / Admin-API) or any other communication with the endpoint of api.cloudinary.com, requests are being transmitted to and processed using scalable cloud endpoints with varying IPs. While no changes should be done on the configuration side, you should set up a proxy in your DMZ (demilitarized zone) that will access api.cloudinary.com.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by nhim175** [comment]
I have the same problem. Is it sending too many API requests will likely cause the issue? I haven't investigated further. Trying to throttle API calls a little bit now.

**Comment by shirlymanor** [comment]
@nhim175 Can you please open a support ticket with your cloud name and the code that you are using for us to investigate in this issue?

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
