### ISSUE TITLE
how to config cloud_name, api_key and api_secret

### ISSUE THREAD

**Issue by nguyenvanphuc2203** [cloudinary/cloudinary_npm#195]

**Comment by yakirp** [comment]
Hi @nguyenvanphuc2203 ,

Here's an example of setting configuration parameters globally in your Node application:

```
cloudinary.config({ 
  cloud_name: 'sample', 
  api_key: '874837483274837', 
  api_secret: 'a676b67565c6767a6767d6767f676fe1' 
});
```

Please let me know if it helps you.
Yakir

**Comment by nguyenvanphuc2203** [comment]
thank you very much, it work for me :D

**Comment by yakirp** [comment]
Great, thanks for the update.

**Comment by nguyenvanphuc2203** [comment]
it not work for react-native ?

**Comment by strausr** [comment]
The React/Node SDK currently doesn't support React native as well. 
You might want to consider using our JS library for this matter- https://github.com/cloudinary/pkg-cloudinary-core.

Additionally, you can directly use our API for uploads. Please see this fiddle for a code example of such upload process (simply add your cloud_name and fill an upload preset) - 
http://jsfiddle.net/fw9pty0v/
