### ISSUE TITLE
Url function doesn't respect cname config

### ISSUE THREAD

**Issue by curiousercreative** [cloudinary/cloudinary_npm#197]
The following will result in `url` being generated with the `res-4.cloudinary.com` domain name rather than `some.domain.com`. My account is a Pro plan with cname, base delivery url and secure delivery url all set properly.
```
import cloudinary from 'cloudinary-core';

var cloud = new cloudinary.Cloudinary({
  cloud_name: AJM.cloudinary.cloud_name,
  cname: 'some.domain.com',
});

var url = cloud.url('some_cloudinary_asset.jpg');
```

NPM package `cloudinary-core@2.5.0`
OS: macOS 10.13.5
Bundler NPM package `webpack@4.12.0`
Browser: Chrome 67

**Comment by aditimadan-Cloudinary** [comment]
Hi,

Can you please open a support ticket here-https://support.cloudinary.com/hc/en-us/requests/new with your cloud name and CNAME and we can look into this.

Thanks,
