### ISSUE TITLE
Config with Meteor/React

### ISSUE THREAD

**Issue by dvlprmartins** [cloudinary/cloudinary_npm#202]
I'm trying to set up cloudinary config when the server is loaded by calling
```
cloudinary.v2.config({
  cloud_name: '...',
  api_key: '...',
  api_secret: '...',
})
```
But it seems like the values don't reach the client.
I also tried to set up a `process.env.CLOUDINARY_URL=` in the server but without success.

The only way that I got it working is by calling the `cloudinary.config` in the client side, but this gives access to the api_secret.

Is there any way to only call the cloudinary config method once on the server side when the app starts?

**Comment by aditimadan-Cloudinary** [comment]
Hi,

Please make sure you have cloudinary in your package.json. 

```
cloudinary = require('cloudinary');
cloudinary.v2.config({
  cloud_name: '...',
  api_key: '..',
  api_secret: '...'
});
```
Can you open a support ticket here:https://support.cloudinary.com/hc/en-us/requests/new and share your whole project/code and we can take a deeper look.

Thanks,

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
