### ISSUE TITLE
Upload error: Must supply api_key

### ISSUE THREAD

**Issue by nosleepfilipe** [cloudinary/cloudinary_npm#204]
Hi there, i have just migrated my old Meteor project to use the new npm cloudinary package, and i have some problems with the image upload.

In my server side, i have this config
```coffee
import URL        from 'url'
import Cloudinary from 'cloudinary'

cloudinary_url = URL.parse process.env.CLOUDINARY_URL

Cloudinary.config
  cloud_name : cloudinary_url.host
  api_key    : cloudinary_url.auth.split(':')[0]
  api_secret : cloudinary_url.auth.split(':')[1]
```

on my client side, i have this config

```coffee
import Cloudinary from 'cloudinary'
ENV = require './env'

Cloudinary.config
  cloud_name : ENV.cloudinary.cloud_name
```

and in the form action, i have this code
```coffee
Cloudinary.uploader.upload avatar, ( error ,response ) ->

    if error
        console.log  'Error uploading file to cloudinary'
        console.error error
```

every time that i try to upload a new image i get this error on the console
```bash
modules.js?hash=d32eb138f75899b9856278fa2e7c80359865121f:168418 Uncaught Must supply api_key
```

Is anything wrong here?
The old image that was there is working fine it shows for all my users without a problem.

**Comment by aditimadan-Cloudinary** [comment]
Can you please open a support ticket here: https://support.cloudinary.com/hc/en-us/requests/new and share the file you are trying to upload and the one that works.

**Comment by Mikkelet** [comment]
I'm having this issue as well. I put the CLOUDINARY_URL=... into my .env file and it still doesnt work.

**Comment by Mikkelet** [comment]
I think I figured it out! I was using the v2 library, and apparently wasn't really registering. Switching to v1 fixed most of my problems. I am using google cloud functions btw if that matters

**Comment by igy** [comment]
Hi Mikkelet, thanks for the update - The main difference between v1 and v2 of the library is the parameter order; in v2 the last parameter is the callback function, but in v1 the callback is often the first or second parameter. This shouldn't really affect the setup of the SDK, but maybe your upload calls were passing options in a way which interfered with API key propagating through the SDK to the API call which was made?

**Comment by Mikkelet** [comment]
Ahh wait acutally, sorry, it's not working. I switched to using upload_unsigned.. which I guess isnt recommended for production. if I use "cloudinary.uploader.upload" I get must_supply_api_key.

I'll submit a ticket.

**Comment by shirlymanor** [comment]
@Mikkelet I've answered in a ticket but wanted to add that upload unsigned with upload preset is secured because you are not exposing the API secret.

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by zachsj** [comment]
I wish the answer was posted here, I'm having the same problem.  I set up the connection between heroku and cloudinary with the config var etc.  Still getting Error: Must supply api_key.  Everything works fine on development side, it's just on production side after deploy that I'm having this issue.

**Comment by aksjoshi1** [comment]
We have a few guides that should help you get this set up that I will link below:

Documentation page: https://cloudinary.com/documentation/node_quickstart

Video guide here: https://training.cloudinary.com/learn/course/introduction-for-api-users-developers/lessons/environment-setup-0415?page=1

PS: Make sure that the folder structure and access to the files are available.

**Comment by zachsj** [comment]
So it's saying do this.
```
// Return "https" URLs by setting secure: true
cloudinary.config({
  secure: true
});
```

Just secure: true? Don't have to put the cloud name, key and secret in there as usual?

There's no files to access, it scrapes the data which is converted to a readable stream and straight to Cloudinary.

**Comment by zachsj** [comment]
Ya that's what I figured, that's how I have it.  I don't understand why my api key is undefined on production side but works on development side

**Comment by cloudy408** [comment]
Are there any differences between what is running in your development and production environments?
If the setup is the same it should work in both environments or not worth in both environments.
