### ISSUE TITLE
Webhook Signature always invalid

### ISSUE THREAD

**Issue by matteo-harpoon** [cloudinary/cloudinary_npm#205]
I'm using `loopback` (powered by `express`) with `body-parser`

```
var cloudinary = require('cloudinary');

var cloudinaryConfig = app.get('cloudinary');

var clientConfig = {};
clientConfig['cloud_name'] = cloudinaryConfig.cloudName; // valid
clientConfig['api_key'] = cloudinaryConfig.apiKey; // valid
clientConfig['api_secret'] = cloudinaryConfig.apiSecret; // valid

cloudinary.config(clientConfig);

var xTs = req.get('X-Cld-Timestamp'); // valid
var xSig = req.get('X-Cld-Signature'); // valid
var data = req.body; // valid object

var sig = cloudinary.utils.webhook_signature(JSON.stringify(data), xTs);

if (sig != xSig) {
  // always goes here
}
```

I also tried to change the way data is passed:
- `cloudinary.utils.webhook_signature(data, xTs);`
- `cloudinary.utils.webhook_signature(JSON.stringify(data, null, 2), xTs);`
- `cloudinary.utils.webhook_signature(JSON.stringify(data, null, '\t'), xTs);`
- `cloudinary.utils.webhook_signature(JSON.stringify(data).replace(/\ /g, ''), xTs);

But none of them returns a correct signature.

What am I missing?

**Comment by aditimadan-Cloudinary** [comment]
Here is an example of generating a signature using webhook_signature: https://github.com/cloudinary/cloudinary_npm/blob/bf7103aac2714002305566d05a53ded4cdcafbca/test/utils_spec.coffee#L522 The data should be the public_id, version, transformation etc. Please open a support ticket here: https://support.cloudinary.com/hc/en-us/requests/new with the public_id, cloud name and any other params you are trying to use for generating signature and we will be able to better debug the issue.

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by Motoxpro** [comment]
For future reference.
I'm not exactly sure, but I think it's wrong because the timestamp is a string. It needs to be an int

```
const validateCloudinaryHeader = async (req, res, next) => {
  const data = req.body;
  const headerTimestamp = req.get('X-Cld-Timestamp');
  const headerSignature = req.get('X-Cld-Signature');

  // Generate signature to match against
  cloudinaryV2.config({ api_key: 'key', api_secret: CLOUDINARY_SECRET_KEY });
  const signature = cloudinaryV2.utils.webhook_signature(
    JSON.stringify(data),
    parseInt(headerTimestamp, 10),
  );

  // Make sure we can't keep re-using a certain signature
  const currentTime = Math.round(new Date().getTime() / 1000);
  const isWithinOneHour = currentTime < parseInt(headerTimestamp, 10) + 60 * 60;
  if (headerSignature === signature && isWithinOneHour) {
    console.log('valid');
    next();
    return;
  }
  console.error('Error while authenticating');
  res.status(403).send('Unauthorized');
};
```
