### ISSUE TITLE
Video upload returns error: 401 - Authorization required.

### ISSUE THREAD

**Issue by Bengejd** [cloudinary/cloudinary_npm#206]
I have been scratching my head for the past couple days now, trying to figure out how to upload a video from my ionic application. I have successfully uploaded images just fine, but when I go to upload videos though, it returns an error stating that `Authorization required`.

I am using the same code for the image upload, the only difference is that it's pointing at the `'https://api.cloudinary.com/v1_1/<MyStuf>/video/upload/'` URL instead of the `'https://api.cloudinary.com/v1_1/<MyStuff>/image/upload/'`.

I am generating the signature on the server, as recommended by the docs, which works for the image upload, but not the video upload. My image is base64 encoded, and my video is base64 encoded as well, but for some reason, it's not working like it should. 

Here is my signature generation code, that I get from the server:

```
const authUid = context.auth.uid;
  const sentUid = data.uid;
  const public_id = data.params_to_sign.public_id;
  const apiSecret = 'MY_API_SECRET';
  const upload_preset = data.params_to_sign.upload_preset;
  const millisecondsToSeconds = 1000;
  const timestamp = Math.round(Date.now() / millisecondsToSeconds);

  if(authUid !== sentUid) {
    return null;
  }
  else {
    console.log('User: ', sentUid, 'is requesting a Cloudinary signature');

    const params = upload_preset ?
      {
      public_id: public_id,
      timestamp: timestamp,
      upload_preset: upload_preset,
    } : {
      public_id: public_id,
      timestamp: timestamp,
    };

    const signature = cloudinary.utils.api_sign_request(params, apiSecret);

    const payload = {
      signature: signature,
      timestamp: timestamp,
    };

    return {
      signature: payload,
    }
  }
```

**Comment by yakirp** [comment]
Hi, Could you please share with me your cloud name?

Thanks
--Yakir

**Comment by Bengejd** [comment]
@yakirp what would be the best way to share that, here or through a support ticket?

**Comment by yakirp** [comment]
@Bengejd it's totally ok to share it here, or you can open a support ticket if you prefer.

**Comment by Bengejd** [comment]
My cloud name is de4xiblq1 @yakirp

**Comment by yakirp** [comment]
@Bengejd 
I saw errors like this:
`Invalid Signature 7903e279376a4f48375514ee20ba93867aff6628. String to sign - 'timestamp=1536801792'.`

And by looking your code, I see that you are also signing the public_id, which is ok, but could you please make sure you also include the public_id in your video upload request?

**Comment by Bengejd** [comment]
I am including my public_id in the video upload request. After making some changes to my code, I am now receiving the following error, when attempting to upload videos: 

```
[Error] Origin http://localhost:8080 is not allowed by Access-Control-Allow-Origin.
[Error] Failed to load resource: Origin http://localhost:8080 is not allowed by Access-Control-Allow-Origin. (upload, line 0)
[Error] XMLHttpRequest cannot load https://api.cloudinary.com/v1_1/de4xiblq1/video/upload/ due to access control checks.
```

This is my network response that I get when uploading a video, which is unsuccessful: 

```
Summary
URL: https://api.cloudinary.com/v1_1/de4xiblq1/video/upload/
Status: —
Source: —

Request
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarytU1utufqom7QQIdj
Origin: http://localhost:8080
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15G77
Referer: http://localhost:8080/
X-Requested-With: XMLHttpRequest

Response
No response headers

Request Data
MIME Type: multipart/form-data
Boundary: ----WebKitFormBoundarytU1utufqom7QQIdj
Request Data: 

```

This is the response that I receive when I am uploading an image, which is successful:

```
Summary
URL: https://api.cloudinary.com/v1_1/de4xiblq1/image/upload/
Status: 200 OK
Source: Network
Address: 34.199.173.149:443

Request
POST /v1_1/de4xiblq1/image/upload/ HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary2rA8aX3srzq3CruI
Origin: http://localhost:8080
Host: api.cloudinary.com
Accept: application/json, text/plain, */*
Connection: keep-alive
Content-Length: 3141646
Accept-Encoding: br, gzip, deflate
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15G77
Referer: http://localhost:8080/
Accept-Language: en-us
X-Requested-With: XMLHttpRequest

Response
HTTP/1.1 200 OK
Access-Control-Max-Age: 1728000
Content-Type: application/json; charset=utf-8
Date: Fri, 14 Sep 2018 02:23:54 GMT
Cache-Control: max-age=0, private, must-revalidate
X-XSS-Protection: 1; mode=block
Access-Control-Allow-Methods: POST, GET, OPTIONS
Server: cloudinary
Access-Control-Allow-Origin: http://localhost:8080
ETag: W/"e39a8d40260d2c5f85f7828aebba0564"
Connection: keep-alive
Content-Encoding: gzip
Transfer-Encoding: Identity
Status: 200 OK
X-Request-Id: d8e2c4f1ebfac97e
X-UA-Compatible: IE=Edge,chrome=1

Request Data
MIME Type: multipart/form-data
Boundary: ----WebKitFormBoundary2rA8aX3srzq3CruI
Request Data: 
```

I'm not sure if this is a step forward or a step backwards, but It's something different than what I was getting before.

**Comment by yakirp** [comment]
@Bengejd I do see some video uploads that failed with "Unsupported source URL"
The issue is that we currently do not support `\r`. 
Could you please try to remove carriage return characters?

**Comment by yakirp** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
