### ISSUE TITLE
[question] Regarding Cloudinary Fetch API

### ISSUE THREAD

**Issue by rtm619** [cloudinary/cloudinary_npm#212]
Hi team!

Is it possible for the Cloudinary Fetch API to store images in a folder instead of the root directory of a space?
Or is it only possible with upload API?

I have a space which will store images of multiple websites and I was wondering if its at all possible to use Fetch API for storing images of each website in its specific folder.

**Comment by marissa-masangcay** [comment]
Hi @rtm619,

Fetched images cannot be placed in folders so they will have to be placed in the root directory. However, you can auto-upload your images into folders. Please just note auto-uploading images detaches them from the origin unlike fetching images. If you're interested in learning more about auto-uploading images you can read more about it in our documentation here: https://cloudinary.com/documentation/fetch_remote_images#auto_upload_remote_resources

Hope this helps!
