### ISSUE TITLE
delete image

### ISSUE THREAD

**Issue by milad145** [cloudinary/cloudinary_npm#213]
hello,

I have this image
`https://res.cloudinary.com/my-cloud-name/image/upload/v1540279844/16_www.Bia2Club.com.jpg`
and i want to delete it by api
i pass the `16_www.Bia2Club.com.jpg` as `public_ids` but results is :

> { deleted: { '16_www.Bia2Club.com.jpg': 'not_found' },
  partial: false,
  rate_limit_allowed: 500,
  rate_limit_reset_at: 2018-10-24T08:00:00.000Z,
  rate_limit_remaining: 492 }

**Comment by thedrew5150** [comment]
".jpg" is not part of the Cloudinary public ID. Try eliminating ".jpg" from your api request and run it again.

For example: public id in your api request should be 16_www.Bia2Club.com

**Comment by roeeba** [comment]
Hi @milad145. Indeed, as @thedrew5150 mentioned, the public ID should not include the extension.

**Comment by milad145** [comment]
@thedrew thanks
