### ISSUE TITLE
Unknown API key <key>

### ISSUE THREAD

**Issue by DmitryGG** [cloudinary/cloudinary_npm#214]
I'm use upload_stream. This works in local machine, but doesn't work under HTTPS, throwing error:
`Unknown API key <key>`

I found following https://support.cloudinary.com/hc/en-us/community/posts/115000574332-Unknown-API-key-when-trying-to-use-the-HTTP-API-directly
But I do not use API endpoint directly.

How to solve this?

```
cloudinary.config({
      cloud_name: cloudinaryCloudName,
      api_key: cloudinaryAPIKey,
      api_secret: cloudinaryAPISecret,
    });

return new Promise((resolve, reject) => {
const cloudinaryStream = cloudinary.v2.uploader.upload_stream((error, result) => {
        if (error) {
         reject(error);
          return;
        }
        resolve(result);
      });
});

fileStream.pipe(cloudinaryStream);
```

**Comment by TalLevAmi** [comment]
Most likely the api key is not live on that account. Can you please open a support ticket by sending an email to support@cloudinary.com and include and cloud_name and api_key? We'll be able to help you with further debugging this issue.

**Comment by DmitryGG** [comment]
I mixed API keys, solved, thanks!

**Comment by olawalejuwonm** [comment]
how did you solve this please? @dmitryrn

**Comment by Vdeub-cloudinary** [comment]
Hi @olawalejuwonm , it seems dmitryrn mixed up API keys from different accounts. If it is still not working for you, can you please open a support ticket by sending an email to support@cloudinary.com and include and cloud_name and api_key? We'll be able to help you with further debugging this issue.
