### ISSUE TITLE
Question: Chaining transformations onto a url

### ISSUE THREAD

**Issue by sseppola** [cloudinary/cloudinary_npm#220]
I have a client that uploads an image to Cloudinary and then uses the response to crop and position the image with a transformation. The resulting image url is then sent to the backend.

In the backend, when the user profile is requested, I want to create two versions of these images:
1) the uploaded image with a max size limit (eg. `w_1024,c_fit`)
2) a thumbnail image (eg. `w_200,g_center,c_thumb`)

Because I store the public_id and transformations in the url itself it becomes tricky to chain transforms onto an existing url, and as far as I can tell I'll have to parse and manipulate the url myself if I want to achieve this. Is there anything in the libs I've missed that would allow me to do something like this:
```cloudinary.chainTransformations(secure_url, ['w_200,g_center,c_thumb'])```

Edit: I could send the client specified transforms to the api and then use that to pre-generate the 2 urls I want, however where I would like to take this is to allow the client to specify the size it needs in a graphql query.

**Comment by aditimadan-Cloudinary** [comment]
If you are using incoming transformation then you can extract the public_id from the URL and then add the transformation you like to it. Upload response for incoming transformation: https://cloudinary.com/documentation/upload_images#incoming_transformations

If you are using eager transformation, then you will get the transformation list in the response. You can create/chain the transformations on the transformations already returned in the response.
Upload response for eager transformation: https://cloudinary.com/documentation/image_upload_api_reference#upload_method

In both the cases the transformations, public_id and a lot of other things are returned separately, so you don't have to do string manipulation on the URL, you can directly get it from the upload response.

**Comment by sseppola** [comment]
Not quite suitable for my use case, I do the following
1. Upload the original image to Cloudinary, and reduce the file size with a incoming transform.
2. In a separate step/session the image can be repositioned and cropped (via Cloudinary transforms). Here the generated images are just derivations of the original image, and these derived urls are what I keep for later use.

In short:
I'm not uploading the image again, so I cannot use incoming nor eager transformations.

Is this a use-case Cloudinary supports?

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
