### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by ipa1981** [cloudinary/cloudinary_npm#221]
It looks that after #217 is fixed it fails in some other setup. Meteor/Vue in my case
```
process.versions.node.split('.')[0]
```
I get "Cannot read property 'split' of undefined" error

**Comment by shirlymanor** [comment]
In order to investigate in this issue, can you please let us know what the version?

```
console.log(JSON.stringify(process.versions));
```
In the midtime, you can use one of the following workarounds:

```
const cloudinary = require('cloudinary/lib/cloudinary'); # for ES6 syntax
const cloudinary = require('cloudinary/lib-es5/cloudinary'); # for ES5 syntax
```

**Comment by ipa1981** [comment]
@shirlymanor 

```
console.log(JSON.stringify(process.versions));
```
returns:
```
{}
```
I run it on client side. 

The change you proposed helps:
```
// cloudinary = require('cloudinary')
cloudinary = require('cloudinary/lib/cloudinary');
```

But should it be this way?

**Comment by shirlymanor** [comment]
If you are using client side JS, you might want to use `cloudinary-core` instead of `cloudinary`.
You can use both if you needs cloudinary in both client and server sides.

**Comment by ipa1981** [comment]
Thanks, it this fully compatible or some migration is needed?

**Comment by shirlymanor** [comment]
It's fully compatible. Let us know if that works.

**Comment by ipa1981** [comment]
Thanks, it works. But not 100% compatible.

instead:

```
cloudinary = require('cloudinary-core')
```

I had to add:
```
cloudinary = require('cloudinary-core').Cloudinary.new()
```
