### ISSUE TITLE
Dependancy issue 

### ISSUE THREAD

**Issue by kkbear1985** [cloudinary/cloudinary_npm#224]
while compiling
[ng] Module not found: Error: Can't resolve 'crypto' in '\node_modules\cloudinary\lib'
[ng] ERROR in ./node_modules/cloudinary/lib-es5/auth_token.js
[ng] Module not found: Error: Can't resolve 'crypto' in '\node_modules\cloudinary\lib-es5'
[ng] ERROR in ./node_modules/cloudinary/lib-es5/utils/index.js
[ng] Module not found: Error: Can't resolve 'crypto' in '\node_modules\cloudinary\lib-es5\utils'
[ng] ERROR in ./node_modules/cloudinary/lib/utils/index.js
[ng] Module not found: Error: Can't resolve 'crypto' in '\node_modules\cloudinary\lib\utils'
[ng] ERROR in ./node_modules/cloudinary/lib/uploader.js
[ng] Module not found: Error: Can't resolve 'fs' in '\node_modules\cloudinary\lib'
[ng] ERROR in ./node_modules/cloudinary/lib-es5/uploader.js
[ng] Module not found: Error: Can't resolve 'fs' in '\node_modules\cloudinary\lib-es5'
[ng] ERROR in ./node_modules/cloudinary/lib/uploader.js
[ng] Module not found: Error: Can't resolve 'http' in '\node_modules\cloudinary\lib'
[ng] ERROR in ./node_modules/cloudinary/lib/api.js
[ng] Module not found: Error: Can't resolve 'http' in '\node_modules\cloudinary\lib'
[ng] ERROR in ./node_modules/cloudinary/lib-es5/uploader.js
[ng] Module not found: Error: Can't resolve 'http' in '\node_modules\cloudinary\lib-es5'
[ng] ERROR in ./node_modules/cloudinary/lib-es5/api.js
[ng] Module not found: Error: Can't resolve 'http' in '\node_modules\cloudinary\lib-es5'
[ng] ERROR in ./node_modules/cloudinary/lib/api.js
[ng] Module not found: Error: Can't resolve 'https' in '\node_modules\cloudinary\lib'
[ng] ERROR in ./node_modules/cloudinary/lib/uploader.js
[ng] Module not found: Error: Can't resolve 'https' in '\node_modules\cloudinary\lib'
[ng] ERROR in ./node_modules/cloudinary/lib-es5/uploader.js
[ng] Module not found: Error: Can't resolve 'https' in '\node_modules\cloudinary\lib-es5'
[ng] ERROR in ./node_modules/cloudinary/lib-es5/api.js
[ng] Module not found: Error: Can't resolve 'https' in '\node_modules\cloudinary\lib-es5'
[ng] ERROR in ./node_modules/cloudinary/lib/uploader.js
[ng] Module not found: Error: Can't resolve 'path' in '\node_modules\cloudinary\lib'
[ng] ERROR in ./node_modules/cloudinary/lib-es5/uploader.js
[ng] Module not found: Error: Can't resolve 'path' in '\node_modules\cloudinary\lib-es5'
[ng] ERROR in ./node_modules/cloudinary/lib/upload_stream.js
[ng] Module not found: Error: Can't resolve 'stream' in '\node_modules\cloudinary\lib'
[ng] ERROR in ./node_modules/cloudinary/lib/uploader.js
[ng] Module not found: Error: Can't resolve 'stream' in '\node_modules\cloudinary\lib'
[ng] ERROR in ./node_modules/cloudinary/lib-es5/upload_stream.js
[ng] Module not found: Error: Can't resolve 'stream' in '\node_modules\cloudinary\lib-es5'
[ng] ERROR in ./node_modules/cloudinary/lib-es5/uploader.js
[ng] Module not found: Error: Can't resolve 'stream' in '\node_modules\cloudinary\lib-es5'
[ng] i ｢wdm｣: Failed to compile.

**Comment by shirlymanor** [comment]
Can you please try to update `lodash` to the latest version as explain [here](https://github.com/cloudinary/cloudinary_npm/issues/183)?

**Comment by shirlymanor** [comment]
Can you please try adding cloudinary-core or @cloudinary/angular-5.x and let us know if that helps?
If that doesn't help can you try `npm install stream --save`

**Comment by shirlymanor** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
