### ISSUE TITLE
What is wrong in this DeleteImage function?

### ISSUE THREAD

**Issue by crazycodewriter** [cloudinary/cloudinary_npm#226]
Besides uploading images which works perfectly we try to create a delete image controller function in Node.js Express, we also use Mongoose.
Here is the controller:

```
cloudinary.config({
  cloud_name: 'name',
  api_key: 'key',
  api_secret: 'secret'
});

module.exports = {
  UploadImage(req, res) {
    cloudinary.uploader.upload(req.body.image, async result => {
      await User.update(
        {
          _id: req.user._id
        },
        {
          $push: {
            images: {
              imgId: result.public_id,
              imgVersion: result.version
            }
          }
        }
      )
        .then(() =>
          res
            .status(HttpStatus.OK)
            .json({ message: 'Image uploaded successfully' })
        )
        .catch(err =>
          res
            .status(HttpStatus.INTERNAL_SERVER_ERROR)
            .json({ message: 'Error uploading image' })
        );
    });
  },

  DeleteImage(req, res) {
    cloudinary.uploader.destroy(req.params.image, async result => {
      await User.update(
        {
          _id: req.user._id
        },
        {
          $pull: {
            images: {
              imgId: result.public_id,
              imgVersion: result.version
            }
          }
        }
      )
        .then(() =>
          res
            .status(HttpStatus.OK)
            .json({ message: 'Image deleted successfully' })
        )
        .catch(err =>
          res
            .status(HttpStatus.INTERNAL_SERVER_ERROR)
            .json({ message: 'Error deleting image' })
        );
    });
  },
  async SetDefaultImage(req, res) {
    const { imgId, imgVersion } = req.params;

    await User.update(
      {
        _id: req.user._id
      },
      {
        picId: imgId,
        picVersion: imgVersion
      }
    )
      .then(() =>
        res.status(HttpStatus.OK).json({ message: 'Default image set' })
      )
      .catch(err =>
        res
          .status(HttpStatus.INTERNAL_SERVER_ERROR)
          .json({ message: 'Error occured' })
      );
  }
};
```

**Routes**

```
router.get(
  '/set-default-image/:imgId/:imgVersion',
  AuthHelper.VerifyToken,
  ImageCtrl.SetDefaultImage
);
router.post('/upload-image', AuthHelper.VerifyToken, ImageCtrl.UploadImage);
router.post(
  '/delete-image/:imgId/:imgVersion',
  AuthHelper.VerifyToken,
  ImageCtrl.DeleteImage
);
```

What is wrong in DeleteImage function? Also  I am not sure if there should be **req.params.image** or **req.body.image**. In the front-end we will have a button for each image from the array for removing that one.

**Comment by brian-cloudinary** [comment]
Hi @crazycodewriter, 

In the code sample you shared, you use `req.body.image` in your `UploadImage` function and `req.params.image` in the `DeleteImage` function. 

Are you passing the `image` value in the URL or the in the body of your request? Could you add `console.log(req)` at the beginning of your `DeleteImage` function and share the output when it is called?

**Comment by crazycodewriter** [comment]
@brian-cloudinary I can check output when will complete it in the front as well. But I've included set default function in the above code as well as routes. Each image has a set-default button and above-added function works perfectly when I click that button in the front in Angular it sets default image as expected.  I assume it either it should like as written in Delete image above or it should like as Set Default function:
 ```
const { imgId, imgVersion } = req.params;
    await User.update(...
```

What are your thoughts about that?

**Comment by crazycodewriter** [comment]
@brian-cloudinary  it works now. Can you please tell me where to add `invalidate: true`
I am asking it because after removing the image it's still caching. I checked documentation but it was a bit confusing.

```
cloudinary.config({
  cloud_name: 'name',
  api_key: 'key',
  api_secret: 'secret'
});

module.exports = {
async DeleteImage(req, res) {
    try {
      const {imgId,imgVersion } = req.params;
      cloudinary.uploader.destroy(imgId,async function(response){
        console.log("response",response)
        if(response.result == 'ok'){
          let updatedUser = await User.updateOne({
            _id: req.user._id
          }, {
            $pull: {
              images: {
                imgId: imgId,
                imgVersion: imgVersion
              }
            }
          })
          if (updatedUser) {
            res.status(HttpStatus.OK).json({
              message: 'Image deleted successfully'
            })
          } else {
            res.status(HttpStatus.INTERNAL_SERVER_ERROR).json({
              message: 'Error deleting image'
            })
          }
        }else{
          res.status(HttpStatus.BAD_REQUEST).json({
            message: 'Image not found'
          })
        }
      });
    } catch (error) {
      res.status(HttpStatus.INTERNAL_SERVER_ERROR).json({
        message: 'Error occured'
      })
    }
  },
```

**Comment by brian-cloudinary** [comment]
Hi @crazycodewriter,

Per the documentation, `invalidate: true` would be passed inside the `object` parameter in the destroy function.

```
cloudinary.uploader.destroy(imgId, { invalidate: true }, function (err, res) {
    ...
})
```

Note that when setting `invalidate` to `true`, it will take a few minutes to fully propagate the changes throughout the CDN.

**Comment by crazycodewriter** [comment]
@brian-cloudinary  after adding it, the function is starting to behave like in past and doesn't delete at all without any error.

```
cloudinary.uploader.destroy(imgId , { invalidate: true },  async function(response){
        console.log("response",response)
        if(response.result == 'ok'){
     ...
    ...
```

When I remove `{ invalidate: true }` it starts working again but caching is there.  Is there another way to stop caching?

**Comment by brian-cloudinary** [comment]
Hi @crazycodewriter,

`async function(response)` should be `async function(error, response)`

**Comment by crazycodewriter** [comment]
The result is the same. It seems better to have a working delete function with caching than having a function that doesn't work at all :D Deleting is very sensitive in cloudinary.

**Comment by brian-cloudinary** [comment]
Are you using v1 of the SDK?

v1:
```
const cloudinary = require('cloudinary')
cloudinary.uploader.destroy(imgId, {invalidate: true}).then(res => console.log(res))
```

v2:
```
const cloudinary = require('cloudinary').v2
cloudinary.uploader.destroy(imgId, {invalidate: true}, (err, res) => console.log(res))
```

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
