### ISSUE TITLE
How to optimize image during the uploading in this code?

### ISSUE THREAD

**Issue by ArtyomBaykov** [cloudinary/cloudinary_npm#236]
I've found a video tutorial with this example which works fine but want to know how to optimize image during the upload. I don't know compress it or optimize? I checked documentation but don't know what must be included here?

```
cloudinary.config({
  cloud_name: '...',
  api_key: '...',
  api_secret: '...'
});

  UploadImage(req, res) {
    cloudinary.uploader.upload(req.body.image, async result => {
      await User.update(
        {
          _id: req.user._id
        },
        {
          $push: {
            images: {
              imgId: result.public_id,
              imgVersion: result.version
            }
          }
        }
      )
        .then(() =>
          res
            .status(HttpStatus.OK)
            .json({ message: 'Image uploaded' })
        )
        .catch(err =>
          res
            .status(HttpStatus.INTERNAL_SERVER_ERROR)
            .json({ message: 'Error could not upload image' })
        );
    });
  },
```

**Comment by aditimadan-Cloudinary** [comment]
You can pass it after the resource path inside cloudinary.uploaded.upload method. 
Something like this: 

`cloudinary.v2.uploader.upload('/home/my_image.jpg', {width: 1000, height: 1000, crop: "limit"},
    function(error, result) {console.log(result, error)});
`

**Comment by ArtyomBaykov** [comment]
@aditimadan-Cloudinary  in my case it should be like this?
```
 cloudinary.uploader.upload(req.body.image, {width: 1000, height: 1000, crop: "limit"},
  async result => {
      await User.update(
        {...
   ...
```

**Comment by aditimadan-Cloudinary** [comment]
Yes, that is correct.

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
