### ISSUE TITLE
Uploading with Buffer won't keep original name

### ISSUE THREAD

**Issue by Clemens-B** [cloudinary/cloudinary_npm#238]
Hello,

we are having the same issue as in https://github.com/cloudinary/cloudinary_npm/issues/181

Uploading via `cloudinary.uploader.upload_stream()` won't keep the original name running the latest cloudinary package.

**Buffer locks like this:**
`{ fieldname: 'files',
    originalname: '6.jpg',
    encoding: '7bit',
    mimetype: 'image/jpeg',
    buffer:
     <Buffer ff d8 ff e0  ... >,
    size: 715228
 },`

**Response from the upload_stream() is:**
`{ public_id: 'jpxft8q6mj6fvdokt6d7',
    version: 1550746854,
    signature: '7dae8ea9ab5a0f2c4567e15bb83adce89f420a83',
    width: 1600,
    height: 1201,
    format: 'jpg',
    resource_type: 'image',
    created_at: '2019-02-21T11:00:54Z',
    tags: [],
    bytes: 715228,
    type: 'upload',
    etag: 'a4b10e79a754917e5aaea2647ef9fbe9',
    placeholder: false,
    url:
     'http://res.cloudinary.com/.../jpxft8q6mj6fvdokt6d7.jpg',
    secure_url:
     'https://res.cloudinary.com/.../jpxft8q6mj6fvdokt6d7.jpg',
    original_filename: 'file' },`

As you can see the `original_filename` is 'file' instead of '6'.

**Comment by Clemens-B** [comment]
Nevermind. It's clear the `original_filename` is always 'file" because you can only pass the buffer.

```javascript
const file = { fieldname: 'files', originalname: '6.jpg', encoding: '7bit', mimetype: 'image/jpeg', buffer: <Buffer ff d8 ff e0 ... >, size: 715228 },

cloudinary.uploader.upload_stream(file.buffer)
```

It would be nice if we could pass an object or a parameter into `upload_stream` to define the file name.

**Comment by strausr** [comment]
@Clemens-B my apologies for the late response. Thank you for the feedback. We'll discuss this internally and update here if any changes are made.

**Comment by strausr** [comment]
@Clemens-B Thank you for your input. This is not on our immediate roadmap. That being said, if we decide to support this in the future we'll update
