### ISSUE TITLE
Error: ENOENT: no such file or directory, open

### ISSUE THREAD

**Issue by TheLizette** [cloudinary/cloudinary_npm#240]
Currently I am having trouble upload a image through using the line: 

`const result = await cloudinary.v2.uploader.upload(req.body.fileName,  
        function(error, result) {
            console.log(result, error); 
        });`

where `req.body.fileName` is the image name "myimagename.jpg" (I printed this information to make sure this is what it was).  `req.body.fileName`  is the name of the image a user uploads through an input. 

`<input type="file" name="image" id="image" onChange ={this.fileSelectedHandler}/>

I am getting the error 

> { [Error: ENOENT: no such file or directory, open 
[0]   errno: -4058,
[0]   code: 'ENOENT',
[0]   syscall: 'open',
[0]   path:
[0] (node:30052) UnhandledPromiseRejectionWarning: #<Object>
[0] (node:30052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

I  know the error ENOENT shows up  when the file is not in the corresponding directory...but that is because the jpg is not in the directory, rather I am trying to have users upload an image from an <input> , then that image being converted into a cloudinary URL

Any help would be appreciated. Thank  you

**Comment by strausr** [comment]
Can you share how the user is supplying the input?

**Comment by TheLizette** [comment]
The user is supplying the input through 
`<form method ="put"  action='/:id' enctype="multipart/form-data">  
          <input type="file" name="image" id="image" /> 
</form>`

where the put request is 

`router.put('/:id', upload.single('image'), async(req, res) => {
    var id = req.params.id;
    console.log(req.body.fileName);
    const result = await cloudinary.v2.uploader.upload(req.body.fileName,  
        function(error, result) {
            console.log(result, error); 
        });
    profilePic.findOne({_id: id}, function(err, foundObject) {
        if(err) {
        console.log(err);
        res.status(500).send();
        }
        else {
            if(!foundObject){
                res.status(404).send();
            }
            else {
                if(req.body.fileName) {
                foundObject.result =req.body.result;
                }
                foundObject.save(function(err, users) {
                    if(err) {
                    console.log(err);
                    res.status(500).send();
                    }
                    else {
                    res.send(users);
                    //console.log(foundObject.imageUrl);
                    //console.log("successfully updated imageUrl")
                    }
                })
            }
        }
    })
})`

**Comment by TheLizette** [comment]
The user is supplying the input  through 
`<form method ="put"  action='/:id' enctype="multipart/form-data">  
                <input type="file" name="image" id="image" /> 
              </form>`

and the put function is:

`router.put('/:id', upload.single('image'), async(req, res) => {
    var id = req.params.id;
    console.log(req.body.fileName);
    const result = await cloudinary.v2.uploader.upload(req.body.fileName,  
        function(error, result) {
            console.log(result, error); 
        });
    profilePic.findOne({_id: id}, function(err, foundObject) {
        if(err) {
        console.log(err);
        res.status(500).send();
        }
        else {
            if(!foundObject){
                res.status(404).send();
            }
            else {
                if(req.body.fileName) {
                foundObject.result =req.body.result;
                }
                foundObject.save(function(err, users) {
                    if(err) {
                    console.log(err);
                    res.status(500).send();
                    }
                    else {
                    res.send(users);
                    }
                })
            }
        }
    })
})`

**Comment by shirlymanor** [comment]
It seems that your app is expecting to find a file at req.body.fileName but that file does not exist. Can you try using a URL as a file name?. for example:

```
cloudinary.v2.uploader.upload("http://res.cloudinary.com/demo/image/upload/sample.jpg", ...
```
Please let us know if that works

**Comment by TheLizette** [comment]
Well the thing is, there wouldn't be a preexisting URL if the line
`const result = await cloudinary.v2.uploader.upload(req.body.fileName, function(error, result) { console.log(result, error); });`
 is the line that will create the cloudinary URL. 

I want to be able to have a user upload an image through the <input> then that jpg to be created into a cloudinary URL

**Comment by shirlymanor** [comment]
Yes, I'm trying to understand where exactly is the error.
What do you get in the console.log(req.body.fileName)?
Can you try using something like `req.file.path`?

**Comment by TheLizette** [comment]
I had tried `req.file.path` before and it threw out an error saying that path was undefined. I had also added the requirement for path `const path = require('path').`  Do you know what that might mean?

**Comment by shirlymanor** [comment]
I saw on StackOverflow that you might want to try: `req.file.image` Can you please try to print it out and let me know what the result? [Here](https://stackoverflow.com/questions/51813006/upload-image-then-update-with-multer-and-express-js/51957965) is a link.

**Comment by TheLizette** [comment]
when I try `req.file.image` I get the error `"UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'image' of undefined"`

Within my router.put function I tried `console.log(req.file);` which printed "undefined"... perhaps there is an error withing my multer set up? I can't really pinpoint what the problem is. 

Here is the multer code I have for reference: 

> 

> const multer =require("multer")

module.exports=multer({
    storage:multer.diskStorage({}),
    fileFilter: (req, file, cb) => {
        if(!file.mimetype.match(/jpe|jpeg|png|gif$i/)){
            cb(new Error('File is not supported'), false)
            return
        }
        cb(null, true)
    }
})

**Comment by yakirp** [comment]
Hi, 
I think this is something with your `multer` configuration.

Please see this simple example (I used the upload_stream, beacuse I'm workign with memory as a storage):

```
var express    = require('express');
var cloudinary = require('cloudinary');

var multer  = require('multer');
var storage = multer.memoryStorage();
var upload = multer({ storage: storage });
var stream = require('stream');
 
cloudinary.config({ 
    cloud_name: '*****', 
    api_key: '******', 
    api_secret: '******' 
  });
 
var app = express();

app.post('/:id', upload.single('image'), function (req, res, next) {

 var upload_stream = cloudinary.v2.uploader.upload_stream(function(err,image) {   
      res.send(image.secure_url);
});

var bufferStream = new stream.PassThrough();
bufferStream.end(req.file.buffer);
bufferStream.pipe(upload_stream);
})

module.exports = app;
```

Please try to isolate the issue with simple `multer` use. 

Btw, could you please try to remove the `async` form your code, and try to see if it works for you?
Here:
`router.put('/:id', upload.single('image'), async(req, res) => {
`

I'm looking forward to your response.

Yakir

**Comment by TheLizette** [comment]
I tried implementing what you said but am still getting an error. The error is: `MulterError: Unexpected field` . This error appears when I test the code on postman. Not when I upload directly through the input form on the site. 

Here is what I changed: 
```
const express = require("express");
const bodyParser = require('body-parser');
const router = express.Router();
const path = require('path');

require('dotenv').config();
require('../../client/src/components/handlers/cloudinary');
const cloudinary =require("cloudinary");
var multer  = require('multer');
var storage = multer.memoryStorage();
var upload = multer({ storage: storage });
var stream = require('stream');

router.put('/:id', upload.single('image'), function(req, res, next) {
    var upload_stream = cloudinary.v2.uploader.upload_stream(function(err,image) {   
        res.send(image.secure_url);
  });
  console.log(upload_stream);
  var bufferStream = new stream.PassThrough();
  bufferStream.end(req.file.buffer);
  bufferStream.pipe(upload_stream);
  })
```
And I am no longer using the old multer set up I had

**Comment by yakirp** [comment]
Could you please share with me the postman call?

**Comment by TheLizette** [comment]
Yes here it is below
![postman](https://user-images.githubusercontent.com/32748021/54090029-d99bd000-432c-11e9-9ed5-79a0a196e49d.JPG)

**Comment by yakirp** [comment]
Please set the key to "image" and let me know if it works for you

**Comment by TheLizette** [comment]
Postman doesn't seem to have an option of image as a key. It has text or file as options

**Comment by TheLizette** [comment]
That worked! Thank you so much I really appreciate your help :)

**Comment by yakirp** [comment]
Great! Glad I could help.

Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by TheLizette** [comment]
I realized this solution works on Postman, but not with the actual form on the site. For example on postman the cloudinary URL is created once an image is uploaded.  But when I test it with my form on the site, there is no  sign  of the  form performing the post request.

Any idea on why the form may not be performing the post request?

Below is the code I have that is working (on postman): 

> profilePage.js

```
<form method ="put"  action='/:id' enctype="multipart/form-data">  
        <input type="file" name='image' id='image' /> 
</form>
```

> userPicture.js

```
const express = require("express");
const bodyParser = require('body-parser');
const router = express.Router();
const path = require('path');

require('dotenv').config();
require('../../client/src/components/handlers/cloudinary');
const cloudinary =require("cloudinary");
var multer  = require('multer');
var storage = multer.memoryStorage();
var upload = multer({ storage: storage });
var stream = require('stream');

router.put('/:id', upload.single('image'), function(req, res, next) {
    var upload_stream = cloudinary.v2.uploader.upload_stream(function(err,image) {   
        res.send(image.secure_url);
  });
  console.log(upload_stream);
  var bufferStream = new stream.PassThrough();
  bufferStream.end(req.file.buffer);
  bufferStream.pipe(upload_stream);
  })
```

**Comment by TheLizette** [comment]
@yakirp can I have this issue opened again?

**Comment by yakirp** [comment]
Please try to add submit button:

```
<form method ="put"  action='/:id' enctype="multipart/form-data">  
        <input type="file" name='image' id='image' /> 
       <input type="submit" value="Upload Image" name="submit">
</form>
```

**Comment by TheLizette** [comment]
When adding a submit button I get in return 
![image](https://user-images.githubusercontent.com/32748021/54105643-e8b46980-4390-11e9-820d-92ba56f235f7.png)

Although the put request is fully functioning in postman...

**Comment by yakirp** [comment]
True, according to the HTML standard, you can only GET or POST.
`<form method="put"> `is invalid HTML and will be treated like `<form>`, i.e. send a GET request.
[source](https://stackoverflow.com/a/8054241)

So change to POST in the HTML and in your backend.

**Comment by yakirp** [comment]
Also note that you probably want to dynamically change the `/:id`

**Comment by TheLizette** [comment]
Changing the form method to post did not change anything. It result with the same message `Cannot post /:id`

What do you mean by changing the /:id dynamically?

**Comment by yakirp** [comment]
Just to make it wokr for now, please chnage this:
`router.put('/:id', upload.single('image'), function(req, res, next) {`
To this:
`router.post('/', upload.single('image'), function(req, res, next) {`

And this:
`<form method ="put"  action='/:id' enctype="multipart/form-data">  `

To this:
`<form method ="post"  action='/' enctype="multipart/form-data"> `

**Comment by TheLizette** [comment]
by changing the form and post request to be like you mentioned above, the request is still not being made. 

![53738125_2054540391509914_397054006934896640_n](https://user-images.githubusercontent.com/32748021/54138343-7ff2de80-43dc-11e9-9cfb-61f9c5ac69c6.png)

**Comment by yakirp** [comment]
I'm not sure why it's posted to /profile/<id>?

Could you please share the HTML code?

**Comment by TheLizette** [comment]
There is no HTML code for it.  I have the form in a javascript file in the render portion of the code. The form is being rendered on a page `localhost:3000/profile/uniqueUserID` where uniqueUserID is different depending on the user

**Comment by yakirp** [comment]
If you're posting to `/profile/uniqueUserID` you also need to add a router for that.
As from your code, I see only `router.put('/:id', upload.single('image'), function(req, res, next) {` so maybe `router.put('/profile/:id', upload.single('image'), function(req, res, next) {` could help.

**Comment by TheLizette** [comment]
Thank you!

**Comment by yakirp** [comment]
Glad I could help :)
