### ISSUE TITLE
how to get public_id from url ?

### ISSUE THREAD

**Issue by mikestaub** [cloudinary/cloudinary_npm#243]
Is there a way?

**Comment by aditimadan-Cloudinary** [comment]
Cloudinary returns public_id in the JSON response for the calls to Cloudinary. You can always get the last part of the URL which is the public_id, anything after the version.
What API call are you performing?

**Comment by mikestaub** [comment]
I am calling the delete_resource method. I know I can simply parse the url, but I was hoping there was something less hacky. Do you have an official regex I can use?

**Comment by aditimadan-Cloudinary** [comment]
The delete_resource method returns the public_id of the resources in the response and you can extract the values from the JSON response.

**Comment by mikestaub** [comment]
delete_resource takes the public_id as a parameter. We are not storing public_ids, just URLs. I guess we can just continue to parse the url.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
