### ISSUE TITLE
customize image_search API call in widget v2

### ISSUE THREAD

**Issue by mikestaub** [cloudinary/cloudinary_npm#245]
When using the upload widget with google image_search, I noticed some of the results being returned are too small for the preset. There is no point returning these images.

Can we customize the google search query to specify minimum image size?

Also, I really think there should be a separate repo for the upload widget. This issue does not belong here, and I worry other devs will not be able to search for similar questions in the future.

**Comment by yakirp** [comment]
Hi @mikestaub,

I opened a feature request on your behalf. Will keep you posted here.

Thanks!
Yakir

**Comment by roeeba** [comment]
Closing this issue as it's irrelevant to our NPM package. We will, however, update here if and when this will be developed.
