### ISSUE TITLE
preload custom serach term in cloudinary uploader v2 image_search

### ISSUE THREAD

**Issue by mikestaub** [cloudinary/cloudinary_npm#247]
Feature request: When the user opens the uploader, we should be able to preload the search input with a custom string.

**Comment by shirlymanor** [comment]
In order for me to open a feature request, can you please elaborate more of this feature?
For example:
* Is this feature related to our [upload widget](https://cloudinary.com/documentation/upload_widget)?
* Is the preload search string can be changed by the user?

Looking forward to your response,

**Comment by mikestaub** [comment]
The answer to both of your questions is yes.

**Comment by shirlymanor** [comment]
Thanks, I opened a feature request to our product to consider adding it to our road-map.

**Comment by shirlymanor** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
