### ISSUE TITLE
Upload preset must be whitelisted for unsigned uploads

### ISSUE THREAD

**Issue by mikestaub** [cloudinary/cloudinary_npm#254]
Can you please open-source the uploader widget? It would help me debug issues like this.

I made no changes to my code, but now the uploader is not working for any source except local. The 'uploadSignature' function is not being called at all and I get that error.

I can't debug the issue because the uploader is a black box iframe.

**Comment by aditimadan-Cloudinary** [comment]
"Upload preset must be whitelisted for unsigned uploads" is usually when you try and use signed preset instead of unsigned. Can you please open a support ticket here:https://support.cloudinary.com/hc/en-us/requests/new and share your cloud name and upload preset and I will be able to debug this further.

**Comment by mikestaub** [comment]
Any update on this? I think it must be a regression. My uploadSignature function is being called when I use the local source, just not any others. Again I did not change my code. Is there a reason the upload widget is not open source? I would be happy to PR with a fix.

**Comment by strausr** [comment]
@mikestaub As Aditi mentioned, can you please open a ticket with your implementation so that we can further asses this?

**Comment by mikestaub** [comment]
I already submitted a ticket last week. I just submitted another in case it got lost.

**Comment by mikestaub** [comment]
From the support thread:

```
... I'm able to reproduce this.
To put a bit more context, this issue only happens when both cropping:true and maxImageHeight and/or maxImageWidth is/are defined then we are running into this issue.

I've reached out to our engineer to look into this and working on the fix.
```

**Comment by lfernando-silva** [comment]
I'm also getting this error just using the REST API, not the widget. Even signed requests throws this error about unsign ones.

**Comment by shirlymanor** [comment]
@lfernando-silva As Aditi mentions it is usually when you try and use signed preset instead of unsigned. Can you please open a support ticket here:https://support.cloudinary.com/hc/en-us/requests/new and share your cloud name and upload preset and I will be able to debug this further.

**Comment by mikestaub** [comment]
@shirlymanor in my case, I was already using a signed preset.

@lfernando-silva The root cause is that not all options are compatible with each other. Try to start very simple and slowly add new options one by one until you hit the error. That is how I was able to triage the issue.

**Comment by lfernando-silva** [comment]
I just tried with a new unsigned preset, with all default options, now an unsigned upload an it fails with the same error. I didn't change any configuration.

`POST https://api.cloudinary.com/v1_1/MY_CLOUD_NAME/image/upload`

```js
{
     unsigned: true,
     upload_preset: "MY_PRESET_CODE"
}
``

**Comment by shirlymanor** [comment]
@lfernando-silva can you please contact us at support@cloudinary.com with your cloud name for further investigation.

**Comment by lfernando-silva** [comment]
Just contacted the support and they helped me to realize that the request body must to be a form data, not a JSON with multipart/header, to get it working properly. My mistake!

Thanks for the help.
