### ISSUE TITLE
Uploading video

### ISSUE THREAD

**Issue by callmekatootie** [cloudinary/cloudinary_npm#26]
I am using `cloudinary.uploader.upload()` to upload a video file.

However, I get the response as  
`{error: { message: 'Invalid image file', http_code: 400}}`

The documentation says that I should be able to upload any files including videos but this does not seem to work in this case.

**Comment by souli2020** [comment]
For anyone recently  facing this issue and researches for a solution and came across this comments  you can use this : 
 cloudinary: cloudinary,
    params: async (req, file) => {
        let resource_type = 'auto';
        if (file.mimetype.startsWith('image/')) {
            resource_type = 'image';
        } else if (file.mimetype.startsWith('video/')) {
            resource_type = 'video';
        }
        return {
            folder: 'folder',
            allowed_formats: ['jpeg', 'jpg', 'png', 'mp4',.....],
            public_id: `${Date.now()}-${file.originalname}`,
            resource_type: resource_type,
        };
    },

**Comment by shivanshu-2002** [comment]
Try ..to use cloudinary.v2...const uploadFileToCloudinary = async (file, folder) => {
     const options = { folder };  
     options.resource_type="auto"; 
     try {
       const response = await cloudinary.v2.uploader.upload(file.tempFilePath, options);
       return response;
     } catch (error) {
       console.error('Error uploading to Cloudinary:', error);
       throw error; // Re-throw the error to handle it in the calling function
     }
   }

**Comment by dannyv-cloudinary** [comment]
Hey @shivanshu-2002.

The best thing to do here would be to [raise a support ticket with us](https://support.cloudinary.com/hc/en-us/requests/new), including your cloud name and the error message you get in response when you run that code snippet.

All the best,
-Danny

**Comment by khushalhingorani1304** [comment]
const uploadFileToCludinary = async (file, folder) => {
    const options = {
        folder,
        resource_type: "auto"
    };
    console.log("TempfilePath: ",file.tempFilePath);
    return await cloudinary.uploader.upload(file.tempFilePath, options);
};

const response = await uploadFileToCludinary(file,"FileUpload");

while uploading video to cloudinay this code gives 

{ message: 'Invalid image file', name: 'Error', http_code: 400 } 

I have tried reading every documentation and done everything but it is not working please help!
