### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by giuliana-bezerra** [cloudinary/cloudinary_npm#264]
How can I use my coorporative proxy (localhost:3128) in cloudinary api calls? Is there a cloudinary config for this? This is what I have so far:

```
const multer = require('multer');
const cloudinary = require('cloudinary');
const cloudinaryStorage = require('multer-storage-cloudinary');

cloudinary.config({
    cloud_name: process.env.CLOUD_NAME,
    api_key: process.env.CLOUDINARY_API_KEY,
    api_secret: process.env.CLOUDINARY_API_SECRET
});

const storage = cloudinaryStorage({
    cloudinary: cloudinary,
    folder: 'myfolder',
    allowedFormats: ['jpg', 'png'],
    transformation: [{ width: 500, height: 500, crop: 'limit' }]
});

module.exports = async (req, res) => {
    console.log('Service..');
    const parser = multer({ storage });
    console.log('Parser created..');
    let upload = parser.single('file');
    console.log('Upload created..');
    upload(req, res, err => {
        //It's not called!
        console.log('Upload called..');
        if (err)
            res.status(500).json({ error: 1, payload: err });
        else {
            const image = {};
            image.url = req.file.url;
            image.id = req.file.public_id;
            res.status(200).json({ error: 0, payload: { id: image.id, url: image.url } });
        }
    });
}
```
The log:

```
Service..
Parser created..
Upload created..
Upload called..
```

**Comment by igy** [comment]
Hi Guiliana,

There isn't currently a way to configure our SDK to use a proxy server for outbound connections. There is a proxy field in the SDK but this is passed through on upload requests for when you're asking us to use a proxy server when fetching from a remote server (i.e this is the 'proxy' parameter on https://cloudinary.com/documentation/image_upload_api_reference )

To proxy the requests from your Node code to Cloudinary's API, I'd recommend that you configure the server itself to send all requests via your proxy- we don't have a specific method we endorse for that, but these modules all provide different methods of achieving that:

https://github.com/gajus/global-agent
https://github.com/np-maintain/global-tunnel#readme
https://github.com/TooTallNate/node-http-proxy-agent

Thanks,
Stephen

**Comment by giuliana-bezerra** [comment]
This link (https://cloudinary.com/documentation/image_upload_api_reference) will work for me. Thanks!
