### ISSUE TITLE
options and callback args is not work correctly

### ISSUE THREAD

**Issue by RizkyArifNur** [cloudinary/cloudinary_npm#270]
i've try to set the ```options``` params but it's not work as expected and also the callback it's not invoked , i'am using the lastest version **cloudinary@1.14.0** and here's my code 
```javascript
cloudinary.uploader.upload(
      data, // this is path to image that will be uploaded
      {
        public_id: `image${Date.now()}` // this options was not working, the publicId is still random string
      },
      () => {
        console.log('invoked') // this callback was not invoked
      }
    )
``` 

anyone can help me??

**Comment by strausr** [comment]
@RizkyArifNur Can you please try adding the v2 option? 

`cloudinary.v2.uploader.upload(..`

**Comment by RizkyArifNur** [comment]
@strausr 
ahhh thank you, it's working correctly
