### ISSUE TITLE
Any plans of typescript addition?

### ISSUE THREAD

**Issue by jawadakram20** [cloudinary/cloudinary_npm#271]

**Comment by strausr** [comment]
@jawadakram20 Currently it is not in our near term plan. That being said, we'll update here if this changes in the future.

**Comment by inunotaisho26** [comment]
@strausr I am going to have stand by @jawadakram20 on this one. Typescript needs to be moved up in cloudinary's list of priorities.

**Comment by strausr** [comment]
@inunotaisho26 @jawadakram20 Thanks for the feedback. Although there isn't an exact ETA, we're planning on handling this during Q3. We'll update as soon as we have more information

**Comment by kerolloz** [comment]
almost everyone is moving to TypeScript, that would be great if you provide types :smile:

**Comment by idobarnoam** [comment]
@kerolloz thanks.
Its indeed planned but currently no exact ETA.

Once we will have something more concrete we will update the thread.

**Comment by repentsinner** [comment]
Thanks, could use type definitions here as well!

**Comment by roeeba** [comment]
Thanks for the note @repentsinner. Indeed, we'll update on #175 .
