### ISSUE TITLE
Can't get image url after uploading via upload_stream

### ISSUE THREAD

**Issue by Hellogark** [cloudinary/cloudinary_npm#276]
I need to get the uploaded image url with cloudinary.uploader.upload_stream,  but after upload if i console.log the response i get undefined. My keys are in an .env file
This is my code 
```
var cloudinary = require('cloudinary').v2;

var file = req.files.img; 
var fileName =file.name.split('.');
var ext = fileName[fileName.length - 1];

var fullName = `${md5(fileName[0])}.${ext.toLowerCase()}`;
    var options ={        
        use_filename:true,
        unique_filename:false,
        folder: `users/${id}/${fullName}`
    };
const result = await cloudinary.uploader.upload_stream(options,res=>console.log(res)).end(file.data);
```

file.data is a buffer, for example
`<Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 00 2a 00 00 00 2a 08 06 00 00 00 c5 c3 c9 5b 00 00 01 fb 49 44 41 54 58 85 ed 99 cd 4e c2 40 14 ... >`
When printing result, the only path i get is this one  `path: '/v1_1/dinamycstest/image/upload',` next a lot of info about the upload. but printing res returns undefinded.

**Comment by honeyjills** [comment]
Hi @Hellogark 
Did you find any solution for this issue. I am facing the same and having trouble figuring it out.

**Comment by Hellogark** [comment]
@honeyjills  i searched about getting the url without success, but what i did was build a const with the link in a string literal, like folder one in my code, but with the link of the uploaded file, something like this for raw files
` fileURL: `https://res.cloudinary.com/dinamycstest/raw/upload/fl_attachment/project/${idProject}/${fileName}`` With this url i can download raw files like rar/zip, video or audio. I save this url in my mongo db and diplay it in the download button to download the file.
This is an image uploaded to the server 
`https://res.cloudinary.com/dinamycstest/image/upload/v1561405066/xkux8cjcaf01ttqg5jhu.png`
you can ignore "v15614...." and "dinamyctest" is the cloud name.
In my case for user profile images i created a pipe in Angular to build the complete url and just save the file name in the db, or you can save the whole url in your db

**Comment by aditimadan-Cloudinary** [comment]
Here is a sample which will return the public_id and the URL from the upload stream.

```
var cloudinary = require('cloudinary').v2;
var fs=require('fs');

//make sure to add the cloudinary config or the env variable

var upload_stream= cloudinary.uploader.upload_stream(function(err,image) {
  if (err){ console.warn(err);}
  console.log("* "+image.public_id);
  console.log("image url:  "+image.url);
});
var file_reader = fs.createReadStream('<file path>').pipe(upload_stream);
```

**Comment by honeyjills** [comment]
@Hellogark Thanks for your reply.
You are talking about downloading the files rght. ? 
My question is about the uploading part. How did you upload the files to Cloudinary?

**Comment by honeyjills** [comment]
@aditimadan-Cloudinary Thank you for your reply. 
This was not working for me. The response was undefined as mentioned by @Hellogark .  All i have is the file buffer. I do not have the File path. 

Is it possible to upload files to cloudinary using the File Buffer?

**Comment by michalkcloudinay** [comment]
Hi,
It is possible to upload files using a File Buffer like this:
var file_reader = fs.createReadStream(<buffer>).pipe(upload_stream);
You can read more about it in this documantaion:
https://nodejs.org/api/fs.html#fs_fs_createreadstream_path_options

**Comment by NumaTejeda** [comment]
Hi! I had the same issue and I found this way. I hope it helps!

![image](https://github.com/user-attachments/assets/6d1bf180-fa59-49de-bbe5-dbd0235edc3e)
