### ISSUE TITLE
Enhancement: Upload multiple images

### ISSUE THREAD

**Issue by inunotaisho26** [cloudinary/cloudinary_npm#283]
There needs to be a more straight forward way of uploading multiple images to cloudinary. I know there are work arounds like using loops and such, but the cloudinary API needs to able o handle this natively. 

Reference @KalaiselvanMahendran @slim-hmidi @anaibol @leecrossley

**Comment by aditimadan-Cloudinary** [comment]
Our upload API currently only supports a single file upload at a time, it does have a high concurrency rate (of about 40-50 concurrent calls) so you can use multi-threads to upload many files at once.
You can also use asynchronous calls, and tell Cloudinary to do the upload in the background by adding the `async` parameter and setting it to `true`. 

Another option would be to use our [auto upload](http://cloudinary.com/blog/how_to_automatically_migrate_all_your_images_to_the_cloud) feature which will enable you to define a path from which the images could be uploaded. This would upload the images lazily (i.e., every time they are specifically called by the end-user).

Please share your use-case in detail and we will be able to assist you better.

**Comment by inunotaisho26** [comment]
@aditimadan-Cloudinary I understand what the API supports, but the issue still needs to be dealt with because it's not gonna go away.

**Comment by aditimadan-Cloudinary** [comment]
I will create a feature request for our product team to consider adding it in the future.

**Comment by strausr** [comment]
Closing due to time elapse. If we decide to add this to our roadmap we'll update
