### ISSUE TITLE
Error: ENOENT: no such file or directory after form submission through Postman

### ISSUE THREAD

**Issue by ramiyadash** [cloudinary/cloudinary_npm#284]
I tried to submit a form through postman, but i keep getting the no such file error,The pdf is not getting saved to the path mentioned in local pc, even though the file exists. Node keeps throwing the error : [Error: ENOENT: no such file or directory

Error: ENOENT: no such file or directory, open 'D:\lims\Generate_PDF_for_Forms\ViralFlexSeqSubmissionForm_Dash_7-2-2019_13:37:42.pdf'] errno: -4058, code: 'ENOENT', syscall: 'open', path: 'D:\lims-customer\Generate_PDF_for_Forms\ViralFlexSeqSubmissionForm_Dash_7-2-2019_13:37:42.pdf'

**Comment by aditimadan-Cloudinary** [comment]
Form the error it looks like it is not able to locate the file in that path. How are you uploading to Cloudinary? Can you please share the code or a URL where this can be tested. Have you tried uploading another file?

**Comment by ramiyadash** [comment]
Hi Aditi,

Thank you so much for your reply.
I believe I posted in the wrong group, I was looking up similar errors and
the post on GitHub popped up. I didn't use cloudinary, but error is similar.
I already have the file, and it works in production environment, but in
local it keeps throwing the same error of No such File or Directory.
I understand if you will not be able to help further.

Regards,
Ramiya

**Comment by aditimadan-Cloudinary** [comment]
Hi Ramiya,

Thanks for the clarification. I will close this thread.

Best,
Aditi
