### ISSUE TITLE
Deleting raw files

### ISSUE THREAD

**Issue by callmekatootie** [cloudinary/cloudinary_npm#29]
As per the [documentation](http://cloudinary.com/documentation/node_image_upload#update_and_delete_images) I should only supply the public ID and the image gets deleted.

This works fine for image files. However, for video files (or raw files), this does not work. I get the response `{ result: 'not found' }`

I am using `cloudinary.uploader.destroy(<public_id>, callback, {invalidate: true});` to delete the file but it fails only for raw files. Is there any special handling required when deleting raw files?

**Comment by Hellogark** [comment]
Well, @taragano  i'm having the same problem, i've tried with cloduinary v.2 as in the documentation but i'm getting this error `Cannot read property 'uploader' of undefined`. i'm setting the public id's as the name of the file on upload, so i'm trying to delete a zip file manually in my node.js app, this is the code i'm using to:
```
 return await cloudinary.v2.uploader.destroy('464ed5c2d1ccbff558f72105768c4079.zip',  {invalidate: true, resource_type: "raw"}, function (err, res) {
            if(err){
                console.log(err);
                return res.status(400).json({
                    ok:false,
                    mensaje: 'Error deleting file',
                    errors:err
                })
            }
            console.log(res);
    })
```
I'm getting not found as response
`{ result: 'not found' }`
this is the url `/v1561509799/projects/5cae3cf5b35e4d2dac90fcf6/464ed5c2d1ccbff558f72105768c4079.zip` the public_id it's supoused to be  `464ed5c2d1ccbff558f72105768c4079.zip`, i've tried with several paths, but nothing seems to work

**Comment by eyalktCloudinary** [comment]
Hi @Hellogark , 
The `public_id` of the asset is formed of the path of the asset within Cloudinary's cloud, together with the asset's name. Meaning that the `public_id` of the file is:
`projects/5cae3cf5b35e4d2dac90fcf6/464ed5c2d1ccbff558f72105768c4079.zip`
Try it out and let me know if that works for you?

```
return await cloudinary.v2.uploader.destroy('projects/5cae3cf5b35e4d2dac90fcf6/464ed5c2d1ccbff558f72105768c4079.zip', 
    { invalidate: true, resource_type: "raw"}, function (err, res) {
            if(err){
                console.log(err);
                return res.status(400).json({
                    ok:false,
                    mensaje: 'Error deleting file',
                    errors:err
                })
            }
            console.log(res);
    }
```
Hope this helps.

**Comment by Hellogark** [comment]
@eyalktCloudinary  My bad, just updated my comment, i'm not using `cloudinary.v2.uploader.destroy` v2 functions seems not working for me, although i'm requiring like this `var cloudinary = require('cloudinary').v2;`  i've  tried the public_id but still returning not found. If i use `cloudinary.v2.uploader.destroy` i'm getting this error message: 
```
TypeError: Cannot read property 'uploader' of undefined
    at app.delete (C:\Users\edmol\Documents\GitHub\backendServer\routes\proyectos.js:478:36)
    at Layer.handle [as handle_request] (C:\Users\edmol\Documents\GitHub\backendServer\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\edmol\Documents\GitHub\backendServer\node_modules\express\lib\router\route.js:137:13)
    at jwt.verify (C:\Users\edmol\Documents\GitHub\backendServer\middlewares\autenticacion.js:21:9)
    at C:\Users\edmol\Documents\GitHub\backendServer\node_modules\jsonwebtoken\verify.js:223:12
    at getSecret (C:\Users\edmol\Documents\GitHub\backendServer\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\edmol\Documents\GitHub\backendServer\node_modules\jsonwebtoken\verify.js:94:10)
    at exports.verificaToken (C:\Users\edmol\Documents\GitHub\backendServer\middlewares\autenticacion.js:10:9)
    at Layer.handle [as handle_request] (C:\Users\edmol\Documents\GitHub\backendServer\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\edmol\Documents\GitHub\backendServer\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\edmol\Documents\GitHub\backendServer\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\edmol\Documents\GitHub\backendServer\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\edmol\Documents\GitHub\backendServer\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\edmol\Documents\GitHub\backendServer\node_modules\express\lib\router\index.js:354:14)
    at param (C:\Users\edmol\Documents\GitHub\backendServer\node_modules\express\lib\router\index.js:365:14)
    at param (C:\Users\edmol\Documents\GitHub\backendServer\node_modules\express\lib\router\index.js:365:14)
```

**Comment by eyalktCloudinary** [comment]
@Hellogark Note that if you're requiring cloudinary like this 
`var cloudinary = require('cloudinary').v2;`,
you do not need to re-specify `v2` when calling the uploader.
Try using `cloudinary.uploader.destroy` ?

**Comment by Hellogark** [comment]
@eyalktCloudinary yeah, i've tried with `cloudinary.uploader.destroy` but i'm getting not found as response, i've trided with the whole url too, included the version for the public_id but still getting the same response

**Comment by Hellogark** [comment]
well, this is strange, i got `{result: ok}` i had to made a string with template literals `var public_id = `projects/${idProject}/${body.file.name}`;`
then my code result like this 
```
try {
        
        return await cloudinary.uploader.destroy(public_id,  {invalidate: true, resource_type: "raw"}, function (err, res) {
                 if(err){
                     console.log(err);
                     return res.status(400).json({
                         ok:false,
                         mensaje: 'Hubo un problema al eliminar el archivo',
                         errors:err
                     })
                 }
                 console.log(res);
     
         })
    } catch (error) {
        console.log("error "+error)
    }
```
but if i set the public_id manually as string it doesn't work

**Comment by eyalktCloudinary** [comment]
@Hellogark The version is not part of the `public_id`.
I want to make sure we're on the same page, if you run the following, what is the response?

```
var cloudinary = require('cloudinary').v2;
return await cloudinary.uploader.destroy('projects/5cae3cf5b35e4d2dac90fcf6/464ed5c2d1ccbff558f72105768c4079.zip', 
    { invalidate: true, resource_type: "raw"}, function (err, res) {
            if(err){
                console.log(err);
                return res.status(400).json({
                    ok:false,
                    mensaje: 'Error deleting file',
                    errors:err
                })
            }
            console.log(res);
    }
```

In addition, can you provide your cloud name? It'll help me further investigate.

**Comment by Hellogark** [comment]
I made it work as i said in my coment above, thanks for the help, i taught the public_id was the one i set in my upload options that is just set as the file name with the extension. This is the cloud name `dinamycstest`

**Comment by eyalktCloudinary** [comment]
@Hellogark You're welcome, glad to hear you've worked it out!

**Comment by Enado95** [comment]
> @Hellogark You're welcome, glad to hear you've worked it out!

HI @eyalktCloudinary i have you exact implementation but i still receive not found see code below: 

```javascript
var cloudinary = require("cloudinary").v2;
require("dotenv").config();

cloudinary.config({
  cloud_name: process.env.CLOUD_NAME,
  api_key: process.env.CLOUD_API_KEY,
  api_secret: process.env.CLOUD_API_SECRET
});

var cloudinary = require("cloudinary").v2;
const deleteimage = async () => {
  return await cloudinary.uploader.destroy(
    "folder/mrobompy9ci9xawtmvcv.png",
    { invalidate: true, resource_type: "raw" },
    function(err, res) {
      if (err) {
        console.log(err);
        return res.status(400).json({
          ok: false,
          mensaje: "Error deleting file",
          errors: err
        });
      }
      console.log(res);
    }
  );
};

deleteimage()
```

**Comment by melitus** [comment]
Ensure that during the upload that your resource_type is set to "raw". That way, you can set it again to "raw" whenever you want to delete a resource. This is my code for deleting below. 
```

const deleteImage = async publicId => {
  console.log({publicId})

  try {
    const response = await cloudinary.v2.uploader.destroy(publicId, {
      invalidate: true,
      resource_type: "raw"
    })
    console.log({response})

    if (response.result !== 'ok') {
      throw {
        error: new Error(response.result)
      }
    }
  } catch (error) {
    console.trace({error})
    throw error.error
  }
}
```
It works perfectly

**Comment by alanyong91** [comment]
@melitus I still get `result { result: 'not found' }` with exact same setup. 
`publicId` is the full URL or folder path?

**Comment by eyalktCloudinary** [comment]
@alanyong91 Hey, in general, the `publicId` is the concatenation of the file's path in Cloudinary and its name. For instance, if a file named "my-asset" resides under the "animals/dogs/" Cloudinary folder path then its `publicId` would be "animals/dogs/my-asset". Note that when it comes to assets of type `raw`, the public ID [must contain](https://cloudinary.com/documentation/upload_images#uploading_non_media_files_as_raw_files) the file extension. Therefore, continuing the example above, if "my-asset" is a ZIP file (i.e of type `raw`), then its `publicId` would be "animals/dogs/my-asset.zip".

I hope this helps. If it doesn't, could you please [open a support ticket](https://support.cloudinary.com/hc/en-us/requests/new), so we could investigate further? Be sure to specify your cloud name, an example of a file that you aren't able to delete, and the steps you are performing in order to delete it.
