### ISSUE TITLE
upload_stream gets error 499 - can I change timeout setting

### ISSUE THREAD

**Issue by Synaccord** [cloudinary/cloudinary_npm#293]
Occasionaly, when I am uploading videos (~20MB) I get an upload error 499 which seems to be a time out.  I want to increase the timeout to see if that solves the problem, but I am using upload_stream and don't seem to have a way to pass options to it.

Is there a way to change the timeout? 
Is there a way to force a retry when I catch this error? I can't easily restart the upload because the node server is receiving it from the browser as a stream and then uploading it to cloudinary.   The browser is using socket.io-stream.   

I am uploading videos to cloudinary using the following:

	var cloudStream=cloudinary.v2.uploader.upload_stream({resource_type: 'video', public_id}, (err, result)=>{
		if(err) {
			logger.error('upload video cloudinary.uploader.upload_stream error:', err, data);
			cb();
		} else {
			cb(result.secure_url);
		}
	})
	stream.pipe(cloudStream)
		.on('error', (err) => {
			logger.error("Error uploading stream:", filename, err)
			cb();
	})
	cloudStream.on('error',(err)=>{
		console.info("cloudStream error:",err)
		cb();
	})

Most of the time this works fine, but one in a while there is a long pause, and then this error:

> upload video cloudinary.uploader.upload_stream error: { message: 'Request Timeout', http_code: 499 } { name: '5d64b5eca43d823b24014692-3-speaking20190827T045111

I see in this issue report about increasing the time out: https://github.com/cloudinary/cloudinary_npm/issues/62

However, in the upload_streams api I don't seem to have the ability to pass options.

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
