### ISSUE TITLE
incoming transformation before upload image (flags: "force_strip") not working

### ISSUE THREAD

**Issue by yongyi520** [cloudinary/cloudinary_npm#296]
`file.path = /var/folders/mc/f0gh5vsd27d_f_s0ncjdg_h80000gn/T/upload_16e9d84f6bbbba08970ff5eb06a81ee5`

`const response = await cloudinary.uploader.upload(file.path, {
          public_id,
          image_metadata: true,
          flags: "force_strip"
        });`

Problem: 
The image uploads from iPhone selfies were incorrectly rotated when uploading the image to cloudinary. 

I tried to apply flags: "force_strip" to remove the meta data from images as mentioned from this link:
https://cloudinary.com/documentation/transformation_flags

However, the problem still exist and images are still incorrectly rotated when upload to the server

Any solutions to disable the automatic rotation?

**Comment by cloudinaraz** [comment]
Hi @yongyi520,

By default, Cloudinary indeed automatically rotate the image on upload, according to the orientation specified in the EXIF metadata.

To override that functionality, you need to add the `angle: "ignore"` parameter to your upload request instead of `flags: "force_strip"`.
This will disable the automatic rotation and will let you achieve the results you are looking for.

**Comment by yongyi520** [comment]
Hi @cloudinaraz 

I have tried your suggestion and the result still rotates the image incorrectly on iPhone X. (sorry for the blown up images coming up)

Here's the upload code with file.path on the server
`file.path=/tmp/upload_252ba9fb3c3ce0b928f37f3303a2e0a1`
`const response = await cloudinary.uploader.upload(file.path, {
          public_id,
          angle: "ignore"
        });`
response i got was 
![Screen Shot 2019-09-08 at 9 25 39 PM](https://user-images.githubusercontent.com/10789851/64489586-43b31480-d27f-11e9-8b2b-e145e5e40d63.png)

The image at the crop window is the original photo:
![Screen Shot 2019-09-08 at 9 28 57 PM](https://user-images.githubusercontent.com/10789851/64489634-b0c6aa00-d27f-11e9-8a28-5710fa4013fb.png)

The image here is the photo linked to cloudinary after upload
![Screen Shot 2019-09-08 at 9 28 45 PM](https://user-images.githubusercontent.com/10789851/64489641-b3c19a80-d27f-11e9-84b7-96b6aae89c4d.png)

**Comment by yongyi520** [comment]
If it helps, here's my client side code for uploading the file to the server:

------
const fileUrl = await getBase64(file)
// crop image
// calculate cropped area pixel
const initialCroppedAreaPixels = await calculateInitialCroppedAreaPixels(fileUrl, aspect)

// initial crop
if(initialCroppedAreaPixels) {
    const croppedImageFile = await getCroppedImg(
    fileUrl,
    initialCroppedAreaPixels
)

const response = await uploadImageToServer(croppedImageFile)

------
function getBase64(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve(reader.result);
    reader.onerror = error => reject(error);
  });
}

------
async function getCroppedImg(imageSrc, pixelCrop) {
  const image = await createImage(imageSrc)
  const canvas = document.createElement('canvas')
  canvas.width = pixelCrop.width
  canvas.height = pixelCrop.height
  const ctx = canvas.getContext('2d')

  ctx.drawImage(
    image,
    pixelCrop.x,
    pixelCrop.y,
    pixelCrop.width,
    pixelCrop.height,
    0,
    0,
    pixelCrop.width,
    pixelCrop.height
  )

  // As Base64 string 
  // return canvas.toDataURL('image/jpeg');

  // As a blob
  return new Promise((resolve, reject) => {
    canvas.toBlob(file => {
      resolve(file)
    }, 'image/jpeg')
  })
}

------
const uploadImageToServer = async ( file ) => {
  let formData = new FormData()
  formData.append('file', file)
  // console.log('formData', formData.get('file'))
  try {
    const res = await fetch(`${SERVER_URL}/upload-image`, {
      method: 'POST',
      body: formData
    })
    const response = await res.body.getReader().read()
    const result = JSON.parse(new TextDecoder('utf-8').decode(response.value))
    return result
  } catch (e) {
    console.log('error uploading image', e)
  }
}

**Comment by yongyi520** [comment]
Another question:

Does cloudinary rotate the image based on any other information?

Because I used piexifjs library to stripped away the exif information before upload and it still rotates the image

**Comment by yongyi520** [comment]
I figured out the problem:

Problem: When I send the file over to the server, there's no orientation data for cloudinary upload. 

Solution: Set EXIF orientation on the blob file before cloudinary upload

Example:
iOS selfie photos have `Orientation = 6`.
When I convert image to blob (after cropping) then uploaded to the server, orientation data is lost
If i set orientation as 6 on the EXIF data, the image will rotate correctly

**Comment by cloudinaraz** [comment]
@yongyi520 I'm really glad to hear that you've found the root cause for the loss of the orientation metadata when uploading the image to your server. Thanks for sharing!

In that case, you actually wanted to rotate the image based on the metadata information, and not ignore it. This is done automatically by our servers when the orientation data is indeed available.
The `angle: "ignore"` should be used when you want to achieve the opposite result of ignoring the orientation metadata, in case it exists, and disable the automatic rotation functionality.

I hope this clarifies the confusion here :)

**Comment by yongyi520** [comment]
Thank you for the insight on `angle: "ignore"` parameter. I will keep that in mind for the future!
