### ISSUE TITLE
Cloudinary delete not working

### ISSUE THREAD

**Issue by Enado95** [cloudinary/cloudinary_npm#299]
I tried an example based on the docs and was unsuccessful. I tried an example given in an issue #29   and was still unsuccessful. See my code below

```javascript
var cloudinary = require("cloudinary").v2;
require("dotenv").config();

cloudinary.config({
  cloud_name: process.env.CLOUD_NAME,
  api_key: process.env.CLOUD_API_KEY,
  api_secret: process.env.CLOUD_API_SECRET
});

const deleteimage = async () => {
  return await cloudinary.uploader.destroy(
    "folder/mrobompy9ci9xawtmvcv",
    { invalidate: true, resource_type: "raw" },
    function(err, res) {
      if (err) {
        console.log(err);
        return res.status(400).json({
          ok: false,
          mensaje: "Error deleting file",
          errors: err
        });
      }
      console.log(res);
    }
  );
};

deleteimage()
```

Response:
`{ result: 'not found' }`

**Comment by roeeba** [comment]
Hi @Enado95. Looking at your account and your logs, I see that you're asking for a resource of type `raw` while the resource is of type `image`. Please try changing it to `resource_type: "raw" ` and let me know if that works?

**Comment by Enado95** [comment]
Works like a charm. After revisiting the docs I do see the various resource [types](https://cloudinary.com/documentation/image_upload_api_reference#optional_parameters) Thanks a lot.

**Comment by roeeba** [comment]
Glad to hear :)

**Comment by glani** [comment]
it looks like it does not work for files uploaded using type 'auto'. I tried both node and python library the same answer 'not found'.  Python: cloudinary==1.16.0, node=1.14.0

**Comment by brian-cloudinary** [comment]
@glani the `auto` resource type is not a resource type supported by Cloudinary - rather, when uploading the resource, it would automatically categorize the asset as an image/video/raw file, and use the relevant `resource_type`. 

So, you cannot delete resources with the `auto` resource type. You would need to use the actual resource type returned in the response of the upload.
