### ISSUE TITLE
Can you transform image while upload?

### ISSUE THREAD

**Issue by Enado95** [cloudinary/cloudinary_npm#301]
Is it possible to transform image before final storage ?
Im using node.js

**Comment by brian-cloudinary** [comment]
Hi @Enado95, you can use the `raw_transformation` or `transformation` option when uploading an asset to transform it before it is stored.

```
cloudinary.v2.uploader.upload("https://res.cloudinary.com/demo/image/upload/sample.jpg", {raw_transformation: "w_300"}, console.log)
cloudinary.v2.uploader.upload("https://res.cloudinary.com/demo/image/upload/sample.jpg", {transformation: {width: 300}}, console.log)
```

Let me know if this works for you?

**Comment by Enado95** [comment]
How i would I get the image URL tho given i would just be uploading a new image? i have to upload it first then upload again to transform?

**Comment by roeeba** [comment]
@Enado95 There are two approaches for applying your transformations. The first is using [Incoming Transformations](https://cloudinary.com/documentation/upload_images#incoming_transformations). This approach applies your desired transformations on the original image that is uploaded to Cloudinary. Except for specific CDN level transformations like `f_auto`, most transformations are supported with incoming transformations.

The second, and most recommended, is using [Eager Transformations](https://cloudinary.com/documentation/upload_images#eager_transformations).
When you list your desired transformation/s by passing the eager parameter, your original image stays as-is, yet derived image/s are generated per your requested transformations. The relevant URLs with the transformation component are returned in the response, for each of the requested eager transformation.

You can then extract the transformed URL and save it in your database.
Alternatively, keep your current upload flow, without applying any transformations at this point.
Then, whenever you need to generate and embed a specific transformation into your page, you can use the `cloudinary.v2.url()` method, while adding the transformations parameters you would like to use. For example:

```
transformed_url = cloudinary.v2.url("<image_public_id>", {fetch_format: 'auto', crop: 'thumb', width: 200, height: 200, gravity: 'auto'});
console.log(transformed_url);
```

If you need additional help with any of the above, please open a support ticket at support@cloudinary.com.

**Comment by Enado95** [comment]
Okay thanks
