### ISSUE TITLE
ENOENT: No such file or directory, open 'my_video_name.mp4'

### ISSUE THREAD

**Issue by irajwani** [cloudinary/cloudinary_npm#305]
Hi, I do not think I should be facing an issue and I'm probably making a mistake somewhere but I followed the docs on how to upload videos for the Node.JS SDK very carefully and am stumped on what the problem is. I have configured my cloud name, api key, and secret globally in my node js project so I don't think this issue is permissions related. I just tried cloudinary(v2).uploader.upload(file,options,cb) and received the following error:

<img width="575" alt="Screenshot 2019-10-10 at 8 36 13 PM" src="https://user-images.githubusercontent.com/25965881/66584105-f1c31e80-eb9d-11e9-93cc-564b237a5121.png">

when running my node js project. (again, all my project does on the '/' route, it runs the uploadVid function and tries to upload the "lorem_video.mp4" file in the same directory.

<img width="660" alt="Screenshot 2019-10-10 at 8 36 03 PM" src="https://user-images.githubusercontent.com/25965881/66584078-e7088980-eb9d-11e9-9ecd-debb25c1b3d2.png">

**Comment by shirlymanor** [comment]
It seems that it doesn't find the video `lorem_video.mp4` in the directory. Can you try giving the all path e.g., `/Usera/imadrajwani/.../lorem_video.mp4`? Or just for testing try:

```
cloudinary.v2.uploader.upload("http://res.cloudinary.com/demo/video/upload/dog.mp4", 
        { resource_type: "video", public_id: "testVid" },
        function(error, result) { console.log(result); });
```

**Comment by irajwani** [comment]
Thank uuu. Providing the absolute path worked like a charm.

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
