### ISSUE TITLE
Uploading SVG data urls will result in an errno":-36,"code":"ENAMETOOLONG"

### ISSUE THREAD

**Issue by BioRodney** [cloudinary/cloudinary_npm#306]
SVG data urls are no longer recognized because the regex in isRemoteUrl doesn't take svg+xml as a mime type into account.

The following regex is used in isRemoteUrl: 
/^ftp:|^https?:|^gs:|^s3:|^data:([\w-]+\/[\w-]+)?(;[\w-]+=[\w-]+)*;base64,([a-zA-Z0-9\/+\n=]+)$/

To match SVG data urls it should probably be like this:
/^ftp:|^https?:|^gs:|^s3:|^data:([\w-]+\/[\w-]+(\+([\w-]+)?)?(;[\w-]+=[\w-]+)*;base64,([a-zA-Z0-9\/+\n=]+)$/
or like this
/^ftp:|^https?:|^gs:|^s3:|^data:([\w-]+\/[\w-+]+)?(;[\w-]+=[\w-]+)*;base64,([a-zA-Z0-9\/+\n=]+)$/

because the mime type for an SVG data url looks like this: 
data:image/svg+xml;base64,

The current regex will not match because of the + between svg and xml. This means that with the current code the data url for a SVG file is not seen as remote and the whole of the data url is being used as the name of the file.

**Comment by igy** [comment]
Hi Rodney,
Thanks for filing this - please give me a while to check the details and do some tests; if it checks out, it should be a quick change and we can add it to the SDK shortly.
-Stephen

**Comment by mikeulvila** [comment]
+1 having the same issue with svg.

**Comment by strausr** [comment]
isRemoteUrl() was updated in https://github.com/cloudinary/cloudinary_npm/commit/5c4504a7138b4b22674e4e3da4a00dc20fac6c57

**Comment by JLVilleminot** [comment]
Still not working for me on "cloudinary": "^1.20.0". The new regex on isRemoteUrl doesn't match SVG data urls, as you can see here : https://regex101.com/r/UYHjH6/1

**Comment by strausr** [comment]
My apologies @JLVilleminot you're correct. We're still working on this and we'll update as soon as it is resolved.

**Comment by thiag73** [comment]
Had this issue with 1.21.0, seems fixed in 1.23.0

**Comment by JLVilleminot** [comment]
@thiag73 You're right, it's working on 1.23.0. Thanks for pointing it out !

**Comment by igy** [comment]
@thiag73 Thanks for pointing this out.
@JLVilleminot, this was resolved in #418 but we didn't have it linked with this issue correctly and forgot to close it - sorry about that

If you're still encountering issues with v1.23.0 or later, please open a new issue with the details
