### ISSUE TITLE
Getting latest version when using cloudinary.url()

### ISSUE THREAD

**Issue by AdamGerthel** [cloudinary/cloudinary_npm#307]
I'm using `cloudinary.url(remote_id, options)` when getting image urls. However, I'd sometimes like to _not_ get the cached version but instead get the latest version of the image. I can't seem to find any documentation for `cloudinary.url()` and the options that are available on the options object.

Is this possible to do?

**Comment by shirlymanor** [comment]
@AdamGerthel It depand how you update your image. You can read more about it here: https://support.cloudinary.com/hc/en-us/articles/202520852-How-can-I-update-an-already-uploaded-image-

**Comment by AdamGerthel** [comment]
@shirlymanor I am updating the image by using the same id (as mentioned in your link) and I'm getting a new version number back. But I'm using `cloudinary.url()` from this node package to make it easier to construct a URL to the image that includes certain parameters (width etc.). However, the resulting URL does not seem to use the latest version. Is it possible to include the version number as part of the options in `cloudinary.url()`?

**Comment by shirlymanor** [comment]
Can you contact us at support@cloudinary.com with your cloud name? we can tweak your account to invalidate the unversioned URL.

**Comment by AdamGerthel** [comment]
Actually, I just found it by going through the code of this repository. Apparently, it's possible to pass the version as an field in the options param: `cloudinary.url('insert-id', { version: 'insert-version-number'})`

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
