### ISSUE TITLE
`SameSite` and `Secure` cookies attribute. Warning Chrome

### ISSUE THREAD

**Issue by Maxfurry** [cloudinary/cloudinary_npm#308]
It seems that the Chrome team has started notifying of deprecation of a future feature in the delivery of cookies with the cross-site request.

I have been having the warning showing on my console and decided to bring to the attention of the team if it is not already known.

**Comment by shirlymanor** [comment]
Thank you @Maxfurry for bringing it to our attention.

**Comment by Maxfurry** [comment]
@shirlymanor Would appreciate it if I am notified when the update is made

**Comment by haithamelmengad** [comment]
+1

**Comment by aleksandar-cloudinary** [comment]
Hi @Maxfurry, @haithamelmengad - The update to set SameSite=None has been made to the relevant cookies set by Cloudinary. I'd suggest logging out and clearing any existing cookies and then logging back in again. This will ensure the cookies are with the updated attribute thus not producing the warning anymore.

**Comment by Maxfurry** [comment]
@shirlymanor <https://github.com/shirlymanor> Thanks a lot for the update.

**Comment by sitrucp** [comment]
Not seeing cookies with the updated attribute.

**Comment by roeeba** [comment]
@sitrucp Can you please let us know which of Cloudinary's cookies you see don't have the attribute?

**Comment by sitrucp** [comment]
__cfruid
__utma
__utmc
__utmz
_ga
_mkto_trk

**Comment by marcnjaramillo** [comment]
As of February 24, I’m still seeing the warning in the console. 

@aleksandar-cloudinary mentioned logging out and clearing cookies and then logging back in again. Does this mean assets that had been stored prior to the update in the code are not being automatically updated with the appropriate flag and are still sending out older cookies? I’m using images that are accessed from another Cloudinary account, so it could be potentially problematic if everyone has to manually reset something before seeing the update.

**Comment by sitrucp** [comment]
Still also seeing Cloudinary cookie SameSite warnings. Only two cookies
have SameSite values, rest are blank:

__cfduid Lax
__cfruid None
__utma blank
__utmb blank
__utmc blank
__utmt blank
__utmz blank
_ga blank
_gid blank
_mkto_trk blank

**Comment by aleksandar-cloudinary** [comment]
Responses from res.cloudinary.com (that is used to deliver resources) do not set cookies so there isn't anything needed for this case specifically.

If you've accessed cloudinary.com (or support.cloudinary.com etc) then there will be some analytics and 3rd party cookies set. The session and other critical cookies to Cloudinary functionality and Widgets have been updated to have a SameSite attribute set, but there are other non-critical cookies that are still being updated. The 3rd party cookies should be handled externally but I would also expect those to be updated too.

If you already have cookies set from cloudinary.com and load resources from res.cloudinary.com then the *.cloudinary.com cookies would be sent as part of the request and therefore would be why you're seeing the warning on a page that displays resources.

**Comment by marcnjaramillo** [comment]
Thanks for the quick response! I haven’t set up a Cloudinary account myself, so this new to me. I only caught it because I’m using some image assets that come from another Cloudinary account and saw the warning (but I will he setting up my own account soon). I wanted to be sure I understood what was going on.

**Comment by sitrucp** [comment]
Ok, I had Cloudinary dashboard open, which accounts for rest of cookies without SameSite value. After closing it, my site using Cloudinary API then shows only one cookie __cfduid with SameSite 'Lax' and no Chrome SameSite warnings.
