### ISSUE TITLE
Missing types on rv2.api.resources_by_ids()

### ISSUE THREAD

**Issue by alexbjorlig** [cloudinary/cloudinary_npm#315]
Resources by ids have the return type `any` 

```
function resources_by_ids(public_ids: string[], options?: AdminAndResourceOptions, callback?: ErrorCallBack): Promise<any>;
```

Not super useful 🤷🏾‍♂️

**Comment by shirlymanor** [comment]
Thank you for the feedback!
We are checking with our team to set a type.

**Comment by dauledk** [comment]
When you add the interfaces, make sure to think about documentation as well. Would be awesome to have the documentation at your fingertips, when using the typscript SDK.

Something like this: 

```typescript
declare interface CloudinaryResource {
    /**
     * Defines the width of an image in pixels.
     * @type {number}
     * @memberof CloudinaryResource
     */
    width?: number;
}
```

Gives your intellisense like this in Code:

![Screenshot 2019-11-19 at 22 00 53](https://user-images.githubusercontent.com/9967422/69186104-2ff61b00-0b18-11ea-82c3-b589d8045fd0.png)

Would be super helpful 🔥

**Comment by strausr** [comment]
@alexbjorlig Updated on our latest release. Please see #358
