### ISSUE TITLE
Missing name property in errors

### ISSUE THREAD

**Issue by tzivz** [cloudinary/cloudinary_npm#316]
We ran into an issue with the Cloudinary code where an error is causing an uncaught promise rejection in serverless code.

We tracked the issue down to Serverless' logging code which expects errors to have a `name` property. I think the Serverless code is reasonable considering that JS `Error` prototypes have `name`.

I propose adding a `name` property to errors. I ran into this in the `uploader.js` code. I'm not sure where else this might be an issue.

**Comment by igy** [comment]
Thanks for the details; let me check, but this seems like a reasonable request to me - I've asked one of my colleagues to check the PR

**Comment by igy** [comment]
Apologies for the delay; I see #317 was merged, so closing this issue - thanks!
