### ISSUE TITLE
Typescript upload result type

### ISSUE THREAD

**Issue by outerlook** [cloudinary/cloudinary_npm#319]
Hi! I highly appreciate types were added recently, but could I ask for some improvements? Results and error type on callback are missing. 

currently I`ve being doing (in a simplfied manner) this:
```
const uploadStreamCloudinary = () => {
  return new Promise<{public_id: string} | undefined>((resolve, reject) => {
    cloudinary.v2.uploader.upload_stream("",(err, image: {public_id: string}) => {
      if (err) resolve();
      else resolve(image)
    })
  })
}
```

but it is error prone. Errors like #151 could be avoided.
Could I kindly ask if it's possible for that typings to be added, or there if there are some complications on that?

**Comment by roeeba** [comment]
Hi, @outerlook. Thank you for your input. We will look into it and update.

**Comment by strausr** [comment]
@outerlook  Please see our latest release. Upload result was updated on types #360
