### ISSUE TITLE
Wrong the link that support typescript

### ISSUE THREAD

**Issue by Silver-birder** [cloudinary/cloudinary_npm#323]
I access to the [page](https://www.npmjs.com/package/cloudinary#typescript).

> 🎉New 🎉TypeScript support was just added. Check out the [declaration file]
(https://github.com/cloudinary/cloudinary_npm/types/index.d.ts).
-> Not Found

I think below is correct.
https://github.com/cloudinary/cloudinary_npm/blob/master/types/index.d.ts

**Comment by aleksandar-cloudinary** [comment]
Thanks for reporting @Silver-birder. I've added a PR - https://github.com/cloudinary/cloudinary_npm/pull/324

**Comment by asisayag2** [comment]
Fixed. 
Thanks @Silver-birder for raising this
