### ISSUE TITLE
Why is typescript included as dependency ?

### ISSUE THREAD

**Issue by Marsup** [cloudinary/cloudinary_npm#326]
Hi,

Is there any reason why you include the compiler in your normal dependencies? Shouldn't it be in your devDependencies?

Thanks.

**Comment by roeeba** [comment]
Hi @Marsup. Thanks for bringing this up. We will check it out.

**Comment by TrySound** [comment]
@roeeba There is PR https://github.com/cloudinary/cloudinary_npm/pull/335

**Comment by strausr** [comment]
@TrySound Thank you for the PR closing this request
