### ISSUE TITLE
No TypeScript declarations for api v1

### ISSUE THREAD

**Issue by alexeychikk** [cloudinary/cloudinary_npm#328]
No TypeScript declarations for api v1, for example:
`Property 'config' does not exist on type 'typeof import("cloudinary")'`

**Comment by roeeba** [comment]
Hi @alexeychikk. Types were added to v2 and are not supported on v1. If TS is required in your app and If possible, I recommend upgrading to v2.

**Comment by alexeychikk** [comment]
@roeeba unfortunately there is no documentation so migration would require a lot of testing stuff out. Last time I tried API v2 to upload stream it just didn’t work out so I stick to API v1.

**Comment by afkir01** [comment]
@alexeychikk , This solved the issue for me:

import * as cloudinary from 'cloudinary/lib/v2';
