### ISSUE TITLE
Upload multiple images from memorystorage

### ISSUE THREAD

**Issue by OskarAhl** [cloudinary/cloudinary_npm#341]
Hi, i'd love to use cloudinary but i'm struggling with the documentation.

I'm using a Multer.MemoryStorage to store the image buffers in memory and a async function to upload the images. It works well for a single image. For multiple images it only uploads only one of the images.

```javascript
 function uploadToCloudinary(fileBuffer, options) {
     return new Promise((resolve, reject) => {
        cloudinary.v2.uploader
           .upload_stream(options, (error, result) => {
                if (error) {
                     reject(error)
                } else {
                     resolve(result)
                }
             })
             .end(fileBuffer)
          })
}

const cloudinary_urls = []
for (let i = 0; i < req.files.length; i++) {
    const file_ = req.files[i]
    const cloudinary_res = await uploadToCloudinary(file_.buffer, { public_id: 'my_picture' })
    cloudinary_urls.push(cloudinary_res.secure_url)
}

```

I'd appreciate any help with this, thanks!

**Comment by aditimadan-Cloudinary** [comment]
Are you passing the same public_id for all the images? From the code you shared looks like the public_id is constant and if your account setting is to overwrite/replace image then it will just overwrite the old one and in the end you will just have the last image on Cloudinary.

**Comment by OskarAhl** [comment]
@aditimadan-Cloudinary Ahh that's it! Thank you 🙏
