### ISSUE TITLE
Photos cannot be downloaded with the function of private_download_url

### ISSUE THREAD

**Issue by huanglong-zz** [cloudinary/cloudinary_npm#37]
I've been using cloudinary for a long time and everything is fine. And it's also ok to upload private photos and pdfs. 

But today when I tried to download the private photos, something went wrong.

```
var url = cloudinary.utils.private_download_url(publicid);
```

The url I get was something like: 

```
https://api.cloudinary.com/v1_1/myappname/image/download?timestamp=1417560245&public_id=mfzmfjhzmcnh2ksp2qs1&signature=4e857d76e3b773b6cbb3129fffed185d725854c8&api_key=616622821755xxx
```

But when I put it in the browser, I got:

```
{
  "error": {
    "message": "Resource not found - mfzmfjhzmcnh2ksp2qs1"
  }
}
```

What the problem could be?
But the mfzmfjhzmcnh2ksp2qs1 is there of course. I saw it in the backend of cloudinary console media_library.

**Comment by duplich** [comment]
Hi there, I am getting the same error, how did you solve this?

**Comment by taragano** [comment]
Can you please share some more information regarding the issue you're experiencing? 
Can you please share a snippet of your code which can reproduce this?

**Comment by duplich** [comment]
I am using PHP Library downloaded from Github just 2 days ago. 

```
require('assets/php/cloudinary/src/Cloudinary.php');
require('assets/php/cloudinary/src/Uploader.php');
require('assets/php/cloudinary/src/Api.php');

$date = new DateTime();

\Cloudinary::config(array( 
  "cloud_name" => "myCloudName", 
  "api_key" => "mySecretKey4325223216" , 
  "api_secret" => "mySecretEeohPFC0IRI0vEDHdQ"
));

function dl_private($public_id){
	$_utils = new \Cloudinary();
	$dl_url = $_utils -> private_download_url($public_id, 'jpg', array('atachment' => true));
	return $dl_url;
}
```

I am copying the public_id from my working listing request. I manually pass parameter $public_id to dl_private function and as the return link I get 

my url looks like: 

`https://api.cloudinary.com/v1_1/croative/image/download?timestamp=1482243882&public_id=profile_images%2FBild_Anzug_u7zghw&format=jpg&signature=d80e2fee1110053c6a1b26c09059d22374d71962&api_key=246943252232167`

and my result as following: 
```
{
  "error": {
    "message": "Resource not found - mfzmfjhzmcnh2ksp2qs1"
  }
}
```

just for comparison following function with the same config works as expected 

```
function dl($public_id){
	$_utils = new \Cloudinary();
	$id = $public_id;
	$zip_url = $_utils -> download_zip_url(array('public_ids' => $id, 'resource_type' => 'image'));
	return $zip_url;
}
```

**Comment by taragano** [comment]
Thank you for sharing this additional information.

I'm not sure whether some of the values here were changed by you for this forum or not.
Specifically, I don't see a resource in your account with the public ID of `mfzmfjhzmcnh2ksp2qs1`.

Also, from the URL you shared, it seems that you were trying to get the resource with the public ID of `profile_images/Bild_Anzug_u7zghw`, and this one is not a private resource (i.e., its `type` is `upload`).
The `private_download_url` is relevant only for private resources (i.e., resources which their `type` is `private`).

I hope this helps.

**Comment by duplich** [comment]
Man, that makes perfect sense now :)
Thanks for your help

**Comment by taragano** [comment]
I'm glad I could help :)
