### ISSUE TITLE
Typescript error on `Cloudinary.utils.sign_request`

### ISSUE THREAD

**Issue by ian** [cloudinary/cloudinary_npm#397]
## Describe the bug in a sentence or two.
…

Property 'sign_request' does not exist on type 'typeof utils'

## Issue Type (Can be multiple)
[] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[x] Other (Specify)

Typescript

## Steps to reproduce

Add this to a cloudinary.ts file and build it:

```
const Cloudinary = require('cloudinary').v2
Cloudinary.utils.sign_request
```

## Versions and Libraries (fill in the version numbers)
Cloudinary_NPM SDK version
Node - v12.13.1
NPM - 6.12.1

## Config Files (Please paste the following files if possible)
Package.json

"cloudinary": "^1.21.0",

**Comment by shirlymanor** [comment]
Can you please elaborate on what you are trying to achieve?
If you want to generate a signed URL. you can use something like:
cloudinary.utils.url("sample",{sign_url:true})

**Comment by ian** [comment]
Not sure how familiar with Typescript you are.  The code I have works fine in javascript, the functionality of the function `sign_request` is fine.  You just have an issue with your library and typescript compliance, which is causing errors in TS builds and ultimately failing deploys.

**Comment by strausr** [comment]
@ian Thanks for bringing this to our attention. I fix will be available in our next release.

**Comment by strausr** [comment]
@ian please let us know if you have any issues following the release
