### ISSUE TITLE
How to subscribe to finish event in cloudinary.uploader.upload_stream ?

### ISSUE THREAD

**Issue by skotchio** [cloudinary/cloudinary_npm#43]
I need to use event subscription instead of callback when using `cloudinary.uploader.upload_stream`:

    var stream = cloudinary.uploader.upload_stream(function(result) { 
        console.log(result);
    });

Something like the following:

    var stream = cloudinary.uploader.upload_stream();
    stream.on('finish', function (result) {
       console.log(result)
    });

But it seems `finish` event does not exists because console.log doesn't get executed.

**Comment by gingermusketeer** [comment]
From the codebase it does not look like this is supported. You might be able to do something like

```js
var stream = cloudinary.uploader.upload_stream(function(result){
  stream.emit('finish', result)
});
stream.on('finish', function (result) {
   console.log(result)
});
```

or even

```js
var stream = cloudinary.uploader.upload_stream(stream.emit.bind(stream, 'finish'));
stream.on('finish', function (result) {
   console.log(result)
});
```

**Comment by tocker** [comment]
@gingermusketeer that looks like a nice solution!
@skotchio, did this meet your needs?

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
