### ISSUE TITLE
Cloudinary Upload Widget response types 

### ISSUE THREAD

**Issue by vishal-chauhan97** [cloudinary/cloudinary_npm#452]
Hey guys,
Thanks for making this awesome product, we have been using it for years now.
We are upgrading to cloudinary upload widget 2, we use react + typescript for our frontend application.
We are facing an issue for creating a type for the response we receive from the widget.
I have looked at the docs and I did not find anything related to types in there.
How do I get the types for the response type.

We used this type for cloudinary widget v1

```
type CloudinaryResult = {
	bytes: number;
	created_at: string;
	etag: string;
	format: string;
	grayscale: boolean;
	height: number;
	illustration_score: number;
	image_metadata: {
		Author: string;
		Colorspace: string;
		CreatorTool: string;
		DPI: string;
		ExifImageHeight: string;
		ExifImageWidth: string;
		JFIFVersion: string;
		Orientation: string;
		ResolutionUnit: string;
		XMPToolkit: string;
		XResolution: string;
		YResolution: string;
	};
	original_filename: string;
	pages: number;
	path: string;
	placeholder: boolean;
	public_id: string;
	resource_type: string;
	secure_url: string;
	semi_transparent: boolean;
	signature: string;
	tags: string[];
	length: number;
	thumbnail_url: string;
	type: string;
	url: string;
	version: number;
	width: number;
};
```

`export type CloudinaryError = {
	message: string;
};`

**Comment by leptians** [comment]
Hi @vishal-chauhan97,

Thank you for your feedback and happy to hear that 👍 
Upload Widget v2 was refactored and behaves very differently with Upload Widget v1. 
The responses would varies depending on the media that you are uploaded. 
Is there any reason why you would like to mapped all the types of the response?

Regards,
Erwin Lukas

**Comment by vishal-chauhan97** [comment]
@leptians thanks for the reply, sorry for the late resposne.
We just moved on to the Upload Widget V2 and I made some basic types for the response by noticing different types of responses I got from widget.
If anyone comes to this post in the future I am adding my basic types for the widget v2 version 
`type CloudinaryResult = {
	info: {
		id: string;
		batchId: string;
		asset_id: string;
		public_id: string;
		version: number;
		version_id: string;
		signature: string;
		width: number;
		height: number;
		format: string;
		resource_type: string;
		created_at: Date;
		tags: string[];
		bytes: number;
		type: string;
		etag: string;
		placeholder: boolean;
		url: string;
		secure_url: string;
		access_mode: string;
		original_filename: string;
		path: string;
		thumbnail_url: string;
	};
	event: string;
	uw_event: boolean | undefined;
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	data: any;
};`
`type CloudinaryError = {
	status: string;
	statusText: string;
};`
