### ISSUE TITLE
can't use the API when public_id contains a space (got 404)

### ISSUE THREAD

**Issue by jbdemonte** [cloudinary/cloudinary_npm#457]
## Bug report for Cloudinary NPM SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.

404 when public_id contains a space

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] Performance - Performance issues
[x] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce

upload a media and set a public id with a space
try to use `cloudinary.api.resource` on it

=> works well when public_id does not contains spaces.

```
const cloudinary = require('cloudinary').v2;

cloudinary.config({
  cloud_name: 'xxx',
  api_key: 'xxx',
  api_secret: 'xxx',
});

async function main() {
  const public_id = "PARTNERS/EMERGENCY NGO/Marja_ENG_LQ_zxy0bi";
  const data = await cloudinary.api.resource(public_id);
  console.log(data)
}

main().catch(console.error)
````

## Error screenshots

<img width="1025" alt="Capture d’écran 2020-11-13 à 21 44 14" src="https://user-images.githubusercontent.com/787639/99119490-99105180-25f9-11eb-8b3d-03e5f3fd0f7b.png">

## Versions and Libraries (fill in the version numbers)
Cloudinary_NPM SDK 1.23.0
Node - 14.6.0
NPM - 6.14.7

## Config Files (Please paste the following files if possible)
`"cloudinary": "^1.23.0",`

**Comment by aleksandar-cloudinary** [comment]
Hi @jbdemonte. Thanks for your message.

Looking at our logs, I've found the asset you are trying to retrieve. The reason it's not working for you isn't related to the space character, but rather the asset in question is of `resource_type` "video" and not an "image". By default, when you call API methods, Cloudinary SDKs set default values of the optional parameters, including `resource_type`. In this case, you are trying to retrieve the details of a "video" but not specifying the `resource_type` parameter in your method call and it defaults to "image". We can verify this by looking at the "href" field from the request which has `/image/upload/`. As you don't have an image with that public_id in your account, you get the 404 error.

May I please ask you to replace the following line -

```
const data = await cloudinary.api.resource(public_id);
```

With:

```
const data = await cloudinary.api.resource(public_id, {resource_type: "video"});
```

Please try that and let me know if it works for you.

**Comment by jbdemonte** [comment]
omg!

I did tons of test, with those parameters in the options: resource_type, format, version, secure, sign_url 
And I missed that, my check with a non spaced name file was an image... so I though this was about the space

Thanks for your help.
