### ISSUE TITLE
Uploader.upload params in different orders

### ISSUE THREAD

**Issue by molinto** [cloudinary/cloudinary_npm#46]
In https://github.com/cloudinary/cloudinary_npm/blob/master/src/uploader.coffee, upload(fileToBeUploaded, callback, options)  but in the examples its upload(fileToBeUploaded, options, callback).  

Examples: 
https://github.com/cloudinary/cloudinary_npm/blob/master/samples/basic/basic.js
https://github.com/cloudinary/cloudinary_npm/blob/master/samples/photo_album/controllers/photos_controller.js

Confused!

**Comment by jamesryanbell** [comment]
The reason for the difference here is that the examples use the v2 version of the library, caught me out too
