### ISSUE TITLE
snyk security issue - update lodash to latest 

### ISSUE THREAD

**Issue by eran10** [cloudinary/cloudinary_npm#480]
can you please update lodash to the latest version (4.17.21)
so that snyk security alert will be fixed for this package?

**Comment by patrick-tolosa** [comment]
hey @eran10 

This library currently has an upgrade caret for lodash, we're using version
`^4.17.11` - meaning the latest `4.x version` but no less than 4.17.

Can you please share the synk report that demonstrates this issue?

A possible reason might be that your yarn/package lock files captured an older version of the lodash, which is now marked as vulnerable

**Comment by eran10** [comment]
yes i think you are right, i will re-create our yarn lock file, thanks
