### ISSUE TITLE
Typescript api_url() result type

### ISSUE THREAD

**Issue by immortalObject** [cloudinary/cloudinary_npm#482]
`v2.utils.api_url()` is a synchronous function that returns `string`, but the types declaration [states](https://github.com/cloudinary/cloudinary_npm/blob/0ac8957c97767da49aad061452cd607d9f66b47e/types/index.d.ts#L709) that it returns `Promise<any>`

**Comment by roeeba** [comment]
Hi @immortalObject , thanks for bringing this up. I've opened an internal ticket to fix it, and we'll update here once done.

**Comment by patrick-tolosa** [comment]
This was very recently merged.

Thanks @immortalObject for the PR!
