### ISSUE TITLE
CLOUDINARY_URL not working with Nestjs.

### ISSUE THREAD

**Issue by abrarniyazi** [cloudinary/cloudinary_npm#484]
I am using coudinary with `multter-store-cloudinary` npm package and it was working perfectly fine until recently. 
To set the configuration parameters I was setting it to enviornment varialble CLOUDINARY_URL. But it seems like now it's not picking up credentials from this variable. I didn't change anything in the relevant code and also I updated some other packages with not directly related. 
I am getting below error:

`Must supply api_key`

 

I already checked the env variable. It does contain the value. If I adding config in directly then it works but I would like to the way it was using CLOUDINARY_URL env variable. 

Any help would be appreciated. Thanks 

```
"cloudinary": "^1.25.1",
"multer-storage-cloudinary": "^4.0.0",
```

**Comment by patrick-tolosa** [comment]
Hey @abrarniyazi 

`multer-storage-cloudinary` is a tool created by the community and is not directly maintained by Cloudinary.
I think it's best to open this issue in their github and see if they can provide additional information.

From this package's point of view, nothing was changed in how the configuration is read from the ENV variables.

**Comment by abrarniyazi** [comment]
Hi @patrick-tolosa thank for the reply. Actually the reason I posted here is because I suspected that it might be because of Cloudinary package as nothing was changed in `multer-storage-cloudinary` package and it was working fine. Thanks I will dig into this more and try to find where is the exact problem.

**Comment by aleksandar-cloudinary** [comment]
Hi @abrarniyazi
If you haven't already, what you can try is to log the value of the CLOUDINARY_URL environment variable in the code where you are using `multer-storage-cloudinary` rather than in the command line directly. It could be that the code is run under a different user and the environment variable is not accessible.

**Comment by abrarniyazi** [comment]
Hi @aleksandar-cloudinary  thanks for your suggestion. I did print the environment variable a step before (during authentication) and it was logged just fine. But got error next.


`[Nest] 76973   - 04/03/2021, 2:04:39 PM   [NestApplication] Nest application successfully started +3ms
cloudinary://23479663830628:A9b3X1lJthxBN0y7xiFQP0uqv5o@dybvt2bml
[Nest] 76973   - 04/03/2021, 2:04:42 PM   [ExceptionsHandler] Must supply api_key +3039ms`

**Comment by aleksandar-cloudinary** [comment]
Hi @abrarniyazi,

Thanks for trying that. Please note that the CLOUDINARY_URL or API SECRET directly should never be shared publicly.

I have edited your response to redact it but this Edit history is available publicly.

I would recommend you to log into your account, go to your Settings -> Security tab -> bottom of the page and disabling the old API Key/Secret pair and generating a new one. Then using the new key-pair in your website/app.

This is to ensure that no one is able to use the credentials you shared in this thread to perform API calls into your account.

**Comment by abrarniyazi** [comment]
Hi @aleksandar-cloudinary  thanks for your concern but I had already edited it by replaceing random number and characters. It did look like a real key but it wasn't. 😀

Please let me know if you have any suggestion for my original problem.

**Comment by noushad-pp** [comment]
For anyone looking for the same error, I had the same issue.
It happened because, env variable was not available when the cloudinary storage object is being created, even though trying to log the value shows the correct value. This might be caused due to using `ConfigService` from NestJs and the asynchronous behaviour of the ConfigService injecting the env variables.

The fix I used was to explicitly specify `dotenv` config method to load the env variables before any other modules are imported, even though NestJs use dotenv to load variables from `.env` file.

```ts
// main.ts
import { NestFactory } from '@nestjs/core';
import { config } from 'dotenv';

// NB: Order of the config method invocation is important, it SHOULD BE BEFORE any other modules import lines
// This ensure env variables are injected before any other modules loaded. Otherwise there might be delay in
// injecting these variables to other modules if ConfigService is used due to its asynchronous injection nature.
// Eg: Cloudinary need CLOUDINARY_URL to be present when storage is initialised. But when initialised outside
// controller or service, the env variable might not be present during invocation. eg: categories.controller.ts
config();

// eslint-disable-next-line import/first
import { AppModule } from './app.module';


async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  // ... other stuff
  await app.listen(process.env.PORT || 5001);
}
bootstrap();
```

```ts
// some-service.ts
import { Body, Controller, Post, UploadedFile, UseInterceptors } from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import { v2 as cloudinary } from 'cloudinary';
import { CloudinaryStorage } from 'multer-storage-cloudinary';

// cloudinary automatically reads CLOUDINARY_URL from process.env
const cloudinaryStorage = new CloudinaryStorage({
  cloudinary,
  params: {
    folder: 'uploads/images',
  },
});

@Controller('upload')
export class UploadController {
// ...constructor and other paths

@Post()
  @UseInterceptors(
    FileInterceptor( 'image',
      { storage: cloudinaryStorage }
    )
  )
  create(@ UploadedFile() image, @Body payload: any) {
 // console.log(image.path);
}

```
