### ISSUE TITLE
error code 400: "live is not currently supported with async"

### ISSUE THREAD

**Issue by gianlucadifrancesco** [cloudinary/cloudinary_npm#485]
Hi everyone!
I wanted to report a problem: whenever I try to use **upload_stream** to upload a video **bigger than 40MB** (even with **`async: true`**) I always get the same error and can't figure out what the problem is.

## Versions
Cloudinary_NPM SDK - v1.25.1
Node - v14.15.4
NPM - v7.5.6

## Steps to reproduce
I'll share with you how I came to this error, even if there are a couple of "useless" steps:

**1.** Define an "upload_stream" function like this:
```
const uploadStream = v2.uploader.upload_stream(
      {
        upload_preset: '...',
        resource_type: 'video', // Couldn't find this in type definitions, but it's mandatory for videos!
        format: 'mp4',
        public_id: '...'
      },
      (err, result) => { /* callback */ },
);
```
**2.** Get a "Readble stream" of a video and give the pipe (in my case I use Multer and I have to convert the buffer from **req.file.buffer** to a readble stream):
```
Readable.from(req.file.buffer).pipe(uploadStream);
```
**3.** Try to upload a **video larger than 40MB**. Here the following error is thrown:
```
{
  message: 'Video is too large to process synchronously, please use an eager transformation with eager_async=true to resolve',
  name: 'Error',
  http_code: 400
}
```
**4.** Now, if I put "**eager_async**" to true, **it does nothing and the same error appears**.
BUT, if I put "**async**" to true the error changes!
```
const uploadStream = v2.uploader.upload_stream(
      {
        upload_preset: '...',
        resource_type: 'video',
        format: 'mp4',
        async: true, // New
        public_id: '...'
      },
      (err, result) => { /* callback */ },
);
Readable.from(req.file.buffer).pipe(uploadStream);
```
**5.** Now, if I try to upload the same video, **the following error appears instead**:
```
{
  message: 'live is not currently supported with async',
  name: 'Error',
  http_code: 400
}
```

What's the meaning of this error?

I have the free plan and I know the limit of video size is 100MB, but I was trying to upload a ~60MB video and this error always appears.
Does anyone have some information about this? What am I doing wrong?
I spent hours searching about this specific error but I couldn't find anything, even on Cloudinary forums 😕

Sorry for the long description and thanks in advance!

**Comment by aditimadan-Cloudinary** [comment]
Can you please share the cloud name and upload preset that you are using and I will be able to check the logs.
If privacy is a concern then please raise a support request here with the details- https://support.cloudinary.com/hc/en-us/requests/new

**Comment by gianlucadifrancesco** [comment]
Hi @aditimadan-Cloudinary, thank you for your immediate response!
I've just submitted the request, referring to this issue and providing the cloud name and upload preset.
Thanks in advance!

**Comment by gianlucadifrancesco** [comment]
Just wanted to update after talking to the support:
- The error "_live is not currently supported with async_" was caused by the combination of `Live broadcast=false` and `async=true`.
- `async=true` was not needed and had to be removed. The correct setting was `eager_async=true` only.
- The error "_Video is too large [...] use eager_async=true_" continued to appear **because I was putting `format: 'mp4'`**, which is an "incoming transformation", which has the limit of 40MB for free plans and 100 MB for paid plans.
- After removing `format: 'mp4'` it worked!
- In case I wanted to convert to mp4 (or make any transformation to) videos larger than 40MB, I'd have to set the following instead: **`eager: { format: 'mp4' }`**. This setting will store the original video without conversion/processing, but it will eventually provide the link to the converted/processed mp4 video.

Amazing support anyway, thank you so much! 😃
