### ISSUE TITLE
Unable to use upload_prefix without https

### ISSUE THREAD

**Issue by MaSpeng** [cloudinary/cloudinary_npm#486]
## Bug report for Cloudinary NPM SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
If you try to use a `upload_prefix` without `https:`, the SDK still expects `https`.

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] Performance - Performance issues
[x] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce
- Provide the credentials using the  `CLOUDINARY_URL` environment containing the query parameter `upload_prefix` using the scheme `http` instead of `https`.
- Try to upload a file using the SDK

## Error screenshots
```
TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
    at new ClientRequest (_http_client.js:155:11)
    at Object.request (https.js:313:10)
    at post (/workspace/node_modules/cloudinary/lib/uploader.js:484:28)
    at call_api (/workspace/node_modules/cloudinary/lib/uploader.js:451:16)
    at Object.upload (/workspace/node_modules/cloudinary/lib/uploader.js:49:10)
    at Object.upload (/workspace/node_modules/cloudinary/lib/utils/index.js:1177:21)
    at FileService.uploadFile (/workspace/dist/apps/quiz-calendar/backend/webpack:/libs/files/backend/domain/src/lib/service/file.service.ts:83:53)
    at FileService.create (/workspace/dist/apps/quiz-calendar/backend/webpack:/libs/files/backend/domain/src/lib/service/file.service.ts:25:31)
    at FileController.create (/workspace/dist/apps/quiz-calendar/backend/webpack:/libs/files/backend/feature-files/src/lib/controller/file.controller.ts:37:43)
    at /workspace/node_modules/@nestjs/core/router/router-execution-context.js:38:29 {
  code: 'ERR_INVALID_PROTOCOL'
}
```
## Browsers (if issue relates to UI, else ignore)
[ ] Chrome
[ ] Firefox
[ ] Safari
[ ] Other (Specify)
[ ] All

## Versions and Libraries (fill in the version numbers)
Cloudinary_NPM SDK version
Node - 14.15.0
NPM - 6.15.8

## Config Files (Please paste the following files if possible)
Package.json

## Repository
If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by victorli-cloudinary** [comment]
Hi @MaSpeng , do you have a specific use case that requires using http instead of https? It is intended behavior that we only allow https for this.

**Comment by MaSpeng** [comment]
Hi @victorli-cloudinary, yes indeed we currently have exactly this use case where we have to communicate using http instead of https.

Regarding the intended behavior, I was able to identify multiple spots where the SDK evaluates if it has to use http or https based upon the configured `upload_prefix`, for example, the current one which is faulty:

https://github.com/cloudinary/cloudinary_npm/blob/518c0e5a0e07f4a39ae730e28a4436a5e348217d/lib/uploader.js#L10

On lines 10-11 you see the evaluation of which one has to be used.

The same evaluation can also be found here: https://github.com/cloudinary/cloudinary_npm/blob/722d804cb94a204d5e0c4eae2abbf00cccab74f7/lib/api_client/execute_request.js#L3

**Comment by MaSpeng** [comment]
Since my pull request which addresses the issue has been merged this can now be closed.

Just a follow-up question, when is the next release planned?

**Comment by patrick-tolosa** [comment]
Thanks for the issue, and the PR @MaSpeng  !

The next release is planned for this coming Sunday, April 25th.

**Comment by MaSpeng** [comment]
@patrick-tolosa Thanks from me too. Glad I could help.

**Comment by patrick-tolosa** [comment]
@MaSpeng you're absolutely right, the release was delayed due to internal reasons, we hope to release it early next week.

**Comment by patrick-tolosa** [comment]
Hey @MaSpeng - We've just released a new version of the Node SDK, please let us know if there are any issues.
