### ISSUE TITLE
Module '"cloudinary"' has no exported member 'config'.ts(2305) Typescript

### ISSUE THREAD

**Issue by tobslob** [cloudinary/cloudinary_npm#491]
## Error screenshots
![image](https://user-images.githubusercontent.com/45825009/120225570-60566380-c23d-11eb-9572-366dc68ee41c.png)

## Versions and Libraries
Cloudinary_NPM SDK version
NPM - 1.25.2

**Comment by tobslob** [comment]
Solved.

```
declare module 'cloudinary' {
  export function config(conf: ConfigOptions);
}
```

**Comment by roeeba** [comment]
Thanks for the update, @tobslob . Closing.

**Comment by yilmazbingo** [comment]
@tobslob Can you please show how you implemented cloudinary set up in typescript. I could not find it anywhere :(

**Comment by tobslob** [comment]
@yilmazbingo have you implemented this?

**Comment by jj0b** [comment]
@tobslob where did you put that to solve this?

**Comment by patrick-tolosa** [comment]
Hey all, I see there's some confusion here.
Config is defined on the `v2` object

```
// Import all
import * as cloudinary from 'cloudinary';

// use
cloudinary.v2.config({cloud_name:'demo'})
console.log(cloudinary.v2.url('sample'));

// alternative import
import {v2} from 'cloudinary';

// use
v2.config({cloud_name:'demo'});
console.log(v2.url('sample'));

```

**Comment by patrick-tolosa** [comment]
@jj0b I'm more than happy to reopen this if needed, 
I'd like to share this sample project that worked for me, I have a feeling this boils down to some form of configuration (either in TS or package.json)

https://github.com/patrick-tolosa/sample-cloudinary-node-ts

If you're still having issues, can you please provide a minimal reproducible project where I could take a look?

**Comment by jj0b** [comment]
@patrick-tolosa thanks for getting back to me. :) 

So it seems it must be some form of configuration issue as when I make a brand new simple `node.js` app and add `cloudinary` I have no problem setting the `config`.

I guess I'll see if knowing that helps me discover what's different in the project I'm working on.

**Comment by patrick-tolosa** [comment]
If you can share your package json (feel free to remove scripts/dependencies) and your tsconfig I can take a look and see if something pops out.

**Comment by jj0b** [comment]
@patrick-tolosa 

`package.json` and `tsconfig.json`. By the way, I used that tsconfig.json in the simple sample project that had no problem with `cloudinary.config()`.

```
{
  "engines": {
    "node": ">=10"
  },
  "husky": {
    "hooks": {
      "pre-commit": "tsdx lint"
    }
  },
  "prettier": {
    "printWidth": 80,
    "semi": true,
    "singleQuote": true,
    "trailingComma": "es5"
  },
  "signale": {
    "displayBadge": false,
    "underlineLabel": false
  },
  "module": "dist/scrappping-web.esm.js",
  "size-limit": [
    {
      "path": "dist/scrappping-web.cjs.production.min.js",
      "limit": "10 KB"
    },
    {
      "path": "dist/scrappping-web.esm.js",
      "limit": "10 KB"
    }
  ],
  "devDependencies": {
    "@size-limit/preset-small-lib": "^6.0.4",
    "@types/bluebird": "^3.5.36",
    "@types/fs-extra": "^9.0.13",
    "@types/papaparse": "^5.3.1",
    "@types/signale": "^1.4.2",
    "@types/yargs": "^17.0.7",
    "babel-plugin-import-graphql": "^2.8.1",
    "husky": "^7.0.4",
    "size-limit": "^6.0.4",
    "ts-node": "^10.4.0",
    "tsdx": "^0.14.1",
    "tslib": "^2.3.1",
    "typescript": "^4.4.4"
  },
  "dependencies": {
    "axios": "^0.24.0",
    "bluebird": "^3.7.2",
    "chalk": "^4.1.2",
    "cheerio": "^1.0.0-rc.10",
    "cloudinary": "^1.28.1",
    "dgraph-js": "^21.3.1",
    "graphql": "^15.7.2",
    "graphql-request": "^3.6.1",
    "grpc": "^1.24.11",
    "papaparse": "^5.3.1",
    "signale": "^1.4.0",
    "yargs": "^17.2.1"
  }
}
```

```
{
  // see https://www.typescriptlang.org/tsconfig to better understand tsconfigs
  "include": ["src", "types"],
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "es5"
    ],
    "baseUrl": "./src",
    "allowJs": true,
    "importHelpers": true,
    // output .d.ts declaration files for consumers
    "declaration": true,
    // output .js.map sourcemap files for consumers
    "sourceMap": true,
    // match output dir to input dir. e.g. dist/index instead of dist/src/index
    "rootDir": "./src",
    // stricter type-checking for stronger correctness. Recommended by TS
    "strict": false,
    // linter checks for common issues
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    // noUnused* overlap with @typescript-eslint/no-unused-vars, can disable if duplicative
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    // use Node's module resolution algorithm, instead of the legacy TS one
    "moduleResolution": "node",
    // transpile JSX to React.createElement
    "jsx": "react",
    // interop between ESM and CJS modules. Recommended by TS
    "esModuleInterop": true,
    // significant perf increase by skipping checking .d.ts files, particularly those in node_modules. Recommended by TS
    "skipLibCheck": true,
    // error out if import and file system have a casing mismatch. Recommended by TS
    "forceConsistentCasingInFileNames": true,
    // `tsdx build` ignores this option, but it is commonly used when type-checking separately with `tsc`
    "noEmit": true,
    "noImplicitAny": false,
  }
}
```

**Comment by patrick-tolosa** [comment]
Hey @jj0b 

I'm afraid I tried using your configuration and everything works.
(I added the TS Config to the sample project locally, and everything works)

I even changed your `noEmit` to true, and then used Node itself to run the generated `.js` file - still works.

If you can provide a sample project I'd like to take a deeper look, this behaviour is a bit odd.

I'm beginning to think it's not just configuration, but perhaps also related to your build process (assuming there's any)

**Comment by jj0b** [comment]
Thanks for all your help @patrick-tolosa. We figured out the issue. I had the directory that my code that was importing Cloudinary into named `cloudinary`. Once I changed the name of that directory, everything worked perfectly.

**Comment by patrick-tolosa** [comment]
Glad you got it sorted out!
