### ISSUE TITLE
cloudinary.image does not correctly escape single and double quotes in attributes

### ISSUE THREAD

**Issue by spudstuff** [cloudinary/cloudinary_npm#504]
cloudinary.image does not correctly escape single and double quotes in attributes. The replacements apply only to the first instance of single or double quotes, and not *all* instances.

## Issue Type
- [ ] Build - Can’t install or import the SDK
- [ ] Babel - Babel errors or cross browser issues
- [ ] Performance - Performance issues
- [x] Behaviour - Functions aren’t working as expected (Such as generate URL)
- [ ] Documentation - Inconsistency between the docs and behaviour
- [ ] Incorrect Types - For typescript users who are having problems with our d.ts files
- [ ] Other (Specify)

## Steps to reproduce
```
var img = cloudinary.image("sample.jpg", {
  alt: "this 'is' my \"alt\"."
});
```
### Expected
`<img src='https://res.cloudinary.com/demo/image/upload/sample.jpg' alt='this &#39;is' my &#34;alt\".'/>`

### Actual
`<img src='https://res.cloudinary.com/demo/image/upload/sample.jpg' alt='this &#39;is&#39; my &#34;alt&#34;.'/>`

## Versions and Libraries (fill in the version numbers)
Cloudinary_NPM SDK version 1.26.2
Node - 14.16.0
NPM - 6.14.11

**Comment by patrick-tolosa** [comment]
Thanks, @spudstuff, for the PR.
I've merged the fix and it will be available in the next release.
