### ISSUE TITLE
Params not getting passed in DELETE method

### ISSUE THREAD

**Issue by lyvartum** [cloudinary/cloudinary_npm#51]
Not sure why there is this IF statement in the call_api function:
```
if (method === "get") {
  api_url += "?" + query_params;
}
```

So when I initiate any DELETE methods, none of the params get through, thus, causing an error.

When I took out the IF condition, my delete requests work because the params/query get passed with the request.

**Comment by TalLevAmi** [comment]
there was an issue with node >= 0.12 and non-GET requests. Can you please try with master?

**Comment by TalLevAmi** [comment]
Should have been solved by 1.2.0. Please reopen if it still persists.
