### ISSUE TITLE
Type '{ folder: string; }' is not assignable to type 'Params | undefined'.

### ISSUE THREAD

**Issue by tom-saetran** [cloudinary/cloudinary_npm#511]
## Bug report for Cloudinary NPM SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two
Params types incomplete, folder does not exist in type "Params".

## Issue Type (Can be multiple)
[X] Incorrect Types - For typescript users who are having problems with our d.ts files

## Steps to reproduce

import { v2 as cloudinary } from "cloudinary"
const cloudinaryStorage = new CloudinaryStorage({ cloudinary, params: { folder: "folderName" }  })

=>

"Type '{ folder: string; }' is not assignable to type 'Params | undefined'.
  Object literal may only specify known properties, and 'folder' does not exist in type 'Params'."

## Error screenshots
https://cdn.discordapp.com/attachments/841312601443139616/877592275184660491/unknown.png

## Versions and Libraries (fill in the version numbers)
Cloudinary_NPM SDK version
Node - v14.17.4
NPM - 7.20.0

**Comment by d-mendoza** [comment]
@tom-saetran This issue should be opened with the plugin that you are using which is https://github.com/affanshahid/multer-storage-cloudinary/ as this is a different project. I am closing this ticket.

**Comment by tom-saetran** [comment]
> @tom-saetran This issue should be opened with the plugin that you are using which is https://github.com/affanshahid/multer-storage-cloudinary/ as this is a different project. I am closing this ticket.

Whops! Thank you, and sorry for the inconvenience.
