### ISSUE TITLE
Remote image overlays not working

### ISSUE THREAD

**Issue by viperfx** [cloudinary/cloudinary_npm#512]
## Describe the bug in a sentence or two.

When using the overlay transformations with a remote image, the final image URL generated does not load.

## Issue Type (Can be multiple)
[x] Behaviour - Functions aren’t working as expected (Such as generate URL)

## Steps to reproduce
Run the following code

`const imgUrl = cloudinary.url('uservitals/Cloudinary_Image_bv1w54.png', { overlay: { url: 'https://ik.imagekit.io/nuxjxaeieeq/Sandbox_Logo__3__u9DGMJywa.png' } })`

The generated URL does not load

## Browsers (if issue relates to UI, else ignore)
[ ] Chrome
[ ] Firefox
[ ] Safari
[ ] Other (Specify)
[x] All

## Versions and Libraries (fill in the version numbers)
Cloudinary_NPM SDK version
Node - 14.17.3
NPM - 6.14.13

**Comment by dannyv-cloudinary** [comment]
Hi Tharshan.

I've tried running that line on my own cloud, but replacing `uservitals/Cloudinary_Image_bv1w54.png` with the sample image, `sample`. The resulting URL works as expected: https://res.cloudinary.com/dannyv/image/upload/l_fetch:aHR0cHM6Ly9pay5pbWFnZWtpdC5pby9udXhqeGFlaWVlcS9TYW5kYm94X0xvZ29fXzNfX3U5REdNSnl3YS5wbmc/sample

Could you please share the URL that `cloudinary.url` returns for you, and provide us with your cloud name? We'll then be able to investigate further.

Many thanks,
-Danny Valentine, Cloudinary Developer Support

**Comment by viperfx** [comment]
@dannyv-cloudinary here is the full URL I see on my side output from the library.

`http://res.cloudinary.com/dt2t3yhwi/image/upload/l_fetch:aHR0cHM6Ly9pay5pbWFnZWtpdC5pby9udXhqeGFlaWVlcS9TYW5kYm94X0xvZ29fXzNfX3U5REdNSnl3YS5wbmc/v1/uservitals/Cloudinary_Image_bv1w54.png`

**Comment by taragano** [comment]
@viperfx - Taking a look at your account's Security Settings, I see that the usage of Fetched URL is restricted.
If you would remove this restriction, fetching will become allowed for your account.
Allowing fetch is done by going to the Security settings page (https://cloudinary.com/console/settings/security), unchecking `Fetched URL` then "save".
Please let us know if this helps?

**Comment by viperfx** [comment]
Yes that fixed it - thank you!
