### ISSUE TITLE
Image upload works fine in local environment, but gives  401 error in production

### ISSUE THREAD

**Issue by SiddheshDabholkar** [cloudinary/cloudinary_npm#517]
## Issue Type
[ &#x2714; ] Behaviour - uploading image gives unknown api key error in production
## Error screenshots
![error](https://user-images.githubusercontent.com/69386085/134788911-db9aa43a-7c56-4094-9437-85bb32809c5f.png)
![second](https://user-images.githubusercontent.com/69386085/134796564-28c68501-4315-4c48-b394-53f8b1175fde.png)

## Versions and Libraries (fill in the version numbers)
Cloudinary_NPM SDK version-1.27.0
Node - v15.13.0
NPM - 7.20.5

## Config Files 
Package.json

{
  "name": "twitterclone",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "serve": "node index.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/SiddheshDabholkar/Twitter-clone.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/SiddheshDabholkar/Twitter-clone/issues"
  },
  "homepage": "https://github.com/SiddheshDabholkar/Twitter-clone#readme",
  "dependencies": {
    "apollo-server": "^2.25.0",
    "bcryptjs": "^2.4.3",
    "cloudinary": "^1.27.0",
    "cookie-parser": "^1.4.5",
    "dotenv": "^10.0.0",
    "graphql": "^15.5.0",
    "jsonwebtoken": "^8.5.1",
    "mongoose": "^5.12.12",
    "validator": "^13.6.0"
  }
}

## Repository

[github repo](https://github.com/SiddheshDabholkar/Twitter-clone)
[live link](https://tweeetr.netlify.app/)

## NOTE
It cant be an issue with API key since i have only one account of cloudinary.I have also cross checked it

**Comment by roeeba** [comment]
Hi @SiddheshDabholkar, can you please share your cloud name so I can further investigate it?
Also, please share the below values located in your `graphql/uploadImage.js`:

```
cloud_name: process.env.CLOUDINARY_NAME,
api_key: process.env.CLOUDINARY_API_KEY,
```

Thanks!

**Comment by SiddheshDabholkar** [comment]
cloud_name:"drntday51",
api_key:"317461216434663",

**Comment by d-mendoza** [comment]
Can you try something like this in a node shell and let us know if there is an error?

```
var cloudinary = require('cloudinary').v2;
cloudinary.config({ 
  cloud_name: 'drntday51', 
  api_key: '317461216434663', 
  api_secret: 'REPACE_WITH_YOUR_KEY',
});
result = await cloudinary.uploader.upload("https://res.cloudinary.com/demo/sample.jpg", {folder: 'cloudinary'})
```

I was able to upload successful, so something in the application must be off. Is there anyway to cycle through values defined in dotenv?

**Comment by SiddheshDabholkar** [comment]
@d-mendoza it's working fine in local,but giving error in production

**Comment by SiddheshDabholkar** [comment]
> Can you try something like this in a node shell and let us know if there is an error?
> 
> ```
> var cloudinary = require('cloudinary').v2;
> cloudinary.config({ 
>   cloud_name: 'drntday51', 
>   api_key: '317461216434663', 
>   api_secret: 'REPACE_WITH_YOUR_KEY',
> });
> result = await cloudinary.uploader.upload("https://res.cloudinary.com/demo/sample.jpg", {folder: 'cloudinary'})
> ```
> 
> I was able to upload successful, so something in the application must be off. Is there anyway to cycle through values defined in dotenv?

was your application hosted? I am not facing above error in local !

**Comment by d-mendoza** [comment]
Hi,

This is probably a ticket that is better suited for our internal support here https://support.cloudinary.com/hc/en-us/requests/new and not necessarily related to the SDK. Can you open a ticket and reference this issue so we can continue and provide specifics of your account.

**Comment by SiddheshDabholkar** [comment]
> Hi,
> 
> This is probably a ticket that is better suited for our internal support here https://support.cloudinary.com/hc/en-us/requests/new and not necessarily related to the SDK. Can you open a ticket and reference this issue so we can continue and provide specifics of your account.

filled the form. Thanks for your response

**Comment by SiddheshDabholkar** [comment]
Seems like the error is with env variables .Images were uploading properly when i hard coded the cloud_name,api_key and api_secret. Thanks for the replies @d-mendoza @roeeba .
