### ISSUE TITLE
Must supply api_key

### ISSUE THREAD

**Issue by Sumair-Aslam** [cloudinary/cloudinary_npm#527]
I am working on a project in which we are using Cloudinary to upload images. I am writing the test cases for my project and I ran into this problem.
Index.ts fle: 

await cloudinary.config({
      cloud_name: process.env.CLOUDINARY_CLOUD_NAME /*'scytalelabs'*/,
      api_key: process.env.CLOUDINARY_API_KEY /*'432183885194623'*/,
![150980798-bc5e7dfb-8f43-433f-a02c-4104bb5dc3d4](https://user-images.githubusercontent.com/30640721/151020041-f5e855e0-ae5e-4bc0-be91-f8482cbc13c2.png)
![Screenshot from 2022-01-25 17-56-26](https://user-images.githubusercontent.com/80763643/150980979-25a0cac5-44b5-4eb1-acbc-f452483a9fe9.png)

      api_secret:
        process.env.CLOUDINARY_API_SECRET /*'<API-SECRET-HIDDEN>'*/,
        
    });

Even tried to hardcode the values but still got the error

Test case file:
it('responds with a 404 if the user is not found', async () => {
  const { cookie } = signup();
  // const listing = await createListing();

  await request(app)
    .post(`/api/listings`)
    .set('Cookie', cookie)
    .field({
      price: 100,
      title: 'test',
      description: 'for test purposes only',
      expiresAt: Date.now() + 25 * 60 * 60 * 1000,
      paymentConfirmation: true,
      massOfItem: 500,
      taxByMassOfItem: 25,
      salesTax: 5,
      exciseRate: 5,
    })
    .attach('image', '/home/sumair/Desktop/listing_test_case.png')
    .expect(400);
});

I am  using supertest library for test purposes

**Comment by momoip** [comment]
Hi Sumair-Aslam,

Would you comment out other code; but in the beginning use the following and see if you can the same error :

var cloudinary = require('cloudinary').v2; 

cloudinary.config({ 
   cloud_name: '<YOUR_CLOUD_NAME>', 
   api_key: '<YOUR_API_KEY>', 
   api_secret: '<YOUR_API_SECRET>',
   secure: true
});

You can refer to our configuration documentation: https://cloudinary.com/documentation/node_integration#configuration

Thanks,
Mo

**Comment by Sumair-Aslam** [comment]
Hi momoip,

First of all thanks a lot.
I have tried your solution but I am still getting the same error!!!

**Comment by epasos573** [comment]
Hi Sumai-Aslam,

In general, you need to put the `.env` file where you launch the `node` and it is possible to reconfigure NodeJS to recognize a different environment variable location, although it is better to put the environment variables in the project root.

To isolate the issue, can you help to initialize a local variable inside the `index.ts` post API and check if you are able to use Cloudinary objects:

```
//**index.ts**

app.post('/api/listings', [
    
    var local_cloudinary = require('cloudinary').v2;
    local_cloudinary.config({
        cloud_name: '<YOUR_CLOUD_NAME_HARDCODED_VALUE>',
        api_key: '<YOUR_API_KEY_HARDCODED_VALUE>',
        api_secret: '<YOUR_API_SECRET_HARDCODED_VALUE>',
        secure: true
    });
    
    //...
    var testclddata = cloudinary.image("sample.jpg")
    console.log(testclddata)
]);

```

If this works, it is likely that the global variable is not initialized when you run the `it('responds with a 404 if the user is not found', async () => {...}`.

Alternatively, you can also try using Postman to perform the POST request to `/api/listings` using the global variable `var cloudinary = require('cloudinary').v2;`.

**Comment by tad0xe** [comment]
i see you using dotenv hope you imported it in index.ts had the same issue  with javascript today and that was how i solved mine

**Comment by Sumair-Aslam** [comment]
Thanks, a lot the issue is resolved. It seems the error was because of multiple env files. Writing the cloudinary.config({....});
in the file where it is throwing error resolves it.
