### ISSUE TITLE
Can't get image width and height by PreloadedFile

### ISSUE THREAD

**Issue by Yinear** [cloudinary/cloudinary_npm#53]
While I upload from the browser, I can only get the preloaded_file by image_id.  But preloaded_file does not provide image width and height after uploading.

Or how can I get the width height?

**Comment by taragano** [comment]
I'm sorry for my response delay.

The preloaded file includes the image's public ID, resource type and type, version and signature.
The additional information, including width, height, bytes and more, can be grabbed from the upload's response.

**Comment by taragano** [comment]
@Yinear  - Just wanted to check whether my last response helped with answering your question.
As it's been a while since the last response, I'll close this issue now, but please feel free to re-open it if you need any further assistance.

Thanks
