### ISSUE TITLE
I don't know why it gives me this error

### ISSUE THREAD

**Issue by TioElvis** [cloudinary/cloudinary_npm#531]
I'm new to this, and I don't understand some things, but according to me this error is very strange, I'm using fastify-ts, multer and cloudinary, I want to tell result that the file path is the file to upload, but it doesn't tell me let

This is the code where I do the request:

fastify.post<{
    Body: CreatePublicationBody;
    Params: CreatePublicationParams;
  }>(
    "/create/:userId",
    {
      preHandler: upload,
    },
    async (request, reply) => {
      const { description } = request?.body;
      const { userId } = request.params;
      const { path } = request.file;

      const result = await v2.uploader.upload(path);

      console.log(result);

      const payload = {
        userId: userId,
        description: description,
        image: result.secure_url,
      };

      await fastify.store.Publication.create(payload, (err, data) => {
        if (err || !data) {
          throw new Error("Error to create Publication");
        } else {
          return reply.status(200).send(data);
        }
      });

      return "ok";
    }
  );

////

![Immagine 2022-02-06 021525](https://user-images.githubusercontent.com/92209528/152664378-21593b72-8b9f-4d05-bf9f-9f17f262575c.png)

And this is how I record it:

import fp from "fastify-plugin";
import multer from "fastify-multer";
import { File, FilesObject } from "fastify-multer/lib/interfaces";
import { v2 } from "cloudinary";

export default fp<SupportPluginOptions>(async (fastify, opts) => {
  fastify.decorate("someSupport", function () {
    return "hugs";
  });

  void fastify.register(multer.contentParser);

  v2.config({
    cloud_name: process.env.CLOUD_NAME,
    api_key: process.env.API_KEY,
    api_secret: process.env.API_SECRET,
  });

  
  
});

**Comment by roeeba** [comment]
Hey @TioElvis, Your upload method seems to be missing the callback function as the second parameter. It should be something like:

```
cloudinary.uploader.upload(path, function(error, result) {console.log(result, error)});
```

**Comment by TioElvis** [comment]
Hello, thanks for answering, I'm trying to do something like that, but now I get this error

![Immagine 2022-02-06 104711](https://user-images.githubusercontent.com/92209528/152675450-600ac3b4-0098-4854-b9c1-36f1edb1b0e6.png)

Any advice ?

**Comment by TioElvis** [comment]
I already solved it hahaha

import { FastifyPluginAsync } from "fastify";
import multer from "fastify-multer";
import { v2 } from "cloudinary";

 fastify.post<{
    Body: CreatePublicationBody;
    Params: CreatePublicationParams;
  }>(
    "/create/:userId",
    {
      preHandler: upload,
    },
    async (request, reply) => {
      const { description } = request?.body;
      const { userId } = request.params;
      const { path } = request.file;

      const result = await v2.uploader.upload(`${path}`);

      console.log(result);

      const payload = {
        userId: userId,
        description: description,
        image: result?.secure_url,
      };

      await fastify.store.Publication.create(payload, (err, data) => {
        if (err || !data) {
          throw new Error("Error to create Publication");
        } else {
          return reply.status(200).send(data);
        }
      });

      return "ok";
    }
  );

And I would be hahah

**Comment by roeeba** [comment]
@TioElvis Thanks for the update! good to hear 🙂
