### ISSUE TITLE
Config is not available in Cloudinary so how can i configure it

### ISSUE THREAD

**Issue by CodeIntelli** [cloudinary/cloudinary_npm#532]
## Bug report for Cloudinary NPM SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two
![image](https://user-images.githubusercontent.com/68110141/153396645-f75ca064-6272-4897-ad2d-774f94a765a8.png)

Clodinary Version
![image](https://user-images.githubusercontent.com/68110141/153396753-9e1d9861-5c6b-416f-9766-85c5c4e5cfb5.png)

**Comment by patrick-tolosa** [comment]
Hey @CodeIntelli , I'm missing your import statement in this snippet, but please take a look at this issue and see if it helps you out. 

https://github.com/cloudinary/cloudinary_npm/issues/491

**Comment by CodeIntelli** [comment]
I have solved the issue just because cloudinary dosent have ts file and in .ts file we have to just put 

//@ts-ignore

before config function and then i got the solution

**Comment by patrick-tolosa** [comment]
@CodeIntelli I'm glad you got it working, but that doesn't sound like an accurate solution.
This library does provide type definitions, and the config is included in them.

I'm closing this issue as it's solved in #491 but if you think your case is different please open a new issue with an example
