### ISSUE TITLE
Node 16 support?

### ISSUE THREAD

**Issue by panaman67** [cloudinary/cloudinary_npm#534]
## Explain your use case
Node 16 is current LTS release and is used commonly. Supporting it would be helpful.

## Describe the problem you’re trying to solve
Using the cloudinary sdk with a Node 16 Vue 3 project

**Comment by michalkcloudinay** [comment]
Hi @panaman67, We are further checking this on our end, and will provide updates on the thread.

**Comment by panaman67** [comment]
> Hi @panaman67, We are further checking this on our end, and will provide updates on the thread.

Thank you. Looking forward to it.

**Comment by patrick-tolosa** [comment]
@panaman67 We've updated this project (The Cloudinary Node SDK) to support tests for Node 16, this was supported out of the box and no changes were needed.

See #535

**Comment by panaman67** [comment]
Will the readme get updated with 16 support?

**Comment by patrick-tolosa** [comment]
@panaman67 thanks for the heads up :) It's now updated
