### ISSUE TITLE
Documentation link in cloudinary_npm repo redirects to 404 page.

### ISSUE THREAD

**Issue by Dmeowmixer** [cloudinary/cloudinary_npm#536]
## Describe the bug in a sentence or two.
Documentation here: https://github.com/cloudinary/cloudinary_npm#note 
 (https://cloudinary.com/documentation/node_integrations ) redirects to a 404 page

## Issue Type (Can be multiple)
[x] Documentation - Inconsistency between the docs and behaviour

## Steps to reproduce
Visit URL here: https://github.com/cloudinary/cloudinary_npm#note ( https://cloudinary.com/documentation/node_integrations ) redirects to a 404 page

Appears the correct URL is now https://cloudinary.com/documentation/node_integration

## Error screenshots
![image](https://user-images.githubusercontent.com/8635238/156946723-5478c1fc-3cb6-434e-920b-31fbc64889e3.png)

## Repository
https://github.com/cloudinary/cloudinary_npm#note

**Comment by patrick-tolosa** [comment]
PR merged and this is now fixed.
