### ISSUE TITLE
TypeScript Type: api.tags parameter order

### ISSUE THREAD

**Issue by zoeytruong** [cloudinary/cloudinary_npm#543]
## Bug report for Cloudinary NPM SDK
version: "^1.28.1"

## Describe the bug in a sentence or two.

- In the node SDK doc for `Get Tags`,[ it shows that I can pass in an object for options](https://cloudinary.com/documentation/admin_api#:~:text=List%20tags%20that%20start%20with%20%27pro%27%20for%20all%20images%3A). The doc shows passing in the options obj as the first param, then the callback function. 

- However, in the TS type definition for `tags`, it shows that `callback` [is the first param and then options](https://github.com/cloudinary/cloudinary_npm/blob/master/types/index.d.ts#L864
). I am trying to use node `util.promisify` for this `api.tags` function so am wondering why Cloudinary has `callback` as the first param. If callback is the second param in `tags`, then I can call `util.promisify` on this method.  

- Tested by calling `.tags` with callback as first argument and that fails. 

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[X] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce
… if applicable

## Error screenshots
… if applicable

## Browsers (if issue relates to UI, else ignore)
[ ] Chrome
[ ] Firefox
[ ] Safari
[ ] Other (Specify)
[ ] All

## Versions and Libraries (fill in the version numbers)
Cloudinary_NPM SDK version
Node - 0.0.0
NPM - 0.0.0

## Config Files (Please paste the following files if possible)
Package.json

## Repository
If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by aleksandar-cloudinary** [comment]
Hi @zoeytruong - thanks for raising this and for opening a pull request. I've tagged one of my colleagues there who can help to review.

**Comment by patrick-tolosa** [comment]
Thanks for the PR @zoeytruong 

It'll be released in the next version (Probably next week)

**Comment by zoeytruong** [comment]
@patrick-tolosa can you update the package-json version to reflect the merged PR for this? Thanks.

**Comment by strausr** [comment]
@zoeytruong Please see the latest release:)
