### ISSUE TITLE
 Error: { message: 'Request Timeout', http_code: 499, name: 'TimeoutError' }

### ISSUE THREAD

**Issue by mugishap** [cloudinary/cloudinary_npm#547]
So, the problem is that I encountered a problem while uploading videos. As you know videos are somehow large so I would like to ask if there was a way that a person change when the timeout error can pop up because videos (eg: a song) can be up to 200 mb and 200mb can't be uploaded just in one minute. Maybe if there is a way you can help I'm looking forward to your help. Thanks.
![image](https://user-images.githubusercontent.com/94197472/162587008-69f745db-4d43-455c-b390-17896c50e580.png)

**Comment by aleksandar-cloudinary** [comment]
Hi @mugishap - Could you please share the code you are using to upload? Large files (100MB and over) need to be sent in chunks/parts and for that, we have the `upload_large` method. Are you currently using this? https://cloudinary.com/documentation/node_image_and_video_upload#node_js_video_upload
If not, please use this method and you can optionally pass a `chunk_size` parameter to that method set to a lower value (20MB default) - that way, each chunk will be smaller in size and will take a lower amount of time to upload and should be within the default 60s timeout. You could set the chunk_size as follows `chunk_size: 6000000` to set it to 6MB. If you're running into a timeout even with lower chunk_size then you could increase the `timeout` by passing that parameter in the configuration (same level as cloud_name, api_key etc).
Let us know how it goes.

**Comment by mugishap** [comment]
That documentation does it thank you very much

**Comment by mugishap** [comment]
Thank you very much for your reply. I just got the answer in
the documentation you gave me.
