### ISSUE TITLE
cloudinary.image mutates option arguement

### ISSUE THREAD

**Issue by gching** [cloudinary/cloudinary_npm#55]
The `option` argument being passed in to `cloudinary.image` is being used directly without being copied, resulting in a mutated `option` object as an end result.

Reproduction:
```javascript
var cloudinary = require('cloudinary');
var options = {
  fetch_format: "auto",
  flags: "progressive"
};
cloudinary.image("random_id", options);
// options now is {} because cloudinary.image mutated it
```

Made a pull request to fix this (I basically just extend it using lodash like what `cloudinary.url` does): #54

**Comment by tocker** [comment]
Closing after merging PR #54.

Thanks for the PR!
