### ISSUE TITLE
modules import using ESM

### ISSUE THREAD

**Issue by roniceyemeli** [cloudinary/cloudinary_npm#552]
### **I'm currently working on a  nodejs, expressjs project, when I'm using COMMONJS everything is working fine.but with ECMAScript around I am receiving an empty 500 error from postman to be honest I found nothing that help resolve this issue. here's my code is CJS and ESM respectively** 

```javascript
const router = require('express').Router();
const cloudinary = require('cloudinary');
const { unlinkSync } = require('node:fs');

cloudinary.config({
	cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
	api_key: process.env.CLOUDINARY_API_KEY,
	api_secret: process.env.CLOUDINARY_API_SECRET
});

router.post('/upload',  (req, res) => {
	try {
		if (!req.files || Object.keys(req.files).length === 0)
			return res.status(400).json({ msg: 'No files were uploaded.' });

		const file = req.files.file;
		if (file.size > 1024 * 1024) {
			 removeTmp(file.tempFilePath);
			return res.status(400).json({ msg: 'Size too large' });
		}

		if (file.mimetype !== 'image/jpeg' && file.mimetype !== 'image/png') {
			 removeTmp(file.tempFilePath);
			return res.status(400).json({ msg: 'File format is incorrect.' });
		}

		cloudinary.v2.uploader.upload(file.tempFilePath, { folder: 'test' }, async (err, result) => {
			if (err) throw err;
			removeTmp(file.tempFilePath);

			res.json({ public_id: result.public_id, url: result.secure_url });
		});
	} catch (err) {
		return res.status(500).json({ msg: err.message });
	}
});


const removeTmp = (path) => {
		unlinkSync(path, err => {
			if(err) console.log('this is the error',err);;
		});
		console.log(`successfully deleted ${path}`);

};
module.exports = router;
```
 ```javascript
import express from 'express';
const router = express.Router();
import { v2 as cloudinary } from 'cloudinary'
import { unlinkSync } from 'node:fs';

cloudinary.config({
	cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
	api_key: process.env.CLOUDINARY_API_KEY,
	api_secret: process.env.CLOUDINARY_API_SECRET
});

router.post('/upload', (req, res) => {
	try {
		if (!req.files || Object.keys(req.files).length === 0) return res.status(422).json('no files uploaded');

		const file = req.files.file;
		if (file.size > 1024 * 1024) {
			rmvTmp(file.tempFilePath);
			return res.status(400).json({ msg: 'size too large' });
		}

		if (file.mimetype !== 'image/jpeg' && file.mimetype !== 'image/png') {
			rmvTmp(file.tempFilePath);
			return res.status(400).json({ msg: 'this file format is not supported' });
		}
		cloudinary.uploader.upload(file.tempFilePath, { folder: 'vireau' }, async (err, result) => {
			if (err) throw err;
			try {
				rmvTmp(file.tempFilePath);
				res.json({ public_id: result.public_id, url: result.secure_url });
			} catch (err) {
				res.status(400).json({ msg: error.message });
			}

			rmvTmp(file.tempFilePath);
			res.json({ public_id: result.public_id, url: result.secure_url });
		});
	} catch (error) {
		return res.status(500).json({ msg: error.message });
	}
});

const rmvTmp = (path) => {
	unlinkSync(path, (err) => {
		if (err) throw err;
		console.log('successfull deleted');
	});
};

export default router;
```

**Comment by patrick-tolosa** [comment]
@roniceyemeli 

What errors are you getting? 
500 error means your server returns the 500 response, but what exceptions/errors does node throw?

**Comment by roniceyemeli** [comment]
![Screenshot from 2022-05-29 15-16-34](https://user-images.githubusercontent.com/81180104/170873807-7749f173-d0b1-4f69-a8ad-548c6c9e2c47.png)

and there's no exceptions/errors in my terminal, the server still running well

**Comment by patrick-tolosa** [comment]
I'd start by removing the try catch to prevent node from swallowing the exception. 

Perhaps you can also place some console.logs within your code to identify where the issue is? 
alternatively you can try simplifying the example, remove all pieces of code that aren't being tested directly until you find what causes the issue.

For example, does removing all Cloudinary code result in working code? (If yes, slowly add functionality until you identify where's the issue).

**Comment by roniceyemeli** [comment]
hello patrick thanks for the tip, i think my problem is related to the CLOUINDARY env file, I'm getting undefined while doing this, seem like my env file doesn't load
```
console.log(process.env.CLOUDINARY_CLOUD_NAME)

if (
	typeof (
		process.env.CLOUDINARY_CLOUD_NAME === 'undefined' ||
		process.env.CLOUDINARY_API_SECRET === 'undefined' ||
		process.env.CLOUDINARY_API_KEY === 'undefined'
	)
) {
	console.log('!! cloudinary config is undefined !!');
	console.log('export CLOUDINARY variable or set dotenv file');
}
```

**Comment by patrick-tolosa** [comment]
Great!

It looks like your environment variables aren't being set-up properly.
how are you setting your environment variables? 

There are several approaches:
- Use a `.env` file, and use the library `dotenv` to auto-load the `.env` file (Are you doing this?)
- Use a variable in your startup script: `FOO=BAR node index.js` -> will result in `process.env.FOO === 'BAR'`
- Define it in your machine as an environment variable (this varies on which machine).

This doesn't sound like a Cloudinary problem, but let me know if the above helps you out.

**Comment by roniceyemeli** [comment]
absolutely wasn't a cloudinary problem, just fixed it by passing  this code within the post controller. it's a good practice? 
```
cloudinary.config({
   cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
   api_key: process.env.CLOUDINARY_API_KEY,
   api_secret: process.env.CLOUDINARY_API_SECRET
});
```

**Comment by patrick-tolosa** [comment]
Great it's solved!

Ideally the Cloudinary library should be set up only once, probably best if it's configured in it's own file, and them imported into your controller to be used.

This is my personal preference of course:

```js
import configuredCloudinary from './myConfiguredCloudinary.js'
```

For small projects you can put it anywhere it makes sense to you.
I'd still be curious as to why you ran into this problem though :)
