### ISSUE TITLE
Upload Widget - Linking to .aspx files in Web Address results in timeout

### ISSUE THREAD

**Issue by rachel-adelle** [cloudinary/cloudinary_npm#561]
## Description
Linking to .aspx files under Web Address in the sample Upload Widget on your website results in a timeout.

## Issue Type
[ x ] Performance
[ x ] Behaviour

## Steps to reproduce
Go to your sample Upload Widget on your website here: https://cloudinary.com/documentation/upload_widget
Paste this link under Web Address: https://www.newsmax.com/CMSPages/GetFile.aspx?guid=9a9d600d-4cfe-4cdc-aefa-1d3b1d4c084c&SiteName=Newsmax&maxsidesize=600

## Error screenshots
https://user-images.githubusercontent.com/84212414/189763082-778bd616-5cfb-4683-a4af-507f977f8f83.mp4

**Comment by skalahasti-cloudinary** [comment]
Hi @rachel-adelle ,

Thanks for reporting the issue. We are currently looking into it.

I will keep you posted with updates.

Best Regards,
Sree

**Comment by rachel-adelle** [comment]
Yes thank you, it's request #201108.

**Comment by rachel-adelle** [comment]
Closing this issue, as it seems to be happening due to being blocked by the website as a security measure.
