### ISSUE TITLE
Use Formatter tool to make the code more readable 

### ISSUE THREAD

**Issue by MohammedOmar123** [cloudinary/cloudinary_npm#564]
## Bug report for Cloudinary NPM SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
…

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce
… if applicable

## Error screenshots
… if applicable

## Browsers (if issue relates to UI, else ignore)
[ ] Chrome
[ ] Firefox
[ ] Safari
[ ] Other (Specify)
[ ] All

## Versions and Libraries (fill in the version numbers)
Cloudinary_NPM SDK version
Node - 0.0.0
NPM - 0.0.0

## Config Files (Please paste the following files if possible)
Package.json

## Repository
If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by dannyv-cloudinary** [comment]
Hi @MohammedOmar123 .

It seems this bug report has been posted with the default template, so I'm closing it off for now. Please feel free to reopen this is with additional details if required, or submit a new bug report.

Many thanks,
-Danny
