### ISSUE TITLE
Modularize client-side utils

### ISSUE THREAD

**Issue by localnerve** [cloudinary/cloudinary_npm#57]
Maybe I'm missing something, but here is a suggestion I'm contributing based on my current understanding.
### Use Case

I want to use utils.url to generate urls in the client side part of a web app. I want to be able to include that part of the code **only** in my client bundle.
### Suggestion

From that use case comes my suggestion:
  Make the util url standalone so it can be included by a bundler by itself without all the other stuff.
This would be super useful for all of the utils that are useful client side. Make them all modules that can be included by themselves as needed.

**Comment by tocker** [comment]
Did you try [cloudinary_js](https://github.com/cloudinary/cloudinary_js)? It is designed for the client side.

**Comment by localnerve** [comment]
Yes, unfortunately it requires jQuery, and is also not modular. I'm looking for just javascript modules as described above that can be pulled into a bundle via commonjs or es6 modules.

Certainly, cloudinary_js could also serve as the basis for a refactor as well and components could be pulled out of that too. (in cloudinary_js, function cloudinary_url, for example). Those components could be used by both cloudinary_npm and cloudinary_js, without dependencies (or with dependencies injected).

**Comment by tocker** [comment]
Hi @localnerve ,
We released a new JS library which is not dependent on jQuery. [Check it out!](https://github.com/cloudinary/pkg-cloudinary-core)
