### ISSUE TITLE
TypeScript: Why `resource_type` in `UploadApiResponse` interface is not required anymore?

### ISSUE THREAD

**Issue by Melanie-Samedi** [cloudinary/cloudinary_npm#583]
Hi, thanks for your work, I have a question about TS type change in `1.33` version more specifically on [this change](https://github.com/cloudinary/cloudinary_npm/commit/00b235a5fb028e24805a21ef79328b7a5464271e#diff-093ad82a25aee498b11febf1cdcb6546e4d223ffcb49ed69cc275ac27ce0ccceL584) concerning `UploadApiResponse` interface.

It's great to have specified `resource_type` values, but I was wondering why it became **optional**? 

I understood that `resource_type` would never be `undefined` in API response because by default it will be set to `image` or set to one of those values `image`, `raw`, `video`, `auto` if specified in upload options, so `resource_type` would be required like `resource_type: "image" | "video" | "raw" | "auto"`
I would gladly appreciate any information if I missed something :) have a nice day !

**Comment by tamaracloudinary** [comment]
Hi Melanie!

Thank you for reporting this, this was a human error made by me. I've created a pull request and we will merge it in the near future. 

Have a great one, 
Tamara
