### ISSUE TITLE
Remove the Node.js 6 support

### ISSUE THREAD

**Issue by oles** [cloudinary/cloudinary_npm#589]
I'd like for a smaller node_modules and quicker installs, and this package pulls in the whole core-js, when it seems to not be needed:

https://github.com/cloudinary/cloudinary_npm/blob/1.34.0/cloudinary.js

as Node.js 6 had an end-of-life at 2019-04-30

**Comment by victorli-cloudinary** [comment]
Hi @oles thank you for bringing this up to us! This has been addressed in 2.0.0, and as such we will close this issue.
