### ISSUE TITLE
Invalid Signature error

### ISSUE THREAD

**Issue by sherylpeebee** [cloudinary/cloudinary_npm#59]
i'm getting the following message back when i try to upload:

`{ error:
   { message: 'Invalid Signature 53c516a1618fe4d88a81a0b6289e83a205608cbe. String to sign - \'timestamp=1439054775\'.',
     http_code: 401 } }`

i followed the config example provided in the documentation. looks like: 

`cloudinary.config({
  cloud_name: 'some-cloud',
  api_key: API_KEY,
  api_secret: CLOUD_API_SECRET
});`

can anyone tell me what i'm doing wrong?

**Comment by zafrani** [comment]
Having the same error on my end following 
http://cloudinary.com/documentation/upload_images#remote_upload
and 
http://cloudinary.com/documentation/upload_images#request_authentication

**Comment by baziliolg** [comment]
Same here. I'm trying to upload images with cURL and get this error:
```{"error":{"message":"Invalid Signature fd6a0434ac39cb3fbeeaf04cd6dfa18ed198eed2. String to sign - 'timestamp=1446836936'."}}```

**Comment by taragano** [comment]
I'm sorry for my response delay.

An "Invalid Signature" error response means that the signature you've passed is different than the one Cloudinary expects to allow the upload. The error response also explains the exact string you need to sign.

We usually highly recommend letting our SDK to take care of the signature generation for you behind the scenes. As demonstrated in our sample projects:
https://github.com/cloudinary/cloudinary_npm/tree/master/samples

However, if you still prefer to take care of it yourself, please have a look at the following article:
http://support.cloudinary.com/hc/en-us/articles/203817991-How-to-generate-a-Cloudinary-signature-on-my-own-

**Comment by taragano** [comment]
@sherylpeebee, @zafrani, @baziliolg  - Just wanted to check whether my last response helped with answering your question.
As it's been a while since the last response, I'll close this issue now, but please feel free to re-open it if you need any further assistance.

Thanks

**Comment by frankorama** [comment]
This worked for me, but adding the "callback" parameter to the list of signed parameters isn't documented anywhere in the API.

**Comment by yakirp** [comment]
@frankorama - Thanks for bringing this to our attention, we'll add it to our documentation

**Comment by animeshsinghweb** [comment]
@frankorama @yakirp where and _how_ to add the "callback" parameter? Same issue here.

**Comment by frankorama** [comment]
```
function generateUploadUrl(folder){
  let paramArray = [
    {name: 'timestamp', value: cloudinary.utils.timestamp(), toSign: true},
    {name: 'type', value: 'authenticated', toSign: false},
    {name: 'api_key', value: provider.apiKey, toSign: false},
    {name: 'folder', value: folder.toString(), toSign: true},
    {name: 'callback', value: 'http://widget.cloudinary.com/cloudinary_cors.html', toSign: true},
  ];

    let paramsToSign = paramArray.filter(p => p.toSign).reduce((coll, param)=>{
    coll[param.name] = param.value;
    return coll;
  }, {});
  let signature = cloudinary.utils.api_sign_request(paramsToSign,  providers.cloudinary.apiSecret);

  let params = paramArray.map(p => `${p.name}=${p.value}`).join('&');
  let paramObj = {};
  paramArray.forEach(p => paramObj[p.name] = p.value);
  paramObj.signature = signature;

  let url = `${provider.uploadUrl}?${params}&signature=${signature}`;

  let retVal = {url: url, parameters: paramObj};

  return retVal;
}
```

**Comment by Kxze** [comment]
Still not working for me.

`"Invalid Signature 8cb46339a4dd5f3459eb2b658b29835b4e45e7e9. String to sign - 'timestamp=1516833104'."`

**Comment by frankorama** [comment]
The good thing about the error message is that it shows you the problem param. Do you have a time stamp in your param list, and is the value in the error message the value you’re encoding?

**Comment by Kxze** [comment]
Yup, I do and it's the exact same value.

**Comment by aditimadan-Cloudinary** [comment]
You can use curl command to test the upload with signature:  curl https://api.cloudinary.com/v1_1/<cloud_name>/image/upload -X POST --data 'file=<url of image>&timestamp= <current unix timestamp>&public_id=<insert public_id>&transformation=<insert transformation>&api_key=<your api key>&signature=<generated signature>'

If we want to upload sample image with transformation w_200,h_200,c_limit and public id=sample then the signature will be comprised of
1. public id
2. timestamp
3. transformation and
4. generated API secret/signature(Note that this is not your account API secret key but a generated signature)

You can use http://www.sha1-online.com/ for generating the signature for testing purpose 

The signature parameters will be - public_id=sample&timestamp=1514500082&transformation=w_200,h_200,c_limit<Insert your API secret here without comma or space>
The signature we got from running the above query is-e5f898986395cf2ba6847571188a25b91d5e89a5
Now our example curl command is:-

curl https://api.cloudinary.com/v1_1/<your cloud name>/image/upload -X POST --data 'file=http://res.cloudinary.com/demo/image/upload/sample.jpg&timestamp= 1514500082&public_id=sample&transformation=w_200,h_200,c_limit&api_key=<your api key>&signature=e5f898986395cf2ba6847571188a25b91d5e89a5'

For more information: https://cloudinary.com/documentation/upload_images#creating_api_authentication_signatures

**Comment by vineshhpatel** [comment]
@aditimadan-Cloudinary 
This simple example does not work. example is documented here https://github.com/cloudinary/cloudinary_npm/blob/master/samples/basic/basic.js
what I might be doing wrong?

`cloudinary.uploader.upload('http://res.cloudinary.com/demo/image/upload/couple.jpg', {tags : "basic_sample"}, function(err,image){

  console.log();

  console.log("** Remote Url");

  if (err){ console.warn(err);}

  console.log("* "+image.public_id);

  console.log("* "+image.url);

  waitForAllUploads("couple",err,image);
});`

**Comment by aditimadan-Cloudinary** [comment]
Hi Vinesh,

Can you please open a support ticket here- https://support.cloudinary.com/hc/en-us/requests/new and please share how you are generating signature including the params and we will be able to debug the issue.

Thanks,

**Comment by vineshhpatel** [comment]
I was using wrong api secret. its working now. Thanks

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by good-idea** [comment]
I had the same issue where my API secret was misconfigured on my staging server. It would be helpful if this error threw an "Invalid secret" instead of "Invalid signature" when this is the case.

**Comment by aleksandar-cloudinary** [comment]
Hi @good-idea. Thanks for your suggestion. Unfortunately, that isn't possible since the API Secret is not directly sent to Cloudinary. The "Invalid Signature" error is returned when the provided signature (which is used for authenticating the API call) doesn't match the parameters passed as part of the request. An incorrect API Secret is only one of the possible reasons that may cause an invalid signature, but Cloudinary has no way to know if this is due to a wrong API Secret specifically. It could also be the case that the API Secret is correct but the client which is calculating the signature is not signing all required parameters, or it's signing parameters that shouldn't be signed and therefore, generating an invalid signature.

**Comment by good-idea** [comment]
Got it, that makes sense. Thanks for the quick reply!

**Comment by sarb001** [comment]
This Discussion Helps me even Today ,Thanks @aleksandar-cloudinary

**Comment by RudyRi** [comment]
> Hi @good-idea. Thanks for your suggestion. Unfortunately, that isn't possible since the API Secret is not directly sent to Cloudinary. The "Invalid Signature" error is returned when the provided signature (which is used for authenticating the API call) doesn't match the parameters passed as part of the request. An incorrect API Secret is only one of the possible reasons that may cause an invalid signature, but Cloudinary has no way to know if this is due to a wrong API Secret specifically. It could also be the case that the API Secret is correct but the client which is calculating the signature is not signing all required parameters, or it's signing parameters that shouldn't be signed and therefore, generating an invalid signature.

Sorry for necroing this post, but this helped me out immensely. It turns out while testing the API through Postman that a blank value was being signed along with the required variables (Cloud name, API key, API Secret) and that generated an invalid signature. Removing the blank value allowed me to upload normally.

**Comment by MohammadHosseinKv** [comment]
This topic helped me fix my Cloudinary Invalid Signature problem.

I was using **Google Apps Script** to upload a JSON file generated from one of my sheets to Cloudinary. Since I needed a signed upload, I was generating the signature manually using SHA-1 or SHA-256. At first, I thought the signature generation itself was the issue, but the actual problem was with the **timestamp**: it was being converted from an integer to **scientific notation** when passed inside the payload object.

Initially, using:

```javascript
const timestamp = Math.floor(Date.now() / 1000);
```

should produce an integer timestamp (e.g., `1759930024`), and it does. However, after putting it into the payload object, it was automatically converted to scientific notation (`1.759930024E9`), which caused Cloudinary to reject the signature.

The error I received looked like this:

```
Error: Cloudinary signed upload failed: 401 
{"error":{"message":"Invalid Signature 181fb39a7b254817ef59dbc0728c72339e9bf86a. String to sign - 'folder=site-data&public_id=products.json&timestamp=1.759930024E9'."}}
```

The fix was to use `.toFixed()` in GAS to keep the timestamp as a plain integer:

```javascript
const timestamp = Math.floor(Date.now() / 1000).toFixed();
```

After this change, the signature was accepted and the upload worked.

Here’s the **working code**:

```javascript
function uploadJsonToCloudinarySigned() {
  const arr = sheetToJson('Products');
  const jsonString = JSON.stringify(arr || []);

  const cfg = _getCloudinarySignedConfig();
  if (!cfg.cloudName || !cfg.apiKey || !cfg.apiSecret) {
    throw new Error('Set CLD_CLOUD_NAME, CLD_API_KEY, CLD_API_SECRET in Script Properties.');
  }

  // Generate timestamp as a plain integer
  const timestamp = Math.floor(Date.now() / 1000).toFixed();
  const publicId = 'products.json';
  const folder = CLOUDINARY_UPLOAD_PATH_FOLDER;

  // Parameters to include in signature (exclude file, cloud_name, api_key)
  const signParams = { timestamp: timestamp, public_id: publicId };
  if (folder) signParams.folder = folder;

  // Build string to sign (alphabetically sorted)
  const keys = Object.keys(signParams).sort();
  const strToSign = keys.map(k => `${k}=${signParams[k]}`).join('&');

  // SHA-1 hash for signature
  const signature = _sha1Hex(strToSign + cfg.apiSecret);

  // Convert JSON to Base64 Data URI
  const base64 = Utilities.base64Encode(jsonString, Utilities.Charset.UTF_8);
  const dataUri = 'data:application/json;base64,' + base64;

  // Payload for POST request
  const payload = {
    api_key: cfg.apiKey,
    file: dataUri,
    public_id: publicId,
    signature: signature,
    timestamp: timestamp,
  };
  if (folder) payload.folder = folder;

  const url = `https://api.cloudinary.com/v1_1/${cfg.cloudName}/raw/upload`;
  const options = { method: 'post', payload: payload, muteHttpExceptions: true, overwrite: true, invalidate: true };

  const resp = UrlFetchApp.fetch(url, options);
  const code = resp.getResponseCode();
  const text = resp.getContentText();

  if (code < 200 || code >= 300) {
    throw new Error('Cloudinary signed upload failed: ' + code + ' ' + text);
  }
  Logger.log(JSON.parse(text));
}
```

Large integers, such as numeric timestamps, may automatically convert to scientific notation when used in objects. Using `.toFixed()` ensures the timestamp stays as an integer, preventing “Invalid Signature” errors from Cloudinary.

Hope this helps. I suggest that if you have an invalid signature problem, first check your API secret key, as most people get that wrong. After confirming that your API key, API secret, and cloud name are correct, then inspect the other parameters being passed to Cloudinary, such as the signature itself or timestamp.

**Comment by DatTrinhThanh** [comment]
on the server, i generated a signature using this in the service:
```javascript
const generateSignature = () => {
    const timestamp = Math.round(Date.now() / 1000);
     return {
        signature: cloudinary.utils.api_sign_request(
            { timestamp },
            cloudinary.config().api_secret,
        ),
        timestamp,
    };
};
``` 
and this in the controller:
```javascript
const generateSignatureController = (req, res, next) => {
    const sig = ImageService.generateSignature();
    return res.status(200).json({
        signature: sig.signature,
        timestamp: sig.timestamp,
        cloudName: cloudinary.config().cloud_name,
        apiKey: cloudinary.config().api_key,
    });
};
```
which led to the problem "Invalid signature String to sign..." when i tried to upload an image using the upload widget.
here's how i configured the upload widget using React:
```javascript
function App() {
    const cloudinaryRef = useRef();
    const widgetRef = useRef();
    useEffect(() => {
        cloudinaryRef.current = window.cloudinary;
        axios.post("http://localhost:3000/images/signature").then((res) => {
            widgetRef.current = cloudinaryRef.current.createUploadWidget({
                cloudName: res.data.cloudName,
                uploadSignatureTimestamp: res.data.timestamp,
                uploadSignature: res.data.signature,
                apiKey: res.data.apiKey
            });
        });
    }, []);

    return <button onClick={() => widgetRef.current.open()}>Upload</button>;
}
```

the way i fixed it, i included 2 more parameters in the `api_sign_request` parameters which are `source: "uw"` and `folder: "<your folder name>"`:
```javascript
const generateSignature = () => {
    const timestamp = Math.round(Date.now() / 1000);
     return {
        signature: cloudinary.utils.api_sign_request(
            { timestamp, source: "uw", folder: "my_signed_upload"},
            cloudinary.config().api_secret,
        ),
        timestamp,
    };
};
```
and also included the `folder` parameter in the upload widget config **with the same value** used in the `api_sign_request` above:
```javascript
function App() {
    const cloudinaryRef = useRef();
    const widgetRef = useRef();
    useEffect(() => {
        cloudinaryRef.current = window.cloudinary;
        axios.post("http://localhost:3000/images/signature").then((res) => {
            widgetRef.current = cloudinaryRef.current.createUploadWidget({
                cloudName: res.data.cloudName,
                uploadSignatureTimestamp: res.data.timestamp,
                uploadSignature: res.data.signature,
                apiKey: res.data.apiKey,
                folder: "my_signed_upload",
            });
        });
    }, []);

    return <button onClick={() => widgetRef.current.open()}>Upload</button>;
}
```
and i finally got rid of that error, hope this helps someone.

p/s: the cloudinary's docs kind of suck, tbh.
