### ISSUE TITLE
Custom Analytics IDs Don't Produce Custom Code

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary/cloudinary_npm#590]
## Describe the bug in a sentence or two.

When passing in custom analytics IDs with `sdkCode`, `techVersion`, and `sdkSemver` via `url` options, the values get overridden by the default analytics settings.

I suspect the issue is:

```
let analyticsOptions = getAnalyticsOptions(Object.assign({}, options, sdkVersions));
```

Where `sdkVersion` will always override any values passed in through `options`.

That is, if this is even the right way to set custom analytics :)

Reference: https://github.com/cloudinary/cloudinary_npm/blob/ef6f5ad9eb1c0834c5796b833b4a7247a88cd39a/lib/utils/index.js#L833

Related: https://github.com/cloudinary-devs/gatsby-transformer-cloudinary/issues/229

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce

```
const url = cloudinary.url(publicId, {
    ...
    urlAnalytics: true,
    sdkCode: 'X',
  });
```

Doesn't produce an ID with `X`

## Browsers (if issue relates to UI, else ignore)
[ ] Chrome
[ ] Firefox
[ ] Safari
[ ] Other (Specify)
[x] All

## Versions and Libraries (fill in the version numbers)
Cloudinary_NPM SDK version 1.34.0 (latest)

**Comment by wissam-khalili** [comment]
Hi @colbyfayock ,

Thank you for your input.
I will share this information with the SDK team.

Regards,
Wissam
