### ISSUE TITLE
Wrong response type from https://api.cloudinary.com/v1_1/<cloud>/auto/upload

### ISSUE THREAD

**Issue by TeemuKoivisto** [cloudinary/cloudinary_npm#599]
## Describe the bug in a sentence or two.
When uploading to `https://api.cloudinary.com/v1_1/<cloud>/auto/upload` API (the same as `cloudinarySdk.uploader.upload`), the returned type is `UploadApiResponse`. This works fine for uploads that upload the whole file at once but for partial uploads, the response is either a completely different object:

```
{
    done: false,
    bytes: 5242880,
    kind: 'upload',
    resource_type: 'image',
    public_id: '167d4ed2-c642-439e-b80b-c47ac97d085c/Y-JG-CANON-EOS-R7-0012'
}
```

Or `UploadApiResponse` but with `done: true` property included. This is not documented in the API nor in the website (AFAIK).

Could be cool if this was included since it's hard to otherwise handle the responses properly.

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[x] Documentation - Inconsistency between the docs and behaviour
[x] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Versions and Libraries (fill in the version numbers)
Cloudinary_NPM SDK version 1.36.1
Node - v18

**Comment by tamaracloudinary** [comment]
Hi there @TeemuKoivisto, 

Thanks for sharing your documentation feedback with us!

That’s a great point and we’ve opened a documentation ticket to improve this. We can update you when the fix is live, if you'd like.
We are continually working to improve the developer/user experience of our docs, and we really appreciate your input.

Best regards,
Tamara

**Comment by tamaracloudinary** [comment]
Hi @TeemuKoivisto, 

How are you?

I wanted to update you that a fix for the issue was deployed. Please see the note in our docs here: 
https://cloudinary.com/documentation/upload_images#chunked_asset_upload
Please let me know if you have questions, and thank you for your patience.

Best,
Tamara

**Comment by TeemuKoivisto** [comment]
Hey, all right. It would be nice if the npm package could be updated as well - it's rather hard to find these things from the documentation. This is what I ended up doing:

```ts
export type CloudinaryUploadResponse =
  | CloudinaryUploaded
  | CloudinaryPartialUpload;
export type CloudinaryUploaded = UploadApiResponse & { done?: true };
export interface CloudinaryPartialUpload {
  done: false;
  bytes: number;
  kind: string;
  resource_type: ResourceType;
  public_id: string;
}
```

**Comment by tamaracloudinary** [comment]
Hi @TeemuKoivisto 
Thanks for that, I added your note to our internal ticket :)
