### ISSUE TITLE
Cloudinary API corrupts UTF-8 public IDs/file names

### ISSUE THREAD

**Issue by lionel-rowe** [cloudinary/cloudinary_npm#607]
There doesn't seem to be a separate repo for the REST API, so I'm putting this here.

_Background: I'm using [Deno](https://deno.land/), which gives `error: Uncaught Error: Dynamic require of "proxy-agent" is not supported` when I try to import via https://esm.sh/cloudinary@1.36.4. Maybe worth opening a separate issue for that, but my use case is pretty simple, so I'd prefer to just use a simple `fetch` request rather than adding bloat by pulling in a whole SDK._

## Explain your use case

I'm trying to [upload a file](https://cloudinary.com/documentation/image_upload_api_reference) via POST request. Everything seems to be working OK, except when the file name contains non-ASCII characters. For example, if `public_id` in my request is "蜡笔小新", the `public_id` returned in the response is "è¡ç¬å°æ°".

When I run the Node SDK in runkit, I notice it deals gracefully with UTF-8 `public_id`s, but I can't figure out how from skimming the code. Perhaps this should be added to the documentation? Not sure if it counts as a bug per se, but usually I just assume modern web APIs will automatically use UTF-8 as default.

## Describe the problem you’re trying to solve

My code looks like this:

```ts
const config = {
    cloudName: getEnvVar('CLOUDINARY_CLOUD_NAME'),
    apiKey: getEnvVar('CLOUDINARY_API_KEY'),
    secretKey: getEnvVar('CLOUDINARY_SECRET_KEY'),
}

const url = `https://api.cloudinary.com/v1_1/${config.cloudName}/image/upload`

const opts = {
    public_id: file.name.split('.').slice(0, -1).join('.'),
    timestamp: String(Math.floor(Date.now() / 1000)),
    // use_filename: true,
}

// don't use any URL encoding etc. otherwise signature won't work
const naiveQps = Object.keys(opts).sort().map(k => `${k}=${opts[k as keyof typeof opts]}`).join('&')

const signature = toHashString(
    await crypto.subtle.digest('SHA-1', new TextEncoder().encode(naiveQps + config.secretKey)),
)

const formData = new FormData()

for (const [k, v] of Object.entries({
    ...opts,
    file,
    api_key: config.apiKey,
    signature,
})) {
    formData.append(k, v)
}

const res = await fetch(url, { method: 'POST', body: formData })
const data: CloudinaryResponseData = await res.json()
```

If I comment out `public_id` and uncomment `use_filename` under `opts`, the same problem still occurs (for a filename of "蜡笔小新.gif").

**Comment by rnamba-cloudinary** [comment]
Hi @lionel-rowe 

Would you please open up a support ticket with our team at support@cloudinary.com as we will need to enable an account level flag to enable special characters as a public_id.

**Comment by lionel-rowe** [comment]
@rnamba-cloudinary I don't think that's correct — as I say, the SDK handles it, I just can't figure out what it's doing differently. Gonna try setting up a throwaway Node project and spying on its network requests to figure out what's going on.

Also, if there's a flag for this, shouldn't it just be turned on by default? Multilingual support must be a pretty common retirement for a global CDN.
