### ISSUE TITLE
Cloudinary Integration using Node.js

### ISSUE THREAD

**Issue by mukulgupta2507** [cloudinary/cloudinary_npm#61]
0
down vote
favorite
	

I'm trying to integrate Cloudinary in my project for uploading images. I have just started using following links:

http://cloudinary.com/documentation/node_image_upload https://github.com/cloudinary/cloudinary_npm/blob/master/samples/basic/basic.js

I stuck at a point where I can see image uploaded to Cloudinary in my dashboard but in my code the response is undefined.

```
cloudinary.config(config.cloudinaryConfig);
function uploadFileInCloudinary(fileObj, callback) {
    console.log(fileObj);
    if(fileObj && (fileObj != undefined)) {
        console.log(fileObj['path']);
        cloudinary.uploader.upload(fileObj['path'], function(err, result) {
            if(err) {
                callback(err);
            }
            console.log("cloudinary result");
            console.log(JSON.stringify(result));  // undefined
            callback(null, result);
        });
    } else {
        callback("error");
    }
}
```
why is it so ? Can anyone give me some pointers where am I doing wrong ?

**Comment by taragano** [comment]
Please use the `v2` upload API instead, for example:

```
cloudinary.v2.uploader.upload(fileObj['path'], function(err, result) {
  ...
});
```

**Comment by mukulgupta2507** [comment]
@taragano 

Thanks for the response. But I was already working with v2 version. I solved my problem with using return statement before calbacks.

**Comment by taragano** [comment]
Thank you for the update, I'm glad it's working for you now :)
I'm closing this discussion now, but please feel free to re-open it if you need any further assistance.

**Comment by Bimpong** [comment]
hi, please can you share you code for solving this problem? im having the same difficulty and cant get past it

**Comment by yakirp** [comment]
Hey @Bimpong ,

Could you please share more information about your issue? Maybe you can share your code here?

Thanks,
--Yakir

**Comment by Bimpong** [comment]
Good to see we can still get some propmt responses here. Fortunately though i managed to solve it a few moments after coming accross this thread and that was by using the version 2 of the api as i believe was also mentioned above...

thanks a bunch
-Bimpong

**Comment by Bimpong** [comment]
If i might trouble you a little though, im a bit confused with a few tasks im to perform with these file/image upload activities with cloudinary/multer/mern-stack...

Three activities to be precises; one of which is to:
create an event which needs:
~a title
~venue
~date and time
~and where cloudinary comes in, upload an image(poster kinda thing)

Now what i want to know is how to send all these information as well as upload the image to cloudinary and store its url along with all other information submitted to the database(mongodb if possible)

sorry if this seems like an obvious thing... I'm actually a bit of a noob to this stuff . Any help you can provide will really be appreciated

Hope to read from you real soon
-Bimpong

**Comment by yakirp** [comment]
Hey @Bimpong ,

Well, you can send all this data as a JSON object to your server after you uploaded the image to Cloudinary.

`
 {
    "title": "Karaoke with friends",
    "venue": "Karaoke club",
    "date ": "10/7/2018",
    "image_url" : "http://res.cloudinary.com/yakir/image/upload/c_fill,f_auto,h_340,q_auto,w_510/gww3mshpecum78lklakx"
  }
`

Cheers,
--Yakir
