### ISSUE TITLE
When will Cloudinary support node 18 or a later version?

### ISSUE THREAD

**Issue by alamgir8** [cloudinary/cloudinary_npm#613]
I'm trying to use Cloudinary with lasted Node version 18, as Node.js 14 reached [official end of life] on April 30th, 2023. Node.js 16 will reach [official end of life] on September 11, 2023. But it's not working as aspected.

So when will Cloudinary support node Version 18 or later?

**Comment by aleksandar-cloudinary** [comment]
Hi @alamgir8, Thanks for reporting. Could you please share a bit more details about what isn't working once you upgraded to Node JS version 18? Do you have trouble installing the SDK or any errors during runtime etc?

**Comment by alamgir8** [comment]
Hi @aleksandar-cloudinary I'm trying to delete an image from the **client side in react app** and my configuration is like this

import cloudinary from "cloudinary/lib/cloudinary";

cloudinary?.config({
  cloud_name: import.meta.env.VITE_APP_CLOUD_NAME,
  api_key: import.meta.env.VITE_APP_CLOUDINARY_API_KEY,
  api_secret: import.meta.env.VITE_APP_CLOUDINARY_API_SECRET,
});

and inside the delete function calling the Cloudinary uploader to destroy/delete the image

await cloudinary.v2.uploader.destroy(public_id);

It worked properly on Node version 16 but did not work on Node version 18

**Comment by tamaracloudinary** [comment]
Hi @alamgir8 , you can try updating your Cloudinary library to the latest version. Please try running the following command in your project directory `npm install cloudinary@latest` or if you are using yarn, you can run: `yarn add cloudinary@latest`.This will update the Cloudinary library to the latest version available.

Additionally, if you are using any other dependencies or plugins alongside Cloudinary, ensure that they are also compatible with Node.js 18 and up-to-date.

Please let me know if the issue was resolved.

**Comment by alamgir8** [comment]
Hi @tamaracloudinary i'm using **Cloudinary** latest version   **"cloudinary": "^1.37.1",**. Also tried to re-install this **npm install cloudinary@latest**, but still had the same issue, it crashed the app.

And all other packages are compatible with **Node 18**, I checked that..

**Comment by rnamba-cloudinary** [comment]
Hey @alamgir8 any chance you can send us a reproducible environment for us to test in?

**Comment by tamaracloudinary** [comment]
Hi @alamgir8, if you are using react (front-end) `import cloudinary from "cloudinary/lib/cloudinary";` you can't configure cloudinary using node.js code `cloudinary.config({ cloud_name...` if you want to delete assets from the client side, please refer to the docs here: https://cloudinary.com/documentation/upload_images#deleting_client_side_uploaded_assets

Subject: Regarding Cloudinary Configuration and Client-Side Asset Deletion

Hi @alamgir8, if you are using React on the front-end, the following import statement is typically used to import the Cloudinary library:

```javascript
import cloudinary from "cloudinary/lib/cloudinary";
```

However, it is important to note that configuring Cloudinary using Node.js code, specifically `cloudinary.config({ cloud_name...`, is not compatible with the front-end implementation in React. 

Regarding the deletion of assets from the client side, we recommend referring to our documentation, which provides detailed instructions on the process. You can find the relevant information at the following link:[https://cloudinary.com/documentation/upload_images#deleting_client_side_uploaded_assets](https://cloudinary.com/documentation/upload_images#deleting_client_side_uploaded_assets)

Thanks
-Tamara
