### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by Boby900** [cloudinary/cloudinary_npm#617]
**while uploading the media it's showing invalid signature in the console**

## Error screenshots
![Screenshot (90)](https://github.com/cloudinary/cloudinary_npm/assets/111265239/492aea2c-e67d-4c9d-b0c1-5d4d9cdc17db)

## Versions and Libraries (fill in the version numbers)
Cloudinary_NPM SDK version: "^1.37.2",

## Config Files (Please paste the following files if possible)
Package.json
![Screenshot (91)](https://github.com/cloudinary/cloudinary_npm/assets/111265239/e8bc7068-e9d5-4a9c-967d-e653e87bc6f0)

## Repository
https://github.com/Boby900/social-media-app

**Comment by aleksandar-cloudinary** [comment]
Hi @Boby900, Thanks for reporting. May I please ask you to double-check your `.env` file (where you have your Cloudinary credentials) and ensure you do not have quotes around your API Secret? If you do, please remove them, save the file and retry the upload request to Cloudinary.

**Comment by Boby900** [comment]
thanks @aleksandar-cloudinary removing the double quotes fixed my issue.
