### ISSUE TITLE
Cloudinary Upload Request getting Timed Out for images of size greater than 50 Kb

### ISSUE THREAD

**Issue by mukulgupta2507** [cloudinary/cloudinary_npm#62]
Hi,

While uploading files of greater than 50 kb, I'm getting timed out from cloudinary response.

```
message: 'Request Timeout', http_code: 499
```

Code:
```
cloudinary.config(config.cloudinaryConfig);  // config of cloudinary

function uploadFileInCloudinary(fileObj, callback) {
	console.log(fileObj);
	if(fileObj && (fileObj != undefined)) {
		console.log(fileObj['path']);
		cloudinary.uploader.upload(fileObj['path'], function(err, result) {
			if(err) {
				console.log(err);
				return callback(err);
			}
			console.log("cloudinary result");
			console.log(JSON.stringify(result));
			return callback(null, result);
		});
	} else {
		return callback("error");
	}
}
```

Can anyone give me some pointers if this expected behaviour or I'm missing anything ?

Thanks

**Comment by taragano** [comment]
I'm sorry for my response delay.

Does this issue still happen for you?

We're can't be sure of why the error was returned. This seems to be related to an invalid data sent to Cloudinary as the uploaded file. Specifically, we believe there was no data sent to Cloudinary for 60 seconds, therefore a 'Timeout' error was returned, this is usually due to a non-optimal internet connection.

If you still get similar issues now, please share some more information and we'll be happy to assist.

**Comment by mukulgupta2507** [comment]
Yes, this behavior is observed on slow internet connection so far. I'm closing this for now, will open it if issues is observed frequently.

Thanks

**Comment by knownasilya** [comment]
I'm experiencing something similar I think, code looks like this:

```js
var THUMBNAIL_OPTIONS = { width: 320, height: 320, crop: 'limit', format: 'jpg', type: 'private' };
var MAX_FILE_SIZE = 1000 * 1000 * config.get('cloudinary.maxFileSizeMB');

function uploadFile(file) {
  log.info('uploadFile()', file.filename);

  return new Promise(function (resolve, reject) {
    var notStream = cloudinary.uploader.upload_stream(function (result) {
      log.info('Upload result from cloudinary: ', result);

      if (result.public_id) {
        resolve(result);
      } else {
        reject(new Error('Result does not contain a public_id'));
      }

    }, THUMBNAIL_OPTIONS);
    file.file.pipe(through(function (chunk, _, next) {
      notStream.write(chunk);
      next();
    }, function (next) {
      notStream.end();
      next();
    }));
  });
}
```

**Comment by Floby** [comment]
Same issue here.

**Comment by roeeba** [comment]
The default client-side timeout is indeed 60 seconds. We highly recommend setting a larger timeout in slow network conditions. You can override the default timeout setting, like this:

`cloudinary.v2.uploader.upload('my_image.jpg', {timeout:120000}, function(error,result){});`

**Comment by nvtuanqti212** [comment]
Do we have any solution for this problem, i have tried all above solutions but not work for me

**Comment by mgriff** [comment]
Hi @nvtuanqti212, usually this error is due to a slow connection meaning no data is sent within the defined data limit

Are you able to share a code snippet with the upload parameters you are setting?

**Comment by kvatul** [comment]
I was also facing same problem , I **just change my wifi address**, It is **working perfect** 😀. Although previosly I was using wifi brodband , but it was giving time out error, I check it by change wify by my mobile, It is working fine

**Comment by Sukh767** [comment]
I am facing the same issues. I wasted two days, and I don't understand where the error is. Suddenly, it's working, but most of the time, I encounter an error.

--------------CODE--------------------
Cloudinary upload error: {
  error: { message: 'Request Timeout', http_code: 499, name: 'TimeoutError' }
}
Failed to upload image at index 0
Cloudinary upload error: {
  error: { message: 'Request Timeout', http_code: 499, name: 'TimeoutError' }
}
Failed to upload image at index 1

My code---
-------------------Routes setup---------------------
router.post('/create-product', protectRoute, adminRoute, upload.fields([{
    name: 'images',
    maxCount: 5
}]),createProduct)
-----------------Controller-------------------------
export const createProduct = async (req, res) => {
  try {
    const {
      name,
      description,
      price,
      discount = 0,
      category,
      brand,
      stock,
      isFeatured = false,
    } = req.body;

    // console.log('Request body:', req.body);
    // console.log('Uploaded files:', req.files);

    if (!name || !description || !price || !category || !brand || !stock) {
      return res.status(400).json({
        success: false,
        message: 'All fields are required.',
      });
    }

    if (!req.files || !req.files.images || req.files.images.length === 0) {
      return res.status(400).json({
        success: false,
        message: 'At least one image is required.',
      });
    }

    let imageLocalPath = req.files.images;
    let imageArray = [];

    for (let i = 0; i < imageLocalPath.length; i++) {
      const imageLinks = imageLocalPath[i]?.path;
      // console.log('Image path:', imageLinks);
    
      const result = await uploadOnCloudinary(imageLinks);
      if (result) {
        imageArray.push({
          public_id: result.public_id, // Map public_id to publicId
          url: result.secure_url || result.url, // Use secure_url if available
        });
      } else {
        console.error(`Failed to upload image at index ${i}`);
      }
    }    

    if (imageArray.length === 0) {
      return res.status(400).json({
        success: false,
        message: 'Failed to upload images to Cloudinary.',
      });
    }

    const product = await Product.create({
      name,
      description,
      price,
      discount,
      category,
      brand,
      stock,
      images: imageArray,
      isFeatured,
    });

    res.status(201).json({
      success: true,
      message: 'Product created successfully',
      product,
    });
  } catch (error) {
    console.error('Error creating product:', error.message);
    res.status(500).json({
      success: false,
      message: 'Failed to create product. Please try again later.',
      error: error.message,
    });
  }
};

export const deleteProduct = async (req, res) => {
  try {
    const { id: productId } = req.params; // Extract productId from route parameters

    // Check if the product exists
    const product = await Product.findById(productId);
    if (!product) {
      return res.status(404).json({
        success: false,
        message: "Product not found",
      });
    }

    // Delete all images associated with the product
    if (product.images && Array.isArray(product.images)) {
      for (const image of product.images) {
        try {
          if (image.public_id) {
            await cloudinary.uploader.destroy(image.public_id);
            console.log(`Deleted image ${image.public_id} from Cloudinary`);
          }
        } catch (error) {
          console.error(`Failed to delete image ${image.public_id} from Cloudinary`, error);
        }
      }
    }

    // Delete the product from the database
    await product.deleteOne();

    res.status(200).json({
      success: true,
      message: "Product deleted successfully",
    });
  } catch (error) {
    console.error("Error deleting product:", error.message);
    res.status(500).json({
      success: false,
      message: "Failed to delete product. Please try again later.",
      error: error.message,
    });
  }
};

-----------------Cloudinary-------------------
import { v2 as cloudinary } from "cloudinary";
import dotenv from 'dotenv'
import fs from 'fs'

dotenv.config()

cloudinary.config({
    cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
    api_key: process.env.CLOUDINARY_API_KEY,
    api_secret: process.env.CLOUDINARY_API_SECRET,
})

export const uploadOnCloudinary = async (path) => {
    try {
      if (!path) throw new Error('File path is missing');
  
      const response = await cloudinary.uploader.upload(path, { resource_type: 'auto' });  
      // Remove the temporary file after upload
      fs.unlinkSync(path);
      return response;
    } catch (error) {
      console.error('Cloudinary upload error:', error);
      fs.unlinkSync(path); // Clean up the file in case of an error
      return null;
    }
}; 

export const deleteFromCloudinary = async (publicId) => {
  try {
    const result = await cloudinary.uploader.destroy(publicId);
    console.log(`Deleted ${publicId} from Cloudinary`);
    return result;
  } catch (error) {
    console.error(`Failed to delete ${publicId} from Cloudinary`, error);
    throw error;
  }
};

----------------Multer---------------
import multer from "multer";


const storage = multer.diskStorage({
    destination: function (req, file, cb) {
      cb(null, './public/temp'); // Save files here
    },
    filename: function (req, file, cb) {
      cb(null, `${Date.now()}-${file.originalname}`); // Generate unique filenames
    },
  });
  
  export const upload = multer({ storage });
  
Am I missing Something?
Need any Information ?

**Comment by Sukh767** [comment]
> The default client-side timeout is indeed 60 seconds. We highly recommend setting a larger timeout in slow network conditions. You can override the default timeout setting, like this:
> 
> `cloudinary.v2.uploader.upload('my_image.jpg', {timeout:120000}, function(error,result){});`

I don't think it will work anymore. I have tried and encountered module errors.
      return callback(result.error);
             ^

TypeError: callback is not a function
    at /home/sukh_ranjan/workspace/Volt-and-vogue/node_modules/cloudinary/lib/utils/index.js:1394:14
    at handle_response (/home/sukh_ranjan/workspace/Volt-and-vogue/node_modules/cloudinary/lib/uploader.js:490:7)
    at ClientRequest.<anonymous> (/home/sukh_ranjan/workspace/Volt-and-vogue/node_modules/cloudinary/lib/uploader.js:607:12)
    at ClientRequest.emit (node:events:530:35)
    at emitErrorEvent (node:_http_client:101:11)
    at TLSSocket.socketCloseListener (node:_http_client:477:7)
    at TLSSocket.emit (node:events:530:35)
    at node:net:343:12
    at TCP.done (node:_tls_wrap:648:7)

Node.js v20.18.1
[no

**Comment by Nikhil273** [comment]
Can Anyone Gives Me Exact Solution...

**Comment by Sukh767** [comment]
```
import { v2 as cloudinary } from "cloudinary"
import dotenv from 'dotenv'
import fs from 'fs'

dotenv.config()

cloudinary.config({
    cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
    api_key: process.env.CLOUDINARY_API_KEY,
    api_secret: process.env.CLOUDINARY_API_SECRET,
})

export const uploadOnCloudinary = async (path, retries = 3) => {
  try {
    if (!path) throw new Error("File path is missing");

    const response = await cloudinary.uploader.upload(path, { resource_type: "auto" });

    // Remove the temporary file after upload
    fs.unlinkSync(path);
    return response;
  } catch (error) {
    console.error("Cloudinary upload error:", error);

    // Retry logic for timeout errors
    if (retries > 0 && error.error?.http_code === 499) {
      console.log(`Retrying upload... Attempts left: ${retries - 1}`)
      return uploadOnCloudinary(path, retries - 1);
    }

    // Ensure temporary files are cleaned up in case of an error
    if (fs.existsSync(path)) fs.unlinkSync(path)
    return null;
  }
}
```

**Comment by tommyg-cld** [comment]
if you are still experiencing issues with timeouts even after increasing it, I suggest opening a ticket via https://support.cloudinary.com/hc/en-us/requests/new
