### ISSUE TITLE
cloudinary.url() promise

### ISSUE THREAD

**Issue by stellanhaglund** [cloudinary/cloudinary_npm#63]
Wouldn't it be good with a promise on cloudinary.url()

I'm trying to get images by sending a request to an external node server but the image isn't loaded when the response is sent so to do 

cloudinary.url().then(function(data){
res.json(data)
})

would be good..

**Comment by stellanhaglund** [comment]
Tried this and it worked fine...

    var q = require('q');
    var deferred = q.defer();
    exports.url = function(public_id, options) {
        options = _.extend({}, options);
        var bang = cloudinary.utils.url(public_id, options);
        deferred.resolve(bang);
        return deferred.promise;
    };

**Comment by tocker** [comment]
`cloudinary.utils.url()` only *computes* the URL and so returns immediately. It has no way of knowing if the resource represented by the public_id has been uploaded yet, and so is immediately resolved.
`cloudinary.uploader.upload` returns a promise. If you need to send the uploaded resource URL to the remote after the resource was uploaded, you can do something like this:

```
// API v2
cloudinary.uploader
  .upload( image)
  .then( function(result) {
    sentToRemoteNode(result.secure_url);
  });
```

**Comment by timendez** [comment]
@tocker is there any documentation for promises with cloudinary? I can't find any

**Comment by tocker** [comment]
We are working on new documentation for our JavaScript libraries.
