### ISSUE TITLE
Escaping overlay text seems impossible in the version 1.41.0

### ISSUE THREAD

**Issue by DenisLaboureyras** [cloudinary/cloudinary_npm#632]
## Describe the bug in a sentence or two.
When I want to use the overlay text transformation, I can't use the slash / character, or comma. It was working fine with a previous version (I was escaping manually these characters, thanks to this article : https://support.cloudinary.com/hc/en-us/articles/202521512-How-to-add-a-special-characters-in-text-overlays-).

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] Performance - Performance issues
[X] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce

Use the following function:
` 
await cloudinary.uploader.upload(url, {
      transformation: [
        {
          overlay: {
            text: 'text with a slash / or an escaped slash %E2%88%95',
          },
        },
      ],
    });
`
The generated file will have escaped characters instead of /

## Versions and Libraries (fill in the version numbers)
Cloudinary_NPM SDK v1.41.0
Node - 18.10.0

**Comment by esguerrat** [comment]
Hi there, 

Thanks for reaching out. I am checking on this with the development team and I will get back to you as soon as possible.

Kind regards, 

Tia

**Comment by momoip** [comment]
Hi DenisLaboureyras,
Please note that we are working on a fix and will keep you updated when it's deployed.
Regards,
Mo

**Comment by DenisLaboureyras** [comment]
Thanks a lot !

**Comment by momoip** [comment]
Hi DenisLaboureyras,
You're very welcome.  I will let you know when the fix is complete.
Regards,
Mo

**Comment by tommyg-cld** [comment]
@DenisLaboureyras I'm afraid there is still no ETA for the fix currently but will update you as soon as we know more.

**Comment by DenisLaboureyras** [comment]
Seems fixed in v2.3.0

**Comment by tommyg-cld** [comment]
@DenisLaboureyras thx for the update and apologies for the lack of updates. Glad it's working now.
