### ISSUE TITLE
Support passing in analytics product version to URL generation

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary/cloudinary_npm#634]
Currently the SDK doesn't support passing in the product version (A, B, etc) which prevents being able to use this for other packages that need to use a version other than B.

## Explain your use case

I'd like to be able to support analytics in Netlify Cloudinary as well as any other integration that makes use of algorithm B.

Netlify Cloudinary reference: https://github.com/cloudinary-community/netlify-plugin-cloudinary/pull/87

## Do you have a proposed solution?

The URL Gen SDK supports passing in `product` alongside `sdkCode` and `sdkSemver`

**Comment by victorli-cloudinary** [comment]
Hey @colbyfayock , looks like this change was included with the 2.0.1 release, could you have a look and confirm if everything is OK on your end?

**Comment by colbyfayock** [comment]
just tested it out and it looks like we're good to go. thanks!
