### ISSUE TITLE
Typescript error on search API

### ISSUE THREAD

**Issue by Bilboramix** [cloudinary/cloudinary_npm#636]
## Describe the bug in a sentence or two.
Typescript is showing a type error when using v2.api.search() : The first parameter of the function is defined as a string.

[The doc](https://cloudinary.com/documentation/admin_api#search_for_resources) should be more explicit about what type to use with the function.
It also show a .execute() chain call that lead to the error `execute is not a function`

## Issue Type 

Documentation - Inconsistency between the docs and behaviour
Incorrect Types - For typescript users who are having problems with our d.ts files

## Error screenshots
![image](https://github.com/cloudinary/cloudinary_npm/assets/91626615/ff348f7e-5d4e-46ce-a136-8f16f6fcbd63)

## Doc suggestion :
Change
![image](https://github.com/cloudinary/cloudinary_npm/assets/91626615/f95538bd-0aa9-4e3e-a0c7-0d3e5cc24060)

To
![image](https://github.com/cloudinary/cloudinary_npm/assets/91626615/e0411cf5-2af3-4d34-9b59-64e8cd682bf0)

Add a little reminder to say that this syntax is not valid :
https://github.com/adentranter/adentranter.com/blob/1d167feb91d370a111adca7d4fbbf7b81cf8c5b0/src/utils/cachedImages.ts#L8

Regards, Bill.

**Comment by tommyg-cld** [comment]
@Bilboramix thx for raising this and apologies for the delay - so this is a known issue that we hope to address it soon.

**Comment by victorli-cloudinary** [comment]
Hi @Bilboramix , just wanted to update you that we've added a fix so that searches can be executed without a query, which is consistent with the example in the documentation you pointed out, that wasn't previously working. Thanks for bringing this to our attention! I believe the change will be live early next week.
