### ISSUE TITLE
Different colors for the same image

### ISSUE THREAD

**Issue by jifeon** [cloudinary/cloudinary_npm#64]
I'm trying to upload one image, and always get different results for colors:

``` bash
> c.uploader.upload('http://res.cloudinary.com/dlvphoomb/image/upload/v1441577895/m8wm8q4fnqqtegdumsog.png', function(result){console.log(result.colors)}, {colors: true})
[object Object]
> [ [ '#FF0000', 60 ], [ '#00FF00CC', 40 ] ]
> c.uploader.upload('http://res.cloudinary.com/dlvphoomb/image/upload/v1441577895/m8wm8q4fnqqtegdumsog.png', function(result){console.log(result.colors)}, {colors: true})
[object Object]
> [ [ '#FF0000', 60 ], [ '#00FF005A', 40 ] ]
> c.uploader.upload('http://res.cloudinary.com/dlvphoomb/image/upload/v1441577895/m8wm8q4fnqqtegdumsog.png', function(result){console.log(result.colors)}, {colors: true})
[object Object]
> [ [ '#FF0000', 60 ], [ '#00FF002C', 40 ] ]
> c.uploader.upload('http://res.cloudinary.com/dlvphoomb/image/upload/v1441577895/m8wm8q4fnqqtegdumsog.png', function(result){console.log(result.colors)}, {colors: true})
[object Object]
> [ [ '#FF0000', 60 ], [ '#00FF0017', 40 ] ]
> c.uploader.upload('http://res.cloudinary.com/dlvphoomb/image/upload/v1441577895/m8wm8q4fnqqtegdumsog.png', function(result){console.log(result.colors)}, {colors: true})
[object Object]
> [ [ '#FF0000', 60 ], [ '#00FF00', 40 ] ]
```

**Comment by tocker** [comment]
Hi @jifeon,

Thanks for using Cloudinary!
The issue you reported is known. The differences are in the *opacity* information. It should not interfere with normal operations.

**Comment by jifeon** [comment]
Ok, is there any estimate for it?

**Comment by tocker** [comment]
We do not have a milestone for this issue. Can you describe how this issue affects your application?

**Comment by jifeon** [comment]
I have a CMS which can setup sites. I use these colors to define a theme for the creating site after user  is uploaded a logo. I save these colors to CSS, but for CSS #00FF002C is not a valid color. So I must to trim it.

**Comment by tocker** [comment]
@jifeon, we cannot change the value as it is required for other uses. You'll need to trim the value to remove the opacity value for your application.
I'm closing the issue due to the elapsed time but please feel free to reopen if you require further assistance!

**Comment by jifeon** [comment]
The issue is not about color format, it's about sometimes you have alpha channel value and sometimes not, it's about inconsistency in API. I cannot rely on data cloudinary return me about the colors. In my case I can trim it, but maybe someone wants to receive color with alpha channel.

**Comment by jifeon** [comment]
> free to reopen

Looks like I have no rights to reopen issues

**Comment by tocker** [comment]
Hi @jifeon ,

This is now fixed:

```
> c.uploader.upload('http://res.cloudinary.com/dlvphoomb/image/upload/v1441577895/m8wm8q4fnqqtegdumsog.png', function(result){console.log(result.colors)}, {colors: true})
{ state: 'pending' }
> [ [ '#FF0000', 60 ], [ '#00FF00', 40 ] ]
> c.uploader.upload('http://res.cloudinary.com/dlvphoomb/image/upload/v1441577895/m8wm8q4fnqqtegdumsog.png', function(result){console.log(result.colors)}, {colors: true})
{ state: 'pending' }
> [ [ '#FF0000', 60 ], [ '#00FF00', 40 ] ]
> c.uploader.upload('http://res.cloudinary.com/dlvphoomb/image/upload/v1441577895/m8wm8q4fnqqtegdumsog.png', function(result){console.log(result.colors)}, {colors: true})
{ state: 'pending' }
> [ [ '#FF0000', 60 ], [ '#00FF00', 40 ] ]
> c.uploader.upload('http://res.cloudinary.com/dlvphoomb/image/upload/v1441577895/m8wm8q4fnqqtegdumsog.png', function(result){console.log(result.colors)}, {colors: true})
{ state: 'pending' }
> [ [ '#FF0000', 60 ], [ '#00FF00', 40 ] ]
> c.uploader.upload('http://res.cloudinary.com/dlvphoomb/image/upload/v1441577895/m8wm8q4fnqqtegdumsog.png', function(result){console.log(result.colors)}, {colors: true})
{ state: 'pending' }
> [ [ '#FF0000', 60 ], [ '#00FF00', 40 ] ]
```

BTW, you may find our sprite generator useful: http://cloudinary.com/documentation/sprite_generation

Combined with the transformation "co_rgb:aabbcc,e_colorize" (replace aabbcc with the right color) you can automatically create CSS sprites that match the theme!
