### ISSUE TITLE
Cloudinary.com Signup Process 

### ISSUE THREAD

**Issue by AbdulRehmanUNI** [cloudinary/cloudinary_npm#642]
![test](https://github.com/cloudinary/cloudinary_npm/assets/129224315/0d48e6d8-6962-45c7-b4c9-112c99fed58a)

Not Sure if this is the right place to suggest this issue about Cloudinary.com. Please guide me.

##Problem:
While signing up for Cloudinary.com, I mistakenly clicked in OTHER and wanted to click on the OPTIMIZE option. When i tried to unclick the other option i couldn't do so and the LET'S GO button was also disabled. So i had to click something in other even though i didn't want to.

##Solution: 
If the user tries to unselect the other button the two options in the other dropdown should stop appearing and user should be able to proceed to the next stage by selecting from the upper four options.

Please provide me feedback. I am new to open source contributions

**Comment by atdcloud** [comment]
Hii @AbdulRehmanUNI , 

Thank you for reaching out!  Can you please provide the direct URL to which page of cloudinary.com that you screenshot? 

Regards, 
Anthony

**Comment by AbdulRehmanUNI** [comment]
@atdcloud Sure. 
Here is the link: https://console.cloudinary.com/console/c-3391e1972a16aff6bc8e24e46c01f4/welcome

--> its the "/welcome" page

![image](https://github.com/cloudinary/cloudinary_npm/assets/129224315/f791359a-a214-4d97-ba0b-745d0bc3ce23)

**Comment by tommyg-cld** [comment]
@AbdulRehmanUNI thx, we'll report it internally.
