### ISSUE TITLE
upload_large using chunk_size is corrupting data

### ISSUE THREAD

**Issue by bompus** [cloudinary/cloudinary_npm#65]
I'm trying to upload an 8mb file ( type raw or image ) using a chunk_size of 6000000. What I am seeing is that on completion, the file size matches, but the file data is corrupted around the location of the second chunk.

I've tried several different files including dummy test files, jpegs, and pdfs of different sizes. If the file is transmitted using a single chunk ( chunk_size is larger than file size ) , the md5 matches. If multiple chunks are involved, the md5 is different, and the md5 changes as you experiment with different chunk sizes ( 5500000 vs 6000000 for example )

Can you update your tests for upload_large ( and all other upload tests? ) to check filesize AND compare etag/md5 to the original md5 to verify the uploaded data matches.

**Comment by bompus** [comment]
I've solved the problem in uploader.js and will be submitting a pull request shortly.

**Comment by bompus** [comment]
Any ETA on implementing the fix?

**Comment by TalLevAmi** [comment]
@bompus thanks for the PR! We have merged the request. We will release a new version next week.

**Comment by bompus** [comment]
@TalLevAmi any update on the release? I need the new version to hit npm to integrate into our build cleanly. Thanks!

**Comment by tocker** [comment]
@bompus A new version (1.2.5) was released yesterday to npm.
