### ISSUE TITLE
"Error: must supply api_key" in heroku log

### ISSUE THREAD

**Issue by zachsj** [cloudinary/cloudinary_npm#653]
## Bug report for Cloudinary NPM SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
Using Next.js.  Everything works fine when I run my app on the development side but after I deploy to Heroku and my site is in production, I see in the Heroku logs.. "Error: must supply api_key".  I set up the connection btwn my heroku acct and cloudinary acct as far as adding the CLOUDINARY_URL to config vars in heroku.

## Issue Type (Can be multiple)
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)

## Steps to reproduce
… if applicable

## Error screenshots
… if applicable

## Browsers (if issue relates to UI, else ignore)
[ ] Chrome

## Versions and Libraries (fill in the version numbers)
Cloudinary_NPM SDK version
Node - v20.11.0
NPM - 10.5.0

## Config Files (Please paste the following files if possible)
Package.json  see https://github.com/zachsj/P-Scraper

## Repository
https://github.com/zachsj/P-Scraper

**Comment by epasos573** [comment]
Could you try to re-deploy your code after adding the Cloudinary config vars in Heroku?

**Comment by zachsj** [comment]
As mentioned above I already had added that.  I think the issue is the setup in my next.config.mjs file, it seems like that needs to be set up and I don't see any instructions on how to do that.

**Comment by rnamba-cloudinary** [comment]
This has been recognized as not a bug and is related to configuration settings. 

We will continue the debugging within a support ticket as this is unrelated to the npm package.
