### ISSUE TITLE
error fetching photos by folder 

### ISSUE THREAD

**Issue by aliosmandev** [cloudinary/cloudinary_npm#667]
https://cloudinary.com/documentation/admin_api#get_resources_by_asset_folder_examples

When I request the api in the above document with sdk, it gives the error at the bottom and when I try it in postman, it says page not found

Postman Error;
<img width="1059" alt="Screenshot 2024-07-01 at 01 46 26" src="https://github.com/cloudinary/cloudinary_npm/assets/106361546/61839eab-9743-44bf-8606-51bdcbbc5b1d">

SDK Error;
<img width="908" alt="Screenshot 2024-07-01 at 01 47 41" src="https://github.com/cloudinary/cloudinary_npm/assets/106361546/1601b412-ca01-4192-a013-a876a34e4fa4">

**Comment by michalkcloudinay** [comment]
Hi @aliosmandev,

This feature is not supported for clouds using the legacy fixed folder mode (which is the setting on your cloud).  
You can read more about this here: https://cloudinary.com/documentation/folder_modes#checking_your_product_environment_folder_mode

Please let us know if you need any further assistance. 
Thanks,
Michal

**Comment by aliosmandev** [comment]
Thank you for your information, actually my main problem is that when I add the prefix, the direction is not correct, that is, I do "desc", it should come from top to bottom, but it does not come in order, I wonder if I am using it incorrectly.

![Screenshot 2024-07-01 at 18 27 42](https://github.com/cloudinary/cloudinary_npm/assets/106361546/da70fc91-3669-4e82-a508-c171fcf05b15)

**Comment by michalkcloudinay** [comment]
Hi @aliosmandev,

When including the "prefix" parameter, the "direction" parameter is ignored. 
You can read more about this here: https://cloudinary.com/documentation/admin_api#get_resources (under `direction`).

Please let us know if you have any further questions.

Thanks,
Michal
