### ISSUE TITLE
Generate upload signatures

### ISSUE THREAD

**Issue by cohix** [cloudinary/cloudinary_npm#67]
There is no documentation that I can find on generating secure upload signatures for upload clients. The iOS documentation says that the serverside SDKs should support this but I cannot find documentation. Please advise. Thanks!

**Comment by TalLevAmi** [comment]
You can use [cloudinary.utils.sign_request] (https://github.com/cloudinary/cloudinary_npm/blob/master/src/utils.coffee#L491)
to generate the signature and add the api_key to the request.

**Comment by tocker** [comment]
Closing this issue as it seems to be resolved.
