### ISSUE TITLE
Working with es6 modules?

### ISSUE THREAD

**Issue by flo-sch** [cloudinary/cloudinary_npm#68]
Hey,

I am just trying to import the package in an es6 app,
But I've got an error from the sources of the `chunking-stream` dependency module.

Basically, just the call of :

```
import cloudinary from 'cloudinary';
```

throws an error : `Uncaught Error: Cannot find module './lib/size-chunker'`

My environment :

```
node: v0.12.4
cloudinary: v1.2.5

// For the story, I am building a mobile app in es6 using React.js
browserify: v11.1.0
babelify: v6.3.0
react: v0.14.0
```

**Comment by Flo-Schield-Bobby** [comment]
It seems to work better now as of `1.3.0`.
However, it causes another error `Cannot find module 'coffeeify'`, which can be solved by running `npm install coffeeify`.

Could you please consider :
- Either include the `Coffeeify` browserify transform as a dependency of this package
- Or even better (in my opinion), switch from CoffeeScript to JavaScript (eventually ES6), as this package targets the npm community, and is not especially related to a CoffeeScript usage ?

**Comment by tocker** [comment]
@flo-sch for ReactJS, please use cloudinary-core instead of this library.

```
npm install lodash
npm install cloudinary-core
```

The name of the library is `cloudinary-core`, so to import the entire namespace, use the following code:
```javascript
import * as cloudinary from 'cloudinary-core';

var html = cloudinary.ImageTag.new( "sample", { cloud_name: "demo", width: 200, crop: "scale"}).toHtml();
```
