### ISSUE TITLE
Unable to delete raw file

### ISSUE THREAD

**Issue by ehtshamaziz** [cloudinary/cloudinary_npm#681]
Public Id: 65b6a4feda9bcf834d99ae28

        // Delete the file from Cloudinary
        const result = await cloudinary.uploader.destroy(publicId, { resource_type: "raw" })
        console.log("Cloudinary delete result:", result);
        
 I am unable to delete file from cloudinary, it gives me result not found error.

**Comment by tommyg-cld** [comment]
@ehtshamaziz with raw files, the file extension is part of the public_id so you need to include it in your API call. 

e.g. 
` const result = await cloudinary.uploader.destroy("65b6a4feda9bcf834d99ae28.json", { resource_type: "raw" })
    console.log("Cloudinary delete result:", result);`

hope this helps.

**Comment by ehtshamaziz** [comment]
> @ehtshamaziz with raw files, the file extension is part of the public_id so you need to include it in your API call.
> 
> e.g. ` const result = await cloudinary.uploader.destroy("65b6a4feda9bcf834d99ae28.json", { resource_type: "raw" }) console.log("Cloudinary delete result:", result);`
> 
> hope this helps.



> @ehtshamaziz with raw files, the file extension is part of the public_id so you need to include it in your API call.
> 
> e.g. ` const result = await cloudinary.uploader.destroy("65b6a4feda9bcf834d99ae28.json", { resource_type: "raw" }) console.log("Cloudinary delete result:", result);`
> 
> hope this helps.

Thankyou, It worked.
