### ISSUE TITLE
Default image url for widget.

### ISSUE THREAD

**Issue by nonelove** [cloudinary/cloudinary_npm#69]
Hi team,

There is no option to set a remote image url when a cloudinary widget is opened. Could you add the option?

Thanks.

**Comment by taragano** [comment]
I'm sorry for my response delay.

I'm sorry, but I'm not sure I fully understand your question. Can you please share some more information, maybe with an example?

Thanks

**Comment by nonelove** [comment]
We have another widget to get an image url to upload it to Cloudinary. After choosing an image in our widget, we close the widget and open cloudinary widget to upload the image. But, we can't write the image url to Cloudinary widget on behalf of the user. It would be very convenient if the default upload url setting for Cloudinary widget.

Thanks.

**Comment by nonelove** [comment]
I need a default url for the page below.

![screen shot 2015-12-21 at 11 50 01 am](https://cloud.githubusercontent.com/assets/7032221/11922289/2be29f44-a7d9-11e5-9b60-a1e7da39ca1b.png)

**Comment by roeeba** [comment]
Hi @nonelove : Apologies for our very delayed response. Thank you very much for your suggestion. we've passed this on to our dev team to consider supporting this in the future versions of our widget.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please check our latest version of the widget (v2). If the request is still relevant, please feel free to either re-open the issue or contact our support at http://support.cloudinary.com.
