### ISSUE TITLE
newest version seems to have a problem

### ISSUE THREAD

**Issue by PedroEsperanca** [cloudinary/cloudinary_npm#70]
I'm getting this error:

```javascript
SyntaxError: /var/www/html/example.com/node_modules/cloudinary/node_modules/lodash/index.js:7591
    /**
    ^^^
Unexpected token ILLEGAL
```

**Comment by tocker** [comment]
The error seems to be in the lodash code, not Cloudinary. 
Can you please provide the full error stack so we can trace it?

**Comment by tocker** [comment]
@PedroEsperanca I'm closing this issue since we didn't get any update. If this is still an issue please feel free to reopen the issue!
