### ISSUE TITLE
Some eager transformations does not return width/height of the new image

### ISSUE THREAD

**Issue by frenzzy** [cloudinary/cloudinary_npm#71]
##### Example 1 - all is good:
```js
cloudinary.uploader.explicit('id', function (result) {
  console.log(result);
  /*{
    // ...
    width: 3264,
    height: 2448,
    eager: [
      {
        width: 662,          <=== SIZE AVAILABLE
        height: 496,
        url: '...',
        secure_url: '...'
      }
    ]
  }*/
}, {
  type: 'upload',
  eager: {
    transformation: [
      {
        crop: 'crop',
        x: 0,
        y: 0,
        width: 3264,
        height: 2445
      },
      {
        crop: 'limit',
        width: 1140,
        height: 496,
        gravity: 'center',
        quality: 90,
        flags: 'progressive',
        format: 'jpg'
      }
    ]
  }
});
```

##### Example 2 - width and height are unavailable:
```js
cloudinary.uploader.explicit('id', function (result) {
  console.log(result);
  /*{
    // ...
    width: 3264,
    height: 2448,
    eager: [
      {
                            <=== WHERE IMAGE SIZE?
        url: '...',
        secure_url: '...'
      }
    ]
  }*/
}, {
  type: 'upload',
  eager: {
    transformation: [
      {
        crop: 'crop',
        x: 0,
        y: 0,
        width: 3264,
        height: 2448 // <= difference
      },
      {
        crop: 'limit',
        width: 1140,
        height: 496,
        gravity: 'center',
        quality: 90,
        flags: 'progressive',
        format: 'jpg'
      }
    ]
  }
});
```

**Comment by taragano** [comment]
I'm sorry for my response delay.

Does this still happen to you?
If so, we'll be happy to know more about it. Can you please re-try performing these calls now, and if it happens again then please share: 

+ The exact calls you passed
+ The public IDs that worked and didn't work for you
+ Your cloud name
+ And the timestamps of the requests.

If privacy is an issue, please feel free to contact us at support@cloudinary.com

**Comment by Frenzzy** [comment]
Yes, it still happens.

I made a minimal version to help you find the problem:
https://github.com/Frenzzy/cloudinary-transform-test

This happens not only on my account, and not always, so just in case:
- Call: https://github.com/Frenzzy/cloudinary-transform-test/blob/master/index.js#L70
- Public ID: `test/size-test`
- Cloud name: `frenzzy`
- Timestamp: `1449239613568` or Fri Dec 04 2015 17:33:33 GMT+0300 (MSK)

Regards.

**Comment by frenzzy** [comment]
Is there any news?

**Comment by AGresvig** [comment]
ding!
