### ISSUE TITLE
"Uncaught ReferenceError: image is not defineds"

### ISSUE THREAD

**Issue by nonelove** [cloudinary/cloudinary_npm#78]
Uncaught ReferenceError: image is not defineds
 @ all.js:105rt.event.dispatch
 @ all.js:2m.handle
 @ all.js:2

I'm using Cloudinary widget. But, after a url is set to 'Public URL of an image file:' in Cloudinary widget, the error message above occurs.

![screen shot 2015-12-21 at 11 48 19 am](https://cloud.githubusercontent.com/assets/7032221/11922259/c96a97d6-a7d8-11e5-9738-38251433e96a.png)

**Comment by roeeba** [comment]
The issue was recently resolved.

**Comment by VFK** [comment]
It was not. Try your own [Quick Example](http://cloudinary.com/documentation/upload_widget#quick_example) cropping is broken (Web Address tab).

`all.js:105 Uncaught TypeError: Cannot read property 'width' of undefined`

**Comment by roeeba** [comment]
You're probably getting the old version of the JS file. Please try and hard refresh the page (command+option+R on Mac or ctrl+F5 on Windows).

**Comment by VFK** [comment]
@roeeba I did a couple of thousand times. I'm getting `http://widget.cloudinary.com/v/hzxyensd5/6aa9cf82aa7b7dfe47778f3d7e5dfb7b/all.js` one. Try to open the widget (the one with cropping) in one tab and any page with images in another tab. Drag any image from other tab to the widget.

**Comment by roeeba** [comment]
@VFK Please try again. It should be okay now.

**Comment by VFK** [comment]
@roeeba It's working now, thank you
