### ISSUE TITLE
issue with react native 0.14

### ISSUE THREAD

**Issue by ethantran** [cloudinary/cloudinary_npm#79]
Unable to resolve module url from /Users/ethan/project/node_modules/cloudinary/lib/config.js: invalid directory /Users/node_modules/url

**Comment by taragano** [comment]
Hi,
I'm sorry for my response delay.

Do you still experience this issue? If so, can you please share some more information and some relevant code snippets?

**Comment by ethandt92** [comment]
Yes this issue still exists. There is not much code involved since the error happens on import.
```
import cloudinary from 'cloudinary'
```
I am guessing this happens since it uses libs that exist in node.js but not in react native.

**Comment by madibalive** [comment]
getting same error in cordova app, it seem to require the fs module , which is not available on the system , it not a node environment , is there way that uploader can a file without fs

**Comment by tocker** [comment]
@ethandt92 please use cloudinary-core instead of this library.

```
npm install lodash
npm install cloudinary-core
```

The name of the library is `cloudinary-core`, so to import the entire namespace, use the following code:
```javascript
import * as cloudinary from 'cloudinary-core';

var html = cloudinary.ImageTag.new( "sample", { cloud_name: "demo", width: 200, crop: "scale"}).toHtml();
```

**Comment by madibalive** [comment]
@tocker  am assuming the same applies for angular 2 -- ionic 2 app

**Comment by tocker** [comment]
@madibalive yes. We do have an Angular library - [cloudinary_ng](https://github.com/cloudinary/cloudinary_angular) - but it has not been tested on Angular 2 yet.

**Comment by tprupsys** [comment]
@tocker, I've tried with lodash and cloudinary-core, though still getting an issue, this time with url lib:
`Unable to resolve module url from .../node_modules/cloudinary-core/cloudinary-core.js...`

**Comment by ronaldheft** [comment]
@tocker @tprupsys Same issue using cloudinary-core on React Native 0.31

```
npm install cloudinary-core --save
import * as cloudinary from 'cloudinary-core/cloudinary-core-shrinkwrap.js';
```

**Comment by NamanAulakh** [comment]
same issue with "react-native": "0.35.0"

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. We’ll consider implementing it in the future React-Native SDK. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
