### ISSUE TITLE
Upload progress

### ISSUE THREAD

**Issue by ChristianRich** [cloudinary/cloudinary_npm#84]
Using below snippet, how would I get the upload progress?

```
cloudinary.uploader.upload("my_picture.jpg", function(result) { 
  console.log(result) 
});
```

If above method does not support progress events is there another method that does?
I don't see that the documentation states anything about image upload progress.

What about the bind('fileuploadprogress') method as described for the jQuery API?
http://support.cloudinary.com/hc/en-us/articles/202520672-How-to-create-an-upload-progress-bar-

Would something similar apply for Node?

**Comment by taragano** [comment]
We currently support upload progress indication only when doing client-side uploads via our jQuery plugin, as you mentioned, with the `fileuploadprogress` event.

This is demonstrated in our [sample project](https://github.com/cloudinary/cloudinary_npm/tree/master/samples/photo_album), specifically:
https://github.com/cloudinary/cloudinary_npm/blob/master/samples/photo_album/views/photos/add_direct.ejs#L70

**Comment by ChristianRich** [comment]
Thanks. I had the feeling upload progress was is not supported server side, but thanks for clarifying.

**Comment by usamamashkoor** [comment]
Does the `fileuploadprogress ` event is supported in react?

**Comment by dannyv-cloudinary** [comment]
Hi @usamamashkoor .

I'm afraid it's not supported directly within React at this time however, taragano's code snippet above may be a helpful workaround.

Many thanks,
-Danny
