### ISSUE TITLE
Passing public_id to overlay does not support folders

### ISSUE THREAD

**Issue by baldurh** [cloudinary/cloudinary_npm#88]
According to the documentation you can pass a string to the overlay parameter in options when generating urls and image tags:
`cloudinary.url("mountain.jpg", { overlay: "cloudinary_icon", width: 100 })`

While this works fine for images in the root folder, it fails when trying to overlay images from subfolders:
`cloudinary.url("mountain.jpg", { overlay: "sub/cloudinary_icon", width: 100 })`

Now, there is a workaround which works fine:
`cloudinary.url("mountain.jpg", { overlay: { public_id: "sub/cloudinary_icon" }, width: 100 })`

This however, is not described in the docs. At least I only figured it out by looking at the code.

Working examples:
```JavaScript
cloudinary.url(publicId, {
    secure: true,
    transformation: [
      {
        width: 1000,
        height: 525,
        crop: 'fill'
      },
      {
        overlay: 'moment-play',
      },
      {
        overlay: 'one_pixel',
        gravity: 'north_west',
        width: 80,
        y: 30,
        x: 30,
        color: channel.brandColor,
        effect: ['colorize']
      },
      {
        overlay: channelLogoPublicId,
        gravity: 'north_west',
        width: 70,
        y: 35,
        x: 35
      }
    ]
  });
```
produces (broken):
[https://res.cloudinary.com/oz/image/upload/c_fill,h_525,w_1000/l_moment-play/co_rgb:d61784,e_colorize,g_north_west,l_one_pixel,w_80,x_30,y_30/g_north_west,l_c1f9064b-088f-4a42-9c8a-1f67eb441aa8/hb7m5uji8g2wzkxhja7f.png,w_70,x_35,y_35/v1/moments/c1f9064b-088f-4a42-9c8a-1f67eb441aa8/8de2716d-d59f-4b9c-a95e-021ae0e4ae88/4670f28d-4c6e-49f0-a7d8-125791545c5e_540_pv.jpg](https://res.cloudinary.com/oz/image/upload/c_fill,h_525,w_1000/l_moment-play/co_rgb:d61784,e_colorize,g_north_west,l_one_pixel,w_80,x_30,y_30/g_north_west,l_c1f9064b-088f-4a42-9c8a-1f67eb441aa8/hb7m5uji8g2wzkxhja7f.png,w_70,x_35,y_35/v1/moments/c1f9064b-088f-4a42-9c8a-1f67eb441aa8/8de2716d-d59f-4b9c-a95e-021ae0e4ae88/4670f28d-4c6e-49f0-a7d8-125791545c5e_540_pv.jpg)

```JavaScript
cloudinary.url(publicId, {
    secure: true,
    transformation: [
      {
        width: 1000,
        height: 525,
        crop: 'fill'
      },
      {
        overlay: 'moment-play',
      },
      {
        overlay: 'one_pixel',
        gravity: 'north_west',
        width: 80,
        y: 30,
        x: 30,
        color: channel.brandColor,
        effect: ['colorize']
      },
      {
        overlay: {
          public_id: channelLogoPublicId
        },
        gravity: 'north_west',
        width: 70,
        y: 35,
        x: 35
      }
    ]
  });
```
produces (working):
[https://res.cloudinary.com/oz/image/upload/c_fill,h_525,w_1000/l_moment-play/co_rgb:d61784,e_colorize,g_north_west,l_one_pixel,w_80,x_30,y_30/g_north_west,l_c1f9064b-088f-4a42-9c8a-1f67eb441aa8:hb7m5uji8g2wzkxhja7f.png,w_70,x_35,y_35/v1/moments/c1f9064b-088f-4a42-9c8a-1f67eb441aa8/8de2716d-d59f-4b9c-a95e-021ae0e4ae88/4670f28d-4c6e-49f0-a7d8-125791545c5e_540_pv.jpg](https://res.cloudinary.com/oz/image/upload/c_fill,h_525,w_1000/l_moment-play/co_rgb:d61784,e_colorize,g_north_west,l_one_pixel,w_80,x_30,y_30/g_north_west,l_c1f9064b-088f-4a42-9c8a-1f67eb441aa8:hb7m5uji8g2wzkxhja7f.png,w_70,x_35,y_35/v1/moments/c1f9064b-088f-4a42-9c8a-1f67eb441aa8/8de2716d-d59f-4b9c-a95e-021ae0e4ae88/4670f28d-4c6e-49f0-a7d8-125791545c5e_540_pv.jpg)

**Comment by taragano** [comment]
You need to use `:` instead of `/` for images within overlays/underlays, as explained in the following KB article:
https://support.cloudinary.com/hc/en-us/articles/202521352-How-to-use-an-image-from-a-sub-folder-as-an-overlay-

So you can use either use (as you already figured out):

    cloudinary.url("mountain.jpg", { overlay: { public_id: "sub/cloudinary_icon" }, width: 100 })
or:

    cloudinary.url("mountain.jpg", { overlay: "sub:cloudinary_icon", width: 100 })

**Comment by baldurh** [comment]
I had actually seen that article and started out by replacing `/` with `:` myself. However, then you don't have the `public_id` anymore but a modified version of it. Also, this is undocumented, apart from the article. I truly feel the sdk should take care of doing this. Otherwise the users of the sdk need to know when to replace them and when not to.

**Comment by taragano** [comment]
Note that using the `public_id` parameter, e.g.,:

```
cloudinary.url("mountain.jpg", { overlay: { public_id: "sub/cloudinary_icon" }, width: 100 })
```
is actually the official support by the SDK, and not a workaround.
This way you don't need to worry about modifying the public ID, the SDK takes care of it for you.
This is indeed undocumented yet, and it's on our road map to add this to our docs.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues

**Comment by lil5** [comment]
```js
cloudinary.imageTag('yellow_tulip.jpg', {transformation: [
  {width: 220, height: 140, crop: "fill"},
  {overlay: new cloudinary.Layer().publicId("brown_sheep"), width: 220, height: 140, x: 220, crop: "fill"},
  {overlay: new cloudinary.Layer().publicId("horses"), width: 220, height: 140, y: 140, x: -110, crop: "fill"},
  {overlay: new cloudinary.Layer().publicId("white_chicken"), width: 220, height: 140, y: 70, x: 110, crop: "fill"},
  {overlay: new cloudinary.Layer().publicId("butterfly.png"), height: 200, x: -10, angle: 10},
  {width: 400, height: 260, radius: 20, crop: "crop"},
  {overlay: new cloudinary.TextLayer().fontFamily("Parisienne").fontSize(35).fontWeight("bold").text("Memories%20from%20our%20trip"), color: "#990C47", y: 155},
  {effect: "shadow"}
  ]}).toHtml();
```

The example (above) in the cloudinary documentation (https://cloudinary.com/documentation/image_transformations#adding_image_underlays) does not work.

The only way I managed to get an underlay/overlay was with @taragano answer:

```js
cloudinary.url("mountain.jpg", { overlay: { public_id: "sub/cloudinary_icon" }, width: 100 })
```

**Comment by eyalktCloudinary** [comment]
@lil5 Thanks for your feedback!
Notice that the `imageTag()` method is part of our JS SDK, where it seems to me that you're using our Node.js SDK.
The Node.js SDK method for creating an image tag is `image()` -
```
cloudinary.image("mountain.jpg", { overlay: { public_id: "sub/cloudinary_icon" }, width: 100 })
```
I couldn't find an `imageTag` example such as the one you've shared under Node.js examples in the mentioned documentation page. Could you kindly direct me to the relevant place so we could fix it??

**Comment by lil5** [comment]
@eyalktCloudinary Thanks for the additional information, indeed I hadn't noticed.

Although I don't see the need to separate NodeJS from Web JS, just for generating a url 😂

 To answer your question I'm using the NodeJS SDK in the browser with `.url({transformation: []})` to output a url. And was look at the documentation for the JS SDK (oops 😅). TLDR: was some PEBCAK
