### ISSUE TITLE
[Suggestion] Allow passing absolute urls to .image() and .url()

### ISSUE THREAD

**Issue by baldurh** [cloudinary/cloudinary_npm#90]
We are storing absolute cloudinary urls in our database. The clients can then decide how they want to transform the urls. Now we are running into (minor) problems using these absolute urls with this sdk.

We just removed the parts of the urls before passing them into these methods.
Examples of urls we are working with:

```
http://res.cloudinary.com/oz/image/upload/moments/c1f9064b-088f-4a42-9c8a-1f67eb441aa8/e88d82b4-d2ae-4d63-8988-25a275b4b960/70ac2da0-34df-4b57-be61-3c88fa1655b0_540_pv.jpg
----------------------------------------- ^ public_id begins
```
```
https://res.cloudinary.com/oz/moments/c1f9064b-088f-4a42-9c8a-1f67eb441aa8/e88d82b4-d2ae-4d63-8988-25a275b4b960/70ac2da0-34df-4b57-be61-3c88fa1655b0_540_pv.jpg
----------------------------- ^ public_id begins (auto upload rule applies)
```
```
http://res.cloudinary.com/oz/image/upload/v1454951830/moments/musicreach/f3432155-1be9-4510-9c3a-c1672c21fc89/f5de39a0-7ad0-48de-b53b-1d148856bcb8_540_pv.jpg
----------------------------------------------------- ^ public_id begins
```

So we created this simple method to extract the `public_id` from the absolute url:
```JavaScript
function getPublicId (url) {
  return url.replace('image/upload/', '')
  .replace('://res.cloudinary.com/oz/', '')
  .replace(/https?/, '')
  // Removes version part
  .replace(/v[^\/]*\//, '');
}
```
Of course this method is specific to our needs.
The thing is we are not sure whether this handles all possible cases. It would be really helpful if one could just pass the absolute url to the sdk and it would take care of extracting the `public_id`.
Another possible solution would be to expose a method for extracting the `public_id` from any cloudinary url.

**Comment by taragano** [comment]
Currently we indeed don't offer a helper method in our SDKs to parse the public ID from a full Cloudinary URL. We'd actually recommend to not store the whole URL. Instead, you can store the public ID (we recommend to also store the `version` if you override your images), and then it's easier to generate URLs, including transformations.

**Comment by baldurh** [comment]
Yeah, currently we're storing the them as absolute urls. It's on our backlog to change that 😊

**Comment by taragano** [comment]
Hן @baldurh,
Just wanted to verify whether there's anything else we can help you with?

**Comment by baldurh** [comment]
Not really, thanks.

**Comment by taragano** [comment]
Thank you. 
Please feel free to contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) for any further assistance.
