### ISSUE TITLE
cloudinary-core doesnt support uploader method

### ISSUE THREAD

**Issue by madibalive** [cloudinary/cloudinary_npm#92]
am currently using cloudinary-core , i have lodash installed to upload video and images to cloudinary ,using the npm module.
Set up is angular 2 + ionic 2 ,it seem to only have the these methods 

```
Cloudinary(options)
Configuration
:
Configuration(options)
HtmlTag
:
HtmlTag(name, publicId, options)
ImageTag
:
ImageTag(publicId, options)
Transformation
:
Transformation(options)
Util
:
Object
VideoTag
:
VideoTag(publicId, options)
crc32
:
(str)
default
:
Object
utf8_encode
:
(argString) 
```

doing this fails , following the guide on the npm documentation @tocker 

```
   cloudinary.uploader.upload("http://www.example.com/image.jpg", function(result) {
            console.log(result)
        });
```

hey  @tocker #79  -- can you help

**Comment by taragano** [comment]
@madibalive - I believe there's a small confusion here.
Note that cloudinary-core is a pure JS (client-side) library.
Angular has a separate library.
And the `cloudinary.uploader.upload` code snippet is used by our Node.js (server-side) library.
Each one is used differently and with different methods.

While the `cloudinary-core` package is installed with NPM, this specific "cloudinary_npm" repository is for Cloudinary's Node.js library.

I hope this makes more sense now.

**Comment by madibalive** [comment]
Hi thanks for the reply , how to upload to file to cloudinary , the cloudinary npm module resolve to error (cant find fs ) , am running in a cordova environment , is it possible to upload using the any library ,am using angular 2 , not angular 1

**Comment by tocker** [comment]
The upload function is not included in the core library because it had to support a wide variety of platforms each with its own HTTP mechanism (and issues).
You can implement your own upload function using the following example: https://jsfiddle.net/tocker/fpoca4c8/

I hope this helps!

**Comment by Spy-Seth** [comment]
Ho yes ! It helps a lot !

You should document this on your official documentation. It's really hard to find this issue.

**Comment by taragano** [comment]
Thank you for your reply @Spy-Seth, I'm glad we could be of assistance.

Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
