### ISSUE TITLE
Docs don't match invocation params of Uploader function. 

### ISSUE THREAD

**Issue by psolbach** [cloudinary/cloudinary_npm#95]
Just a quick heads up.

While your [node docs](http://cloudinary.com/documentation/node_integration) state to call `uploader.upload()` with `file, callback, options` in order to set a **Public ID**, it is clear by looking at the function definition [here](https://github.com/cloudinary/cloudinary_npm/blob/master/lib/uploader.js#L60) that it should be `filename, options, callback`. Swapping the params results in a `TypeError`.

**Comment by taragano** [comment]
Hi @psolbach,
I apologize for the response delay.

We indeed initially implemented our SDK with Upload calls like:

```
cloudinary.uploader.upload('my_image.jpg', function(result) { console.log(result) }, 
                           { public_id: "sample_id" });
```
However, after requests from the community, we added support for the other convention, note that it is used with the `v2` version, e.g.,:

```
cloudinary.v2.uploader.upload("sample.jpg", 
    { public_id: "sample_id" }, 
    function(error, result) { console.log(result); });
```

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
