### ISSUE TITLE
Trying to call `upload` fails silently if you have not called `config`

### ISSUE THREAD

**Issue by thomasdavis** [cloudinary/cloudinary_npm#96]
```
const cloudinary = require('cloudinary');
cloudinary.uploader.upload("http://www.example.com/image.jpg", function(result) {
  console.log(result)
});
```

Says nothing, should detect if you have configured first.

**Comment by taragano** [comment]
Hi @thomasdavis,
I'm sorry for the delay response.

When I tried it there was indeed a displayed error message `Must supply api_key`.
Can you please make sure you have updated versions of node and our Node SDK?

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues
