### ISSUE TITLE
Audio upload

### ISSUE THREAD

**Issue by slaymantis** [cloudinary/cloudinary_npm#98]
Hello

I am trying to get audio to upload with cloudinary.
I see the code in cloudinary.js

There are methods there for images and video
exports.image = function (source, options) 
exports.video = function (public_id, options)

Any suggestions?

**Comment by roeeba** [comment]
In Cloudinary audio files are treated as video resources, and therefore are uploaded the same.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
